{1}{}{PID_METAL_PARTS@Various irregular pieces of metal, all shapes and sizes. Nothing special, but you suppose it could be turned into something worthwhile given the right expertise and equipment.@@@PID_METAL_ORE 2@PID_WORKBENCH_PRIMITIVE 1|PID_WORKBENCH 1@PID_METAL_PARTS 1@exp 0 script fix_boy@fix_Resource}
{2}{}{PID_METAL_PARTS10@Various irregular pieces of metal, all shapes and sizes. Nothing special, but you suppose it could be turned into something worthwhile given the right expertise and equipment.@@@PID_METAL_ORE 20@PID_WORKBENCH_PRIMITIVE 1|PID_WORKBENCH 1@PID_METAL_PARTS 10@exp 0 script fix_boy@fix_Resource}
{3}{}{PID_GUNPOWDER@A box with a black powder.@@@PID_MINERAL 1@PID_WORKBENCH_PRIMITIVE 1|PID_WORKBENCH 1@PID_GUNPOWDER 1@exp 0 script fix_boy@fix_Resource}
{4}{}{PID_GUNPOWDER10@A box with a black powder.@@@PID_MINERAL 10@PID_WORKBENCH_PRIMITIVE 1|PID_WORKBENCH 1@PID_GUNPOWDER 10@exp 0 script fix_boy@fix_Resource}
{5}{}{PID_ALLOYS@Some alloys. You could use them for repairing and upgrading equipment, or any other engineering projects.@@@PID_MINERAL 2&PID_METAL_ORE 2@PID_WORKBENCH_PRIMITIVE 1|PID_WORKBENCH 1@PID_ALLOYS 1@exp 0 script fix_boy@fix_Resource}
{6}{}{PID_ALLOYS5@Some alloys. You could use them for repairing and upgrading equipment, or any other engineering projects.@@@PID_METAL_ORE 10&PID_MINERAL 10@PID_WORKBENCH_PRIMITIVE 1|PID_WORKBENCH 1@PID_ALLOYS 5@exp 0 script fix_boy@fix_Resource}
{7}{}{PID_METAL_PARTS2@Various irregular pieces of good metal, all shapes and sizes. Nothing special, but you suppose it could be turned into something worthwhile given the right expertise and equipment.@@@PID_ORE2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_METAL_PARTS2 1@exp 0 script fix_boy@fix_Resource}
{8}{}{PID_METAL_PARTS210@Various irregular pieces of good metal, all shapes and sizes. Nothing special, but you suppose it could be turned into something worthwhile given the right expertise and equipment.@@@PID_ORE2 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_METAL_PARTS2 10@exp 0 script fix_boy@fix_Resource}
{9}{}{PID_GUNPOWDER2@A box with a better black powder.@@@PID_MINERALS2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_GUNPOWDER2 1@exp 0 script fix_boy@fix_Resource}
{10}{}{PID_GUNPOWDER210@A box with a better black powder.@@@PID_MINERALS2 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_GUNPOWDER2 10@exp 0 script fix_boy@fix_Resource}
{11}{}{PID_ALLOYS2@Alloys of a very good quality. You could use them for repairing and upgrading equipment, or any other engineering projects@@@PID_MINERALS2 1&PID_ORE2 1@PID_ADVANCED_BENCH 1@PID_ALLOYS2 1@exp 0 script fix_boy@fix_Resource}
{12}{}{PID_ALLOYS25@Alloys of a very good quality. You could use them for repairing and upgrading equipment, or any other engineering projects@@@PID_MINERALS2 5&PID_ORE2 5@PID_ADVANCED_BENCH 1@PID_ALLOYS2 5@exp 0 script fix_boy@fix_Resource}
{13}{}{PID_LEATHER_JACKET@A black, heavy leather jacket.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_FIBER 1&PID_GECKO_PELT 5@PID_WORKBENCH 1@PID_LEATHER_JACKET 1@exp 70 script fix_boy@fix_Generic}
{14}{}{PID_LEATHER_JACKET_HELMET@These leather helmets are extremely popular throughout the known wasteland. Easy to make and also known as 'aviatior helmets', they fit perfectly to any leather jacket. Unfortunately, they provide quite limited head protection.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_FIBER 1&PID_GECKO_PELT 2@PID_WORKBENCH 1@PID_LEATHER_JACKET_HELMET 1@exp 20 script fix_boy@fix_Generic}
{15}{}{PID_CURED_LEATHER_ARMOR@This heavily padded leather jacket is unusual in that it has two sleeves. You'll definitely make a fashion statement whenever, and wherever, you rumble.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_FIBER 1&PID_GECKO_PELT 5&PID_GOLDEN_GECKO_PELT 2&PID_BRAHMIN_HIDE 1&PID_LEATHER_JACKET 1@PID_WORKBENCH 1@PID_CURED_LEATHER_ARMOR 1@exp 130 script fix_boy@fix_Generic}
{16}{}{PID_COMBAT_LEATHER_JACKET_HELMET@With eye-protective goggles and an extra layer of sturdy leather, this helmet certainly provides better damage resistance for your skull than the regular one.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_FIBER 1&PID_PUMP_PARTS 1&PID_GECKO_PELT 1&PID_GOLDEN_GECKO_PELT 1&PID_LEATHER_JACKET_HELMET 1@PID_WORKBENCH 1@PID_COMBAT_LEATHER_JACKET_HELMET 1@exp 40 script fix_boy@fix_Generic}
{17}{}{PID_LEATHER_ARMOR@Your basic all leather apparel. Finely crafted from tanned brahmin hide.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_FIBER 1&PID_GOLDEN_GECKO_PELT 5@PID_WORKBENCH 1@PID_LEATHER_ARMOR 1@exp 135 script fix_boy@fix_Generic}
{18}{}{PID_LEATHER_ARMOR_HELMET@Just like common leather armors, this helmet is based on pre-War armor designed for motorcycle riding, football, and other dangerous contact sports. The side slots can be upgraded with headphones for the Wattz Electronics 2043B Radio.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_FIBER 1&PID_GOLDEN_GECKO_PELT 2@PID_WORKBENCH 1@PID_LEATHER_ARMOR_HELMET 1@exp 40 script fix_boy@fix_Generic}
{19}{}{PID_LEATHER_ARMOR_MK_II@An enhanced version of the basic leather armor with extra layers of protection. Finely crafted from tanned brahmin hide.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_LEATHER_ARMOR 1&PID_GOLDEN_GECKO_PELT 2&PID_BRAHMIN_HIDE 1@PID_WORKBENCH 1@PID_LEATHER_ARMOR_MK_II 1@exp 60 script fix_boy@fix_Generic}
{20}{}{PID_LEATHER_ARMOR_HELMET_MK2@With an additional layer of sturdy leather and heat resistant welding goggles, this helmet is the best head protection gear wasteland armorers can make out of leather.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_PUMP_PARTS 1&PID_GOLDEN_GECKO_PELT 1&PID_LEATHER_ARMOR_HELMET 1@PID_WORKBENCH 1@PID_LEATHER_ARMOR_HELMET_MK2 1@exp 30 script fix_boy@fix_Generic}
{21}{}{PID_METAL_ARMOR@Polished metal plates, crudely forming a suit of armor.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_FIBER 1&PID_BRAHMIN_HIDE 1&PID_METAL_PARTS 4&PID_ALLOYS 3@PID_WORKBENCH 1@PID_METAL_ARMOR 1@exp 200 script fix_boy@fix_Generic}
{22}{}{PID_METAL_HELMET@Although somewhat heavy and impractical, this Metal Mask offers quite a solid protection and, as an extra effect, scares away annoying kids. Due to its composition, it offers no protection against electric shocks.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_FIBER 1&PID_BRAHMIN_HIDE 1&PID_ALLOYS 1&PID_METAL_PARTS 1@PID_WORKBENCH 1@PID_METAL_HELMET 1@exp 135 script fix_boy@fix_Generic}
{23}{}{PID_METAL_ARMOR_MK_II@Polished metal plates, finely crafted into a suit of armor.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2@PID_METAL_PARTS2 1&PID_METAL_ARMOR 1&PID_FIBER 1@PID_ADVANCED_BENCH 1@PID_METAL_ARMOR_MK_II 1@exp 61 script fix_boy@fix_Blueprint}
{24}{}{PID_METAL_HELMET_MK2@Substantially enhanced in several critical spots with high quality metal parts and polished with care, this metal mask will hardly break or get rusty over time.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2@PID_METAL_PARTS2 1&PID_METAL_HELMET 1&PID_FIBER 1@PID_ADVANCED_BENCH 1@PID_METAL_HELMET_MK2 1@exp 40 script fix_boy@fix_Blueprint}
{25}{}{PID_TESLA_ARMOR@This shining armor provides superior protection against energy attacks. The three Tesla Attraction Coil Rods disperse a large percentage of directed energy attacks.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2@PID_METAL_ARMOR 1&PID_ALLOYS2 1&PID_ELECTRONIC_PARTS 4@PID_ADVANCED_BENCH 1@PID_TESLA_ARMOR 1@exp 100 script fix_boy@fix_Blueprint}
{26}{}{PID_TESLA_HELMET@Just like Tesla Armor, this helmet with autonomous power supply uses electromagnetic field to keep hot plasma away from your head. Quite simple, yet unique design, based on some ancient pre-War experiments and blueprints.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2@PID_METAL_PARTS2 1&PID_ALLOYS2 2&PID_ELECTRONIC_PARTS 2@PID_ADVANCED_BENCH 1@PID_TESLA_HELMET 1@exp 200 script fix_boy@fix_Blueprint}
{27}{}{PID_COMBAT_ARMOR@High tech armor, made out of advanced defensive polymers.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2@PID_ALLOYS2 5&PID_METAL_PARTS 1&PID_FIBRE2 1@PID_ADVANCED_BENCH 1@PID_COMBAT_ARMOR 1@exp 444 script fix_boy@fix_Blueprint}
{28}{}{PID_COMBAT_HELMET@Before The Great War, this combat helmet was standard-issue along with combat armor. Good overall protection with laser target designation and fancy shielding glass.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2@PID_ALLOYS2 2&PID_METAL_PARTS 1&PID_FIBER 1@PID_ADVANCED_BENCH 1@PID_COMBAT_HELMET 1@exp 675 script fix_boy@fix_Blueprint}
{29}{}{PID_COMBAT_ARMOR_MK_II@High tech armor, made out of advanced defensive polymers.@PE_PROFESSION_ARMORER 3@PE_PROFESSION_ARMORER 3@PID_COMBAT_ARMOR 1&PID_ALLOYS2 2&PID_METAL_PARTS2 1@PID_ADVANCED_BENCH 1@PID_COMBAT_ARMOR_MK_II 1@exp 600 script fix_boy@fix_Blueprint}
{30}{}{PID_BROTHERHOOD_COMBAT_ARMOR@A superior version of Combat Armor. The Brotherhood of Steel have made many improvements over the standard version.@PE_PROFESSION_ARMORER 3@PE_PROFESSION_ARMORER 3@PID_COMBAT_ARMOR 1&PID_METAL_PARTS2 1&PID_ALLOYS2 4&PID_FIBER 3@PID_ADVANCED_BENCH 1@PID_BROTHERHOOD_COMBAT_ARMOR 1@exp 1000 script fix_boy@fix_Blueprint}
{31}{}{PID_9MM_BALL@A collection of ancient 9x19mm rounds. Heavy grease to preserve them from the environment. Standard bullets.@@@PID_METAL_PARTS 1&PID_GUNPOWDER 4@@PID_9MM_BALL 100@exp 52 script fix_boy@fix_Generic}
{32}{}{PID_10MM_JHP@Ammunition. Caliber: 10mm, jacketed hollow-points@@@PID_METAL_PARTS 1&PID_GUNPOWDER 8@PID_WORKBENCH 1@PID_10MM_JHP 100@exp 100 script fix_boy@fix_Generic}
{33}{}{PID_10MM_AP@Ammunition. Caliber: 10mm, armor piercing.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1@PID_10MM_AP 100@exp 100 script fix_boy@fix_Blueprint}
{34}{}{PID_44_MAGNUM_JHP@A brick of ammunition, .44 Magnum caliber, hollow-points.@@@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1@PID_44_MAGNUM_JHP 100@exp 100 script fix_boy@fix_Generic}
{35}{}{PID_44_FMJ_MAGNUM@A brick of ammunition, .44 Magnum caliber, full metal jacket.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1@PID_44_FMJ_MAGNUM 100@exp 100 script fix_boy@fix_Generic}
{36}{}{PID_HN_NEEDLER_CARTRIDGE@Ammunition. This cartridge appears to be ammo for the HN Needler Pistol. Each 'bullet' is a small hypodermic designed to inject a target with its contents upon impact.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 1@PID_ADVANCED_BENCH 1@PID_HN_NEEDLER_CARTRIDGE 100@exp 46 script fix_boy@fix_Blueprint}
{37}{}{PID_14MM_AP@Large caliber ammunition. 14mm armor piercing.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 4@PID_ADVANCED_BENCH 1@PID_14MM_AP 100@exp 125 script fix_boy@fix_Blueprint}
{38}{}{PID_223_FMJ@A case of ammunition, .223 caliber, Full Metal Jacket.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 5@PID_ADVANCED_BENCH 1@PID_223_FMJ 100@exp 147 script fix_boy@fix_Blueprint}
{39}{}{PID_45_CALIBER_AMMO@Ammunition. .45 Caliber.@@@PID_GUNPOWDER 2&PID_PUMP_PARTS 1@PID_WORKBENCH 1@PID_45_CALIBER_AMMO 100@exp 18 script fix_boy@fix_Generic}
{40}{}{PID_BBS@A package of BB's from before the war. In excellent condition. Stainless steel.@@@PID_PUMP_PARTS 4@@PID_BBS 50@exp 8 script fix_boy@fix_Generic}
{41}{}{PID_22_AMMO@Ammunition for hunting, .22 caliber soft point.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1@PID_22_AMMO 100@exp 100 script fix_boy@fix_Generic}
{42}{}{PID_5MM_JHP@A brick of small, lightweight ammunition. Caliber: 5mm, jacketed hollow-point.@PE_PROFESSION_GUNSMITH_B 1|PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_B 1|PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_GUNPOWDER 4@PID_WORKBENCH 1@PID_5MM_JHP 100@exp 50 script fix_boy@fix_Generic}
{43}{}{PID_5MM_AP@A brick of small caliber ammunition. 5mm armor piercing.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PID_METAL_PARTS 2&PID_GUNPOWDER2 1@PID_ADVANCED_BENCH 1@PID_5MM_AP 100@exp 66 script fix_boy@fix_Blueprint}
{44}{}{PID_7_62MM_AMMO@Ammunition. Caliber: 7.62mm.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 5@PID_ADVANCED_BENCH 1@PID_7_62MM_AMMO 100@exp 148 script fix_boy@fix_Blueprint}
{45}{}{PID_SHOTGUN_SHELLS@12 ga. Shotgun Shells@@@PID_METAL_PARTS 1&PID_GUNPOWDER 9@PID_WORKBENCH 1@PID_SHOTGUN_SHELLS 100@exp 92 script fix_boy@fix_Generic}
{46}{}{PID_FLAMETHROWER_FUEL@A cylinder containing an extremely flammable liquid fuel for flamethrowers.@@@PID_ROT_GUT 4@PID_WORKBENCH 1@PID_FLAMETHROWER_FUEL 120@exp 60 script fix_boy@fix_Generic}
{47}{}{PID_ADV_SUPERBURN@A component of the flamethrower fuel. Makes fuel even more hot and dangerous.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_GUNPOWDER2 2@PID_ADVANCED_BENCH 1@PID_ADV_SUPERBURN 100@exp 51 script fix_boy@fix_Generic}
{48}{}{PID_FLAMETHROWER_FUEL_MK_II@This flamethrower fuel uses an advanced super-burn mix.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_ADV_SUPERBURN 1&PID_FLAMETHROWER_FUEL 40@PID_WORKBENCH 1@PID_FLAMETHROWER_FUEL_MK_II 40@exp 0 script fix_boy@fix_Blueprint}
{49}{}{PID_EXPLOSIVE_ROCKET@A rocket with a large explosive warhead.@PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_B 1@PID_METAL_PARTS 1&PID_GUNPOWDER 6@PID_WORKBENCH 1@PID_EXPLOSIVE_ROCKET 10@exp 75 script fix_boy@fix_Generic}
{50}{}{PID_ROCKET_AP@A rocket shell, with a smaller explosive, but designed to pierce armor plating.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 5&PID_ELECTRONIC_PARTS 1@PID_ADVANCED_BENCH 1@PID_ROCKET_AP 10@exp 150 script fix_boy@fix_Blueprint}
{51}{}{PID_SMALL_ENERGY_CELL@A small, self-contained energy storage unit.@@@PID_ELECTRONIC_PARTS 6&PID_ALLOYS 2@PID_WORKBENCH 1@PID_SMALL_ENERGY_CELL 100@exp 102 script fix_boy@fix_Generic}
{52}{}{PID_MICRO_FUSION_CELL@A medium sized energy production unit. Self-contained fusion plant.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_REFINED_ORE 3&PID_ALLOYS 1&PID_ELECTRONIC_PARTS 1@PID_ADVANCED_BENCH 1@PID_MICRO_FUSION_CELL 100@exp 153 script fix_boy@fix_Blueprint}
{53}{}{PID_9MM_MAUSER@A Mauser M/96, in 9x19mm Parabellum. In excellent condition. Extremely accurate. @@@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_PUMP_PARTS 3@PID_WORKBENCH 1@PID_9MM_MAUSER 1@exp 51 script fix_boy@fix_Generic}
{54}{}{PID_10MM_PISTOL@A Colt 6520 10mm autoloading pistol. Each pull of the trigger will automatically reload the firearm until the magazine is empty. Single shot only, using the powerful 10mm round. @@@PID_FIREWOOD 1&PID_METAL_PARTS 5&PID_ALLOYS 1@PID_WORKBENCH 1@PID_10MM_PISTOL 1@exp 141 script fix_boy@fix_Generic}
{55}{}{PID_44_MAGNUM_REVOLVER@Being that this is the most powerful handgun in the world, and can blow your head clean-off, you've got to ask yourself one question. Do I feel lucky? Well, do ya punk? @PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_ALLOYS 2&PID_METAL_PARTS 5@PID_WORKBENCH 1@PID_44_MAGNUM_REVOLVER 1@exp 177 script fix_boy@fix_Generic}
{56}{}{PID_SPEED_LOADER@Useful thingy for faster reloading of a revolver.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_PUMP_PARTS 1@PID_WORKBENCH 1@PID_SPEED_LOADER 1@exp 10 script fix_boy@fix_Generic}
{57}{}{PID_44_MAGNUM_SPEEDLOADER@A .44 Magnum Revolver with a speed loader.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_44_MAGNUM_REVOLVER 1&PID_SPEED_LOADER 1@PID_WORKBENCH 1@PID_44_MAGNUM_SPEEDLOADER 1@exp 0 script fix_boy@fix_Generic}
{58}{}{PID_DESERT_EAGLE@An ancient Desert Eagle pistol, in .44 Magnum. Interest in late 20th century films made this one of the most popular handguns of all times. @PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 3&PID_ALLOYS 3@PID_WORKBENCH 1@PID_DESERT_EAGLE 1@exp 173 script fix_boy@fix_Generic}
{59}{}{PID_EXTENDED_MAGAZINE@An extended magazine, for those who dislike frequent reloading.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_PUMP_PARTS 1@PID_WORKBENCH 1@PID_EXTENDED_MAGAZINE 1@exp 10 script fix_boy@fix_Generic}
{60}{}{PID_DESERT_EAGLE_EXT_MAG@An ancient Desert Eagle pistol, in .44 Magnum. Interest in late 20th century films made this one of the most popular handguns of all times. This one has been equipped with an expanded magazine for longer fun and games!@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_DESERT_EAGLE 1&PID_EXTENDED_MAGAZINE 1@PID_WORKBENCH 1@PID_DESERT_EAGLE_EXT_MAG 1@exp 0 script fix_boy@fix_Generic}
{61}{}{PID_NEEDLER_PISTOL@You suspect this Bringham needler pistol was once used for scientific field studies. It uses small hard-plastic hypodermic darts as ammo. @PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS2 1&PID_ALLOYS 1&PID_METAL_PARTS 3&PID_METAL_PARTS2 1&PID_PUMP_PARTS 5@PID_ADVANCED_BENCH 1@PID_NEEDLER_PISTOL 1@exp 239 script fix_boy@fix_Blueprint}
{62}{}{PID_14MM_PISTOL@A Sig-Sauer 14mm Auto Pistol. Large, single shot handgun. Excellent craftmanship. @PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS 3&PID_METAL_PARTS 3&PID_ALLOYS2 2@PID_ADVANCED_BENCH 1@PID_14MM_PISTOL 1@exp 326 script fix_boy@fix_Blueprint}
{63}{}{PID_223_PISTOL@A .223 rifle modified and cut down to a pistol. This is a one-of-a-kind firearm, obviously made with love and skill. @PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_HUNTING_RIFLE 1&PID_PUMP_PARTS 3&PID_ALLOYS2 1&PID_METAL_PARTS2 2@PID_ADVANCED_BENCH 1@PID_223_PISTOL 1@exp 185 script fix_boy@fix_Blueprint}
{64}{}{PID_GREASE_GUN@This submachine gun filled National Guard arsenals after the Army replaced it with newer weapons. However, the "Grease Gun" was simple and cheap to manufacture so there are quite a few still in use.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 6@PID_WORKBENCH 1@PID_GREASE_GUN 1@exp 125 script fix_boy@fix_Generic}
{65}{}{PID_10MM_SMG@H&K MP9 Submachinegun (10mm variant). A medium-sized SMG, capable of single shot and burst mode.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_METAL_PARTS2 1&PID_ALLOYS 2@PID_ADVANCED_BENCH 1@PID_10MM_SMG 1@exp 117 script fix_boy@fix_Blueprint}
{66}{}{PID_HK_P90C@The Heckler & Koch P90c was just coming into use at the time of the war. The weapon's bullpup layout, and compact design, make it easy to control. The durable P90c is prized for its reliability, and high firepower in a ruggedly-compact package.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS 3&PID_ALLOYS2 1&PID_METAL_PARTS 4&PID_METAL_PARTS2 2@PID_ADVANCED_BENCH 1@PID_HK_P90C 1@exp 372 script fix_boy@fix_Blueprint}
{67}{}{PID_RED_RYDER_BB_GUN@A Red Ryder BB gun. The classic. @@@PID_FIREWOOD 1&PID_PUMP_PARTS 2@PID_WORKBENCH 1@PID_RED_RYDER_BB_GUN 1@exp 24 script fix_boy@fix_Generic}
{68}{}{PID_HUNTING_RIFLE@A Colt Rangemaster semi-automatic rifle, in .22 caliber. Single-shot only.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 4&PID_ALLOYS 3@PID_WORKBENCH 1@PID_HUNTING_RIFLE 1@exp 171 script fix_boy@fix_Generic}
{69}{}{PID_SCOPE@An all-weather optical scope in excellent condition.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_PUMP_PARTS 2@PID_WORKBENCH 1@PID_SCOPE 1@exp 44 script fix_boy@fix_Generic}
{70}{}{PID_SCOPED_HUNTING_RIFLE@Nothing's better than seeing that surprised look on your target's face. The Loophole x20 Scope on this hunting rifle makes it easier than ever before. Accurate from first shot to last, no matter what kind of game you're gunning for.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_HUNTING_RIFLE 1&PID_SCOPE 1@PID_WORKBENCH 1@PID_SCOPED_HUNTING_RIFLE 1@exp 0 script fix_boy@fix_Generic}
{71}{}{PID_SNIPER_RIFLE@A DKS-501 Sniper Rifle. Excellent long range projectile weapon. Originally .308, this one is chambered in the more common .223 caliber.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS2 1&PID_ALLOYS 3&PID_METAL_PARTS 6&PID_METAL_PARTS2 3@PID_ADVANCED_BENCH 1@PID_SNIPER_RIFLE 1@exp 463 script fix_boy@fix_Blueprint}
{72}{}{PID_TOMMY_GUN@This Thompson M1928 submachine gun is a sinister looking weapon; every time you hold it, you have an urge to put on a fedora hat and crack your knuckles. The Thompson is well-fed by a large 50 round drum magazine.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 3&PID_PUMP_PARTS 7@PID_WORKBENCH 1@PID_TOMMY_GUN 1@exp 79 script fix_boy@fix_Generic}
{73}{}{PID_ASSAULT_RIFLE@An AK-112 5mm Assault Rifle. An old military model, out of use around the time of the war. Can fire single-shot or burst, using the high velocity 5mm rounds.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS 4&PID_ALLOYS2 2&PID_METAL_PARTS 1&PID_METAL_PARTS2 1@PID_ADVANCED_BENCH 1@PID_ASSAULT_RIFLE 1@exp 373 script fix_boy@fix_Blueprint}
{74}{}{PID_ASSAULT_RIFLE_EXT_MAG@This Assault Rifle has an extended, military sized, ammunition clip. The expanded magazine capacity makes it more fun than ever to Spray-and-Pray.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_ASSAULT_RIFLE 1&PID_EXTENDED_MAGAZINE 1@PID_ADVANCED_BENCH 1@PID_ASSAULT_RIFLE_EXT_MAG 1@exp 0 script fix_boy@fix_Generic}
{75}{}{PID_FN_FAL@This rifle has been more widely used by armed forces than any other rifle in history. It's a reliable assault weapon for any terrain or tactical situation.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_ALLOYS 3&PID_ALLOYS2 2@PID_ADVANCED_BENCH 1@PID_FN_FAL 1@exp 306 script fix_boy@fix_Blueprint}
{76}{}{PID_FN_FAL_HPFA@The FN FAL HPFA variant. This model has been tinkered with to increase its firepower making the gun much more dangerous, to both the user and his target.@PE_PROFESSION_GUNSMITH_S 3@PE_PROFESSION_GUNSMITH_S 3@PID_FN_FAL 1&PID_FIREWOOD 1&PID_ALLOYS 3&PID_METAL_PARTS2 5&PID_ALLOYS2 3@PID_MULTI_TOOL 1&PID_ADVANCED_BENCH 1@PID_FN_FAL_HPFA 1@exp 1117 script fix_boy@fix_Generic}
{77}{}{PID_INDEPENDENT@This was an experimental weapon at the time of the war. Manufactured, primarily, from high-strength polymers, the weapon is almost indestructible. It's light, fast firing, accurate, and can be broken down without the use of any tools.@PE_PROFESSION_GUNSMITH_S 3@PE_PROFESSION_GUNSMITH_S 3@PID_FIREWOOD 1&PID_ALLOYS 3&PID_METAL_PARTS2 3&PID_ALLOYS2 5@PID_MULTI_TOOL 1&PID_ADVANCED_BENCH 1@PID_INDEPENDENT 1@exp 1219 script fix_boy@fix_Generic}
{78}{}{PID_SHOTGUN@A Winchester Widowmaker double-barreled 12-gauge shotgun. Short barrel, with mahogany grip.@@@PID_FIREWOOD 1&PID_METAL_PARTS 5@PID_WORKBENCH 1@PID_SHOTGUN 1@exp 105 script fix_boy@fix_Generic}
{79}{}{PID_SAWED_OFF_SHOTGUN@Someone took the time to chop the last few inches off the barrel and stock of this shotgun. Now, the wide spread of this hand-cannon's short-barreled shots makes it perfect for short-range crowd control.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_SHOTGUN 1&PID_METAL_PARTS 1&PID_PUMP_PARTS 2@PID_WORKBENCH 1@PID_SAWED_OFF_SHOTGUN 1@exp 24 script fix_boy@fix_Generic}
{80}{}{PID_COMBAT_SHOTGUN@A Winchester City-Killer 12-gauge combat shotgun, bullpup variant. In excellent condition, it has the optional DesertWarfare environmental sealant modification for extra reliability.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 6&PID_ALLOYS 1@PID_WORKBENCH 1@PID_COMBAT_SHOTGUN 1@exp 161 script fix_boy@fix_Generic}
{81}{}{PID_HK_CAWS@The CAWS, short for Close Assault Weapons System, shotgun is a useful tool for close-range combat. The bullpup layout gives the weapon a short, easily handleable, length while still retaining enough barrel length for its high velocity shells.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS2 2&PID_ALLOYS 2&PID_METAL_PARTS 3&PID_PUMP_PARTS 3@PID_ADVANCED_BENCH 1@PID_HK_CAWS 1@exp 296 script fix_boy@fix_Blueprint}
{82}{}{PID_PANCOR_JACKHAMMER@The Jackhammer, despite its name, is an easy to control shotgun, even when fired on full automatic. The popular bullpup design, which places the magazine behind the trigger, makes the weapon well balanced & easy to control.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_METAL_PARTS2 2&PID_ALLOYS 3&PID_ALLOYS2 1@PID_ADVANCED_BENCH 1@PID_PANCOR_JACKHAMMER 1@exp 332 script fix_boy@fix_Blueprint}
{83}{}{PID_FLAMER@A Flambe 450 model flamethrower, varmiter variation. Fires a short spray of extremely hot, flamable liquid. Requires specialized fuel to work properly.@@@PID_FIREWOOD 1&PID_ALLOYS 3@PID_WORKBENCH 1@PID_FLAMER 1@exp 113 script fix_boy@fix_Generic}
{84}{}{PID_HEATERCHAMBER@Enables the use of extremely heated fuel with the flamethrower.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_METAL_PARTS2 1&PID_ALLOYS2 1@PID_ADVANCED_BENCH 1@PID_HEATERCHAMBER 1@exp 128 script fix_boy@fix_Generic}
{85}{}{PID_IMPROVED_FLAMETHROWER@A Flambe 450 model flamethrower, varmiter variation. Fires a short spray of extremely hot, flamable liquid. Requires specialized fuel to work properly. This model has been modified to fire a hotter mixture which causes greater combustibility.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_FLAMER 1&PID_HEATERCHAMBER 1@PID_WORKBENCH 1@PID_IMPROVED_FLAMETHROWER 1@exp 0 script fix_boy@fix_Blueprint}
{86}{}{PID_ROCKET_LAUNCHER@A Rockwell BigBazooka rocket launcher. With the deluxe 3 lb. trigger. Fires AP or Explosive Rockets.@PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_B 1@PID_ALLOYS2 2&PID_ALLOYS 5&PID_METAL_PARTS 2&PID_METAL_PARTS2 1@PID_ADVANCED_BENCH 1@PID_ROCKET_LAUNCHER 1@exp 424 script fix_boy@fix_Blueprint}
{87}{}{PID_M60@This relatively light machine gun was prized by militaries around for world for its high rate of fire. This reliable, battlefield-proven design, was used on vehicles and for squad level fire-support.@PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_B 1@PID_METAL_PARTS 7&PID_ALLOYS 7@PID_WORKBENCH 1@PID_M60 1@exp 395 script fix_boy@fix_Generic}
{88}{}{PID_LIGHT_SUPPORT_WEAPON@This squad-level support weapon has a bullpup design. The bullpup design makes it difficult to use while lying down. Because of this it was remanded to National Guard units. It, however, earned a reputation as a reliable weapon that packs a lot of punch for its size.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_ALLOYS2 2&PID_METAL_PARTS 1&PID_METAL_PARTS2 1&PID_ALLOYS 5&PID_PUMP_PARTS 5@PID_ADVANCED_BENCH 1@PID_LIGHT_SUPPORT_WEAPON 1@exp 414 script fix_boy@fix_Blueprint}
{89}{}{PID_MINIGUN@A Rockwell CZ53 Personal Minigun. A multi-barrelled chaingun firing 5mm ammunition at over 60,000 RPM.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_FIREWOOD 1&PID_PUMP_PARTS 7&PID_ALLOYS 5&PID_ALLOYS2 2&PID_METAL_PARTS2 2&PID_METAL_PARTS 2@PID_MULTI_TOOL 1&PID_ADVANCED_BENCH 1@PID_MINIGUN 1@exp 494 script fix_boy@fix_Blueprint}
{90}{}{PID_AVENGER_MINIGUN@Rockwell designed the Avenger as the replacement for their aging CZ53 Personal Minigun. The Avenger's design improvements include improved, gel-fin, cooling and chromium plated barrel-bores. This gives it a greater range and lethality.@PE_PROFESSION_GUNSMITH_B 3@PE_PROFESSION_GUNSMITH_B 3@PID_MINIGUN 1&PID_METAL_PARTS2 3&PID_ALLOYS2 2@PID_MULTI_TOOL 1&PID_ADVANCED_BENCH 1@PID_AVENGER_MINIGUN 1@exp 600 script fix_boy@fix_Generic}
{91}{}{PID_LASER_PISTOL@A Wattz 1000 Laser Pistol. Civilian model, so the wattage is lower than military or police versions. Uses small energy cells.@@@PID_FIREWOOD 1&PID_ALLOYS 2&PID_ELECTRONIC_PARTS 2&PID_METAL_PARTS 4@PID_WORKBENCH 1@PID_LASER_PISTOL 1@exp 167 script fix_boy@fix_Generic}
{92}{}{PID_MFT_SYSTEM@Improved system of laser weapon targeting, using a magnetic field.@PE_PROFESSION_ENERGY_EXPERT 3@PE_PROFESSION_ENERGY_EXPERT 3@PID_METAL_PARTS 1&PID_ELECTRONIC_PARTS 1@PID_WORKBENCH 1@PID_MFT_SYSTEM 1@exp 40 script fix_boy@fix_Generic}
{93}{}{PID_MAGNETO_LASER_PISTOL@This Wattz 1000 laser pistol has been upgraded with a magnetic field targeting system that tightens the laser emission, giving this pistol extra penetrating power.@PE_PROFESSION_ENERGY_EXPERT 1@PE_PROFESSION_ENERGY_EXPERT 1@PID_METAL_PARTS 2&PID_FIREWOOD 1&PID_ALLOYS 4&PID_ELECTRONIC_PARTS 3@PID_WORKBENCH 1@PID_MAGNETO_LASER_PISTOL 1@exp 199 script fix_boy@fix_Generic}
{94}{}{PID_PLASMA_PISTOL@Glock 86 Plasma Pistol. Designed by the Gaston Glock AI. Shoots a small bolt of superheated plasma. Powered by a small energy cell.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ELECTRONIC_PARTS 1&PID_FIREWOOD 1&PID_ALLOYS 4&PID_ALLOYS2 1&PID_METAL_PARTS2 1@PID_ADVANCED_BENCH 1@PID_PLASMA_PISTOL 1@exp 311 script fix_boy@fix_Blueprint}
{95}{}{PID_EXT_CAPACITOR_BATTERY@Energy storage with additional capacity.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_METAL_PARTS2 1@PID_ADVANCED_BENCH 1@PID_EXT_CAPACITOR_BATTERY 1@exp 100 script fix_boy@fix_Generic}
{96}{}{PID_PLASMA_PISTOL_EXT_CAP@This Glock 86 Plasma Pistol has had its magnetic housing chamber realigned to reduce the drain on its energy cell. Its efficiency has doubled, allowing it to fire more shots before the battery is expended.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_PLASMA_PISTOL 1&PID_EXT_CAPACITOR_BATTERY 1@PID_ADVANCED_BENCH 1@PID_PLASMA_PISTOL_EXT_CART 1@exp 0 script fix_boy@fix_Generic}
{97}{}{PID_LASER_RIFLE@A Wattz 2000 Laser Rifle. Uses micro fusion cells for more powerful lasers, and an extended barrel for additional range.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_FIREWOOD 1&PID_ALLOYS2 2&PID_METAL_PARTS 2&PID_ALLOYS 4&PID_ELECTRONIC_PARTS 3@PID_ADVANCED_BENCH 1@PID_LASER_RIFLE 1@exp 387 script fix_boy@fix_Blueprint}
{98}{}{PID_LASER_RIFLE_EXT_CAP@This Wattz 2000 laser rifle has had its recharging system upgraded and a special recycling chip installed that reduces the drain on the micro fusion cell by 50%.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_LASER_RIFLE 1&PID_EXT_CAPACITOR_BATTERY 1@PID_ADVANCED_BENCH 1@PID_LASER_RIFLE_EXT_CAP 1@exp 0 script fix_boy@fix_Generic}
{99}{}{PID_PLASMA_RIFLE@A Winchester Model P94 Plasma Rifle. An industrial-grade energy weapon, firing superheated bolts of plasma down a superconducting barrel. Powered by Micro Fusion Cells.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_FIREWOOD 1&PID_METAL_PARTS2 2&PID_ALLOYS2 2&PID_ALLOYS 6&PID_ELECTRONIC_PARTS 5@PID_ADVANCED_BENCH 1@PID_PLASMA_RIFLE 1@exp 500 script fix_boy@fix_Blueprint}
{100}{}{PID_BRASS_KNUCKLES@Hardened knuckle grip that is actually made out of steel. They protect your hand, and do more damage, in unarmed combat.@@@PID_PUMP_PARTS 4@@PID_BRASS_KNUCKLES 1@exp 10 script fix_boy@fix_Generic}
{101}{}{PID_SPIKED_KNUCKLES@An improved version of the classic Brass Knuckles. The Spiked Knuckles do more damage, tearing into the flesh of your opponent in unarmed combat.@@@PID_METAL_PARTS 3@@PID_SPIKED_KNUCKLES 1@exp 60 script fix_boy@fix_Generic}
{102}{}{PID_POWER_FIST@A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. Others are just scared. Powered by small energy cells.@PE_PROFESSION_ENERGY_EXPERT 1@PE_PROFESSION_ENERGY_EXPERT 1@PID_ALLOYS 3&PID_ELECTRONIC_PARTS 4@PID_ADVANCED_BENCH 1@PID_POWER_FIST 1@exp 128 script fix_boy@fix_Generic}
{103}{}{PID_POWER_SERVOS@A system for modifying the power-fist.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ALLOYS2 1&PID_METAL_PARTS2 1@PID_ADVANCED_BENCH 1@PID_POWER_SERVOS 1@exp 300 script fix_boy@fix_Generic}
{104}{}{PID_MEGA_POWER_FIST@A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. This one has upgraded power servos for increased strength. Powered by small energy cells.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_POWER_FIST 1&PID_POWER_SERVOS 1@PID_ADVANCED_BENCH 1@PID_MEGA_POWER_FIST 1@exp 0 script fix_boy@fix_Blueprint}
{105}{}{PID_SHARPENED_POLE@A wood pole sharpened at one end.@@@PID_FIREWOOD 1@@PID_SHARPENED_POLE 1@exp 4 script fix_boy@fix_Generic}
{106}{}{PID_SPEAR@A sharp-bladed cutting and stabbing weapon.@@@PID_PUMP_PARTS 4&PID_SHARPENED_POLE 1&PID_METAL_PARTS 1@@PID_SPEAR 2@exp 14 script fix_boy@fix_Generic}
{107}{}{PID_SHARP_SPEAR@A razor tipped polearm. The shaft is wooden, and the tip is sharpened steel.@@@PID_SPEAR 1&PID_FLINT 1&PID_METAL_PARTS 3@@PID_SHARP_SPEAR 1@exp 31 script fix_boy@fix_Generic}
{108}{}{PID_KNIFE@A sharp-bladed cutting and stabbing weapon.@@@PID_PUMP_PARTS 2&PID_FIREWOOD 1&PID_METAL_PARTS 1@@PID_KNIFE 2@exp 14 script fix_boy@fix_Generic}
{109}{}{PID_COMBAT_KNIFE@A high-quality combat knife, the Stallona is from SharpWit, Inc. The edge of this blade is guaranteed sharp for over a decade of use!@@@PID_METAL_PARTS 3&PID_FLINT 1&PID_FIREWOOD 1&PID_PUMP_PARTS 4@PID_WORKBENCH 1@PID_COMBAT_KNIFE 1@exp 75 script fix_boy@fix_Generic}
{110}{}{PID_RIPPER@A Ripper(tm) vibroblade. Powered by a small energy cell, the chainblade rips and tears into it's target.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ALLOYS2 1&PID_ALLOYS 2&PID_ELECTRONIC_PARTS 1@PID_ADVANCED_BENCH 1@PID_RIPPER 1@exp 183 script fix_boy@fix_Blueprint}
{111}{}{PID_SLEDGEHAMMER@A large hammer with big handle. Very popular with the muscular crowd.@@@PID_FIREWOOD 1&PID_METAL_PARTS 1@@PID_SLEDGEHAMMER 1@exp 25 script fix_boy@fix_Generic}
{112}{}{PID_SUPER_SLEDGE@A Super Sledgehammer, manufactured by the Brotherhood of Steel, using the finest weapons technology available. Includes a kinetic energy storage device, to increase knockback.@@@PID_METAL_PARTS2 2&PID_ALLOYS 1&PID_ELECTRONIC_PARTS 1&PID_SLEDGEHAMMER 1@PID_WORKBENCH 1@PID_SUPER_SLEDGE 1@exp 143 script fix_boy@fix_Blueprint}
{113}{}{PID_CATTLE_PROD@A Farmer's Best Friend model cattle prod from Wattz Electronics. Uses small energy cells for power.@PE_PROFESSION_ENERGY_EXPERT 1@PE_PROFESSION_ENERGY_EXPERT 1@PID_FIREWOOD 1&PID_ELECTRONIC_PARTS 4&PID_ALLOYS 2@PID_WORKBENCH 1@PID_CATTLE_PROD 1@exp 92 script fix_boy@fix_Generic}
{114}{}{PID_IMP_CAPACITOR_BATTERY@Improved version of plasma storage, enables higher rate of fire.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ALLOYS2 1&PID_ELECTRONIC_PARTS 3&PID_METAL_PARTS2 1&PID_METAL_PARTS 2&PID_ALLOYS 1@PID_ADVANCED_BENCH 1@PID_IMP_CAPACITOR_BATTERY 1@exp 400 script fix_boy@fix_Generic}
{115}{}{PID_SUPER_CATTLE_PROD@A Farmer's Best Friend model cattle prod from Wattz Electronics. This model has been upgraded to increase the electrical discharge.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_CATTLE_PROD 1&PID_IMP_CAPACITOR_BATTERY 1@PID_WORKBENCH 1@PID_SUPER_CATTLE_PROD 1@exp 0 script fix_boy@fix_Blueprint}
{116}{}{PID_THROWING_KNIFE@A knife, balanced specifically for throwing. Made of titanium, and laser sharpened.@@@PID_METAL_PARTS 4&PID_FIREWOOD 2@@PID_THROWING_KNIFE 10@exp 90 script fix_boy@fix_Generic}
{117}{}{PID_MOLOTOV_COCKTAIL@A home-made flammable grenade.@@@PID_ROT_GUT 4@PID_WORKBENCH 1@PID_MOLOTOV_COCKTAIL 30@exp 60 script fix_boy@fix_Generic}
{118}{}{PID_FRAG_GRENADE@A generic fragmentation grenade. Contains a small amount of high explosives, the container itself forming most of the damaging fragments. Explodes on contact.@PE_PROFESSION_DEMOLITION_EXPERT 1@PE_PROFESSION_DEMOLITION_EXPERT 1@PID_METAL_PARTS 1&PID_GUNPOWDER 4@PID_WORKBENCH 1@PID_FRAG_GRENADE 10@exp 52 script fix_boy@fix_Generic}
{119}{}{PID_PLASMA_GRENADE@A magnetically sealed plasma delivery unit, with detonating explosives. Creates a blast of superheated plasma on contact.@PE_PROFESSION_DEMOLITION_EXPERT 2@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_METAL_PARTS 1&PID_REFINED_ORE 2@PID_ADVANCED_BENCH 1@PID_PLASMA_GRENADE 10@exp 111 script fix_boy@fix_Blueprint}
{120}{}{PID_DYNACORD@This lethal mixture of Dynamite and Cordex combines the best of both, leaving you no other choice than to worship it.@PE_PROFESSION_DEMOLITION_EXPERT 3@PE_PROFESSION_DEMOLITION_EXPERT 3@PID_GUNPOWDER2 6&PID_METAL_PARTS2 1@PID_ADVANCED_BENCH 1@PID_DYNACORD 10@exp 400 script fix_boy@fix_Blueprint}
{121}{}{PID_ANTIDOTE@A bottle containing a home-brewed antidote for poison. A milky liquid with floating pieces of radscorpion flesh.@PE_PROFESSION_DOCTOR 1@PE_PROFESSION_DOCTOR 1@PID_SCORPION_TAIL 5@@PID_ANTIDOTE 1@exp 15 script fix_boy@fix_Generic}
{122}{}{PID_WEAK_HEALING_POWDER@A weak low-tech healing agent. It's not quite a stimpak, but it'll do.@@@PID_BROC_FLOWER 1@@PID_WEAK_HEALING_POWDER 1@exp 3 script fix_boy@fix_Generic}
{123}{}{PID_HEALING_POWDER@A low-tech healing agent. It's not quite a stimpak, but it'll do.@PE_PROFESSION_DOCTOR 1@PE_PROFESSION_DOCTOR 1@PID_XANDER_ROOT 1&PID_BROC_FLOWER 1@@PID_HEALING_POWDER 1@exp 5 script fix_boy@fix_Generic}
{124}{}{PID_STIMPAK@A healing chem. When injected, the chem provides immediate healing of minor wounds.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_HYPODERMIC_NEEDLE 1&PID_BIO_GEL 1&PID_XANDER_ROOT 1&PID_BROC_FLOWER 1@PID_WORKBENCH 1@PID_STIMPAK 1@exp 15 script fix_boy@fix_Generic}
{125}{}{PID_STIMPAK@A healing chem. When injected, the chem provides immediate healing of minor wounds.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_HYPODERMIC_NEEDLE 5&PID_BIO_GEL 5&PID_XANDER_ROOT 5&PID_BROC_FLOWER 5@PID_WORKBENCH 1@PID_STIMPAK 5@exp 75 script fix_boy@fix_Generic}
{126}{}{PID_SUPER_STIMPAK@An advanced healing chem. Very powerful. Superstims will cause a small amount of damage after a period of time due to powerful nature of the chemicals used.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_STIMPAK 1&PID_BIO_GEL 2&PID_CHEMICALS 1@PID_MED_MACHINE 1@PID_SUPER_STIMPAK 1@exp 26 script fix_boy@fix_Generic}
{127}{}{PID_SUPER_STIMPAK@An advanced healing chem. Very powerful. Superstims will cause a small amount of damage after a period of time due to powerful nature of the chemicals used.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_STIMPAK 5&PID_BIO_GEL 10&PID_CHEMICALS 5@PID_MED_MACHINE 1@PID_SUPER_STIMPAK 5@exp 130 script fix_boy@fix_Generic}
{128}{}{PID_RADAWAY@A chemical solution that bonds with radiation particles and passes them through your system. Takes time to work.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_CHEMICALS 1&PID_BIO_GEL 1@PID_MED_MACHINE 1@PID_RADAWAY 1@exp 21 script fix_boy@fix_Blueprint}
{129}{}{PID_RADAWAY@A chemical solution that bonds with radiation particles and passes them through your system. Takes time to work.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_CHEMICALS 5&PID_BIO_GEL 5@PID_MED_MACHINE 1@PID_RADAWAY 5@exp 105 script fix_boy@fix_Blueprint}
{130}{}{PID_RAD_X@Anti-radiation chems to be taken before exposure. No known side effects.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_CHEMICALS 1&PID_BIO_GEL 3@PID_MED_MACHINE 1@PID_RAD_X 1@exp 33 script fix_boy@fix_Blueprint}
{131}{}{PID_RAD_X@Anti-radiation chems to be taken before exposure. No known side effects.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_CHEMICALS 5&PID_BIO_GEL 15@PID_MED_MACHINE 1@PID_RAD_X 5@exp 165 script fix_boy@fix_Blueprint}
{132}{}{PID_MENTATS@A pillbox of mind-altering chems. Increases memory related functions, and speeds other mental processes. Highly addictive.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_CHEMICALS 2&PID_CHEMICALS2 4&PID_BIO_GEL 2@PID_MED_MACHINE 1@PID_MENTATS 1@exp 80 script fix_boy@fix_Blueprint}
{133}{}{PID_BUFFOUT@Highly advanced steroids. While in effect, they increase strength and reflexes. Very addictive.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_CHEMICALS2 5@PID_MED_MACHINE 1@PID_BUFFOUT 1@exp 75 script fix_boy@fix_Blueprint}
{134}{}{PID_PSYCHO@An unique delivery system filled with strange and unknown chemicals of probably military origin. It is supposed to increase the combat potential of a soldier.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_CHEMICALS 4&PID_CHEMICALS2 5&PID_BIO_GEL 1@PID_MED_MACHINE 1@PID_PSYCHO 1@exp 100 script fix_boy@fix_Blueprint}
{135}{}{PID_JET@Jet is a powerful metamphetamine that stimulates the central nervous system. The initial euphoric rush rarely lasts more than a few minutes, but during that time, the user is filled with a rush of energy & strength.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_CHEMICALS 3&PID_CHEMICALS2 3@PID_ADVANCED_BENCH 1@PID_JET 1@exp 59 script fix_boy@fix_Blueprint}
{136}{}{PID_LOCK@A lock, quite standard for this environment.@@@PID_FLINT 1&PID_METAL_PARTS 5@PID_WORKBENCH 1@PID_LOCK 1@exp 200 script fix_boy@fix_Generic}
{137}{}{PID_LOCKPICKS@A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks.@@@PID_FLINT 1&PID_PUMP_PARTS 3&PID_METAL_PARTS 2@PID_WORKBENCH 1@PID_LOCKPICKS 1@exp 48 script fix_boy@fix_Generic}
{138}{}{PID_EXP_LOCKPICKS@A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks. This set also includes some special tools for more difficult mechanical locking mechanisms.@SK_LOCKPICK 60@SK_LOCKPICK 125@PID_FLINT 1&PID_BRAHMIN_HIDE 1&PID_METAL_PARTS 7@PID_WORKBENCH 1@PID_EXP_LOCKPICK_SET 1@exp 200 script fix_boy@fix_Generic}
{139}{}{PID_DYNAMITE@A high explosive, consisting of nitroglycerin mixed with the absorbent substance kiselguhr. Includes a timer.@PE_PROFESSION_DEMOLITION_EXPERT 2@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_GUNPOWDER2 6&PID_DETONATOR_PARTS 1@PID_ADVANCED_BENCH 1@PID_DYNAMITE 1@exp 153 script fix_boy@fix_Blueprint}
{140}{}{PID_PLASTIC_EXPLOSIVES@A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. Includes a timer.@PE_PROFESSION_DEMOLITION_EXPERT 2@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_GUNPOWDER2 12&PID_DETONATOR_PARTS 1@PID_ADVANCED_BENCH 1@PID_PLASTIC_EXPLOSIVES 1@exp 306 script fix_boy@fix_Blueprint}
{141}{}{PID_ROPE@A strong, thick line. About 45 feet in length.@@@PID_FIBER 1@PID_WORKBENCH_PRIMITIVE 1|PID_WORKBENCH 1@PID_ROPE 1@exp 10 script fix_boy@fix_Generic}
{142}{}{PID_WATERBAG_EMPTY@This bag can be filled up with water.@@@PID_BRAHMIN_HIDE 1&PID_FIBER 1@@PID_WATERBAG_EMPTY 1@exp 30 script fix_boy@fix_Generic}
{143}{}{PID_RADIO@This hand-held radio doesn't work but it looks as though it's still in pretty good condition.@@@PID_PUMP_PARTS 5&PID_METAL_PARTS 1@PID_WORKBENCH 1@PID_RADIO 1@exp 30 script fix_boy@fix_Generic}
{144}{}{PID_SHOVEL@This shovel is the property of it's owners. You can't even conceive of a use for it.@@@PID_METAL_PARTS 1&PID_FIREWOOD 1@PID_WORKBENCH 1@PID_SHOVEL 1@exp 14 script fix_boy@fix_Generic}
{145}{}{PID_PRIMITIVE_TOOL@This most rudimentary tool does not look very reliable. Still, it can be used to chop wood or to mine ore.@@@PID_FLINT 1@@PID_PRIMITIVE_TOOL 1@exp 4 script fix_boy@fix_Generic}
{146}{}{PID_AXE@Worn hatchet. Its blade is still in good condition.@@@PID_PUMP_PARTS 1&PID_FIREWOOD 1@PID_WORKBENCH 1@PID_AXE 1@exp 14 script fix_boy@fix_Generic}
{147}{}{PID_MULTI_TOOL@A tool set, containing various useful tools, including pliers.@@@PID_FLINT 1&PID_PUMP_PARTS 3&PID_METAL_PARTS 1@PID_WORKBENCH 1@PID_MULTI_TOOL 1@exp 60 script fix_boy@fix_Generic}
{148}{}{PID_MOVABLE_AMMO_BOX_L1@A wooden crate used to store ammo.@@@PID_FIREWOOD 20&PID_FIBER 5&PID_METAL_PARTS2 4@PID_WORKBENCH 1@PID_MOVABLE_AMMO_BOX_L1 1@exp 320 script fix_boy@fix_Generic}
{149}{}{PID_MOVABLE_AMMO_BOX_S1@A wooden crate used to store ammo.@@@PID_FIREWOOD 10&PID_FIBER 2&PID_METAL_PARTS2 2@PID_WORKBENCH 1@PID_MOVABLE_AMMO_BOX_S1 1@exp 160 script fix_boy@fix_Generic}
{150}{}{PID_MOVABLE_POOR_BOX@A small box used to collect money for the poor.@@@PID_FIREWOOD 5&PID_FIBER 3@PID_WORKBENCH_PRIMITIVE 1|PID_WORKBENCH 1@PID_MOVABLE_POOR_BOX 1@exp 50 script fix_boy@fix_Generic}
{151}{}{PID_MOVABLE_CHEST@A wooden chest.@@@PID_FIREWOOD 15&PID_FIBER 5@PID_WORKBENCH 1@PID_MOVABLE_CHEST 1@exp 120 script fix_boy@fix_Generic}
{152}{}{PID_MOVABLE_CRATE@A wooden crate.@@@PID_FIREWOOD 10&PID_FIBER 5@PID_WORKBENCH_PRIMITIVE 1|PID_WORKBENCH 1@PID_MOVABLE_CRATE 1@exp 100 script fix_boy@fix_Generic}
{153}{}{PID_MOVABLE_FOOTLOCKER1@Basic footlocker. Holds stuff, sits at foot of bed.@@@PID_METAL_PARTS2 2&PID_METAL_PARTS 8&PID_PUMP_PARTS 8@PID_WORKBENCH 1@PID_MOVABLE_FOOTLOCKER1 1@exp 300 script fix_boy@fix_Generic}
{154}{}{PID_MOVABLE_LOCKER1@A storage container.@@@PID_METAL_PARTS2 2&PID_METAL_PARTS 12&PID_PUMP_PARTS 12@PID_WORKBENCH 1@PID_MOVABLE_LOCKER1 1@exp 400 script fix_boy@fix_Generic}
{155}{}{PID_MOVABLE_SAFE@A heavy metal safe.@@@PID_METAL_PARTS2 15&PID_ALLOYS2 5&PID_METAL_PARTS 10&PID_PUMP_PARTS 5@PID_WORKBENCH 1@PID_MOVABLE_SAFE 1@exp 1250 script fix_boy@fix_Generic}
{156}{}{PID_TENT@A tightly packed tent made of brahmin leather.@@@PID_BRAHMIN_HIDE 8&PID_ROPE 1&PID_SHARPENED_POLE 4@@PID_TENT 1@exp 0 script fix_boy@fix_Generic}
