{10}{}{Hero Male}
{11}{}{ }
{20}{}{Hero Female}
{21}{}{ }
{30}{}{Villager}
{40}{}{Villager}
{50}{}{Radscorpion}
{51}{}{A small mutated scorpion.}
{60}{}{Radscorpion}
{61}{}{A mutated scorpion.}
{70}{}{Deathclaw}
{71}{}{An immature Deathclaw.}
{80}{}{Deathclaw}
{81}{}{An immature Deathclaw.}
{90}{}{Dog}
{91}{}{A canine, probably of a mixed breed.}
{100}{}{Brahmin}
{101}{}{A two headed, mutant cow.}
{110}{}{Rat}
{111}{}{A typical large rat.}
{120}{}{Mantis}
{121}{}{A mutated Mantis.}
{130}{}{Elder}
{140}{}{Hakunin}
{150}{}{Mynoc}
{160}{}{Spore Plant}
{161}{}{A carnivorous plant.}
{170}{}{Cute Slave}
{180}{}{Handsome Slave}
{190}{}{Healthy Slave}
{200}{}{Healthy Slave}
{210}{}{Strong Slave}
{220}{}{Strong Slave}
{230}{}{Combat Slave}
{240}{}{Combat Slave}
{250}{}{Clever Slave}
{260}{}{Clever Slave}
{270}{}{Generic Slave}
{280}{}{Generic Slave}
{290}{}{Anna}
{300}{}{Tough Thug}
{310}{}{Tough Thug}
{320}{}{Melee Thug}
{330}{}{Melee Thug}
{340}{}{Agile Thug}
{350}{}{Agile Thug}
{360}{}{Gun Thug}
{370}{}{Gun Thug}
{380}{}{Big Gun Thug}
{390}{}{Big Gun Thug}
{400}{}{Tough Guard}
{410}{}{Tough Guard}
{420}{}{Melee Guard}
{430}{}{Melee Guard}
{440}{}{Agile Guard}
{450}{}{Agile Guard}
{460}{}{Gun Guard}
{470}{}{Gun Guard}
{480}{}{Big Gun Guard}
{490}{}{Big Gun Guard}
{500}{}{Orphan (Male)}
{510}{}{Orphan (Female)}
{520}{}{Child (Male)}
{530}{}{Child (Female)}
{540}{}{Loser}
{550}{}{Loser}
{560}{}{Bad Merchant}
{570}{}{Bad Merchant}
{580}{}{Average Merchant}
{590}{}{Average Merchant}
{600}{}{Master Trader}
{610}{}{Master Trader}
{620}{}{Vic}
{630}{}{Weak Peasant}
{640}{}{Weak Peasant}
{650}{}{Average Peasant}
{660}{}{Average Peasant}
{670}{}{Strong Peasant}
{680}{}{Strong Peasant}
{690}{}{Weak Melee Guard}
{700}{}{Weak Melee Guard}
{710}{}{Weak Gun Guard}
{720}{}{Weak Gun Guard}
{730}{}{Repair Bot}
{740}{}{Repair Bot Mark II}
{750}{}{Robobrain}
{760}{}{Floating Eye Bot}
{770}{}{Sentry Bot}
{780}{}{Sentry Bot Mark II}
{790}{}{Robobrain}
{800}{}{Little Gecko}
{810}{}{Tough Lil Gecko}
{820}{}{Wild Dog}
{821}{}{A mixed breed feral dog.}
{830}{}{Golden Gecko}
{840}{}{Deathclaw}
{850}{}{Deathclaw Spawn}
{860}{}{Tough Golden Gecko}
{870}{}{Lynette}
{880}{}{Dr. Troy}
{890}{}{John Cassidy}
{900}{}{Gregory}
{910}{}{Citizen (Female)}
{920}{}{Citizen (Male)}
{930}{}{Up Class Citizen (F)}
{940}{}{Up Class Citizen (M)}
{950}{}{Trapper}
{960}{}{Trapper}
{970}{}{Sulik}
{980}{}{Maida Buckner}
{990}{}{Torr}
{1000}{}{Lumpy}
{1010}{}{Reactor Glowing One}
{1020}{}{Reactor Ghoul}
{1030}{}{Reactor Guard}
{1040}{}{Zomak}
{1050}{}{Skeeter}
{1060}{}{The Brain}
{1070}{}{Lenny}
{1080}{}{Wooz}
{1090}{}{Harold}
{1100}{}{Mole Rat}
{1110}{}{Greater Mole Rat}
{1120}{}{Pig Rat}
{1130}{}{Tough Pig Rat}
{1140}{}{Weak Brahmin}
{1141}{}{A two-headed, mutant cow.}
{1150}{}{A.Pwr.Armor (don't use)}
{1160}{}{Mutated Rat}
{1161}{}{A tough mutant rat.}
{1170}{}{Mutated Mole Rat}
{1171}{}{A tough mutant mole rat.}
{1180}{}{Mutated Pig Rat}
{1181}{}{A tough mutant pig rat.}
{1190}{}{Super Mutant}
{1200}{}{Powerful Mutant}
{1210}{}{Melchoir}
{1220}{}{Hero Andro (don't use)}
{1230}{}{Hero Andro (don't use)}
{1240}{}{Hero Male (don't use)}
{1250}{}{Hero Female (don't use)}
{1260}{}{Hero Male (don't use)}
{1270}{}{Hero Female (don't use)}
{1280}{}{Hero Male (don't use)}
{1290}{}{Hero Female (don't use)}
{1300}{}{Hero Male (don't use)}
{1310}{}{Hero Female (don't use)}
{1320}{}{Hero Male (don't use)}
{1330}{}{Hero Female (don't use)}
{1340}{}{Vault City Guard}
{1350}{}{Vault City Guard}
{1360}{}{Cyberdog}
{1370}{}{NCR Guard}
{1380}{}{NCR Guard}
{1390}{}{NCR Melee Guard}
{1400}{}{Slaver Guard}
{1410}{}{Slaver Overseer}
{1420}{}{Grand Master Trader}
{1430}{}{Grand Master Trader}
{1440}{}{Tandi}
{1450}{}{Merk}
{1460}{}{Ratch}
{1470}{}{Skeeter}
{1480}{}{Mikey}
{1490}{}{NCR Bartender}
{1500}{}{Shop Owner}
{1510}{}{Gruthar}
{1520}{}{Goris}
{1530}{}{Molerat Fighter}
{1540}{}{Molerat Fighter}
{1550}{}{Molerat Fighter}
{1560}{}{Molerat Fighter}
{1570}{}{Molerat Fighter}
{1580}{}{Molerat Fighter}
{1590}{}{Generic Ghoul}
{1600}{}{Myron}
{1610}{}{Marcus}
{1620}{}{Doc Jones}
{1630}{}{Davin}
{1640}{}{Miria}
{1650}{}{Laddie}
{1660}{}{Rondo}
{1670}{}{Ranch Hand}
{1680}{}{Ranch Hand}
{1690}{}{Ranch Hand}
{1700}{}{Bouncer}
{1710}{}{Bouncer}
{1720}{}{Weak Mr. Handy}
{1730}{}{Generic Glowing One}
{1740}{}{Dar}
{1750}{}{Dalia}
{1760}{}{Gordon}
{1770}{}{test (don't use)}
{1780}{}{Reactor Ghoul}
{1790}{}{Generic Ghoul}
{1800}{}{Matt}
{1810}{}{B. Hunter Lead (1-6)}
{1820}{}{Bounty Hunter (1-6)}
{1830}{}{B. Hunter Lead (7-12)}
{1840}{}{Bounty Hunter (7-12)}
{1850}{}{Bounty Hunter (7-12)}
{1860}{}{B. Hunter Lead (13-18)}
{1870}{}{Bounty Hunter (13-18)}
{1880}{}{Bounty Hunter (13-18)}
{1890}{}{B. Hunter Lead (19-?)}
{1900}{}{Bounty Hunter (19-?)}
{1910}{}{Bess}
{1911}{}{A two headed, mutant cow.}
{1920}{}{Balthas}
{1930}{}{Grisham}
{1940}{}{Phil}
{1950}{}{Chicken}
{1960}{}{Karl}
{1970}{}{Jonny}
{1980}{}{Jo}
{1990}{}{Zeke}
{2000}{}{Butcher}
{2010}{}{Petey}
{2020}{}{Primitive Hunter}
{2030}{}{Primitive Hunter}
{2040}{}{Cannibal}
{2050}{}{Cannibal}
{2060}{}{Holy Man}
{2070}{}{Holy Woman}
{2080}{}{Nomad- Low}
{2090}{}{Nomad- Med}
{2100}{}{Nomad- Low}
{2110}{}{Nomad- Med}
{2120}{}{Bandit}
{2130}{}{Bandit}
{2140}{}{Farmer}
{2150}{}{Farmer}
{2160}{}{Mantis}
{2170}{}{Slaver}
{2180}{}{Slaver}
{2190}{}{Wild Brahmin}
{2200}{}{Homesteader}
{2210}{}{Homesteader}
{2220}{}{Vault City Patrol}
{2230}{}{Vault City Patrol}
{2240}{}{Strong Slaver}
{2250}{}{Strong Slaver}
{2260}{}{Crazies}
{2270}{}{Scavengers}
{2280}{}{Glow Crazies}
{2290}{}{Glow Scavengers}
{2300}{}{Fisherman}
{2310}{}{Fisherwoman}
{2320}{}{Wilder}
{2330}{}{Wilder}
{2340}{}{Bootlegger}
{2350}{}{Bootlegger}
{2360}{}{Prospector}
{2370}{}{Prospector}
{2380}{}{Raider}
{2390}{}{Raider}
{2400}{}{Fire Gecko}
{2410}{}{Tough Fire Gecko}
{2420}{}{Alien}
{2430}{}{Tough Alien}
{2440}{}{Sm Tough Deathclaw}
{2450}{}{Tough Deathclaw}
{2460}{}{Floater}
{2470}{}{Nasty Floater}
{2480}{}{Centaur}
{2490}{}{Mean Centaur}
{2500}{}{Enclave Patrol}
{2510}{}{Enclave Patrol}
{2520}{}{Press Gang}
{2530}{}{Press Gang}
{2540}{}{Mercenary}
{2550}{}{Mercenary}
{2560}{}{Nightkin}
{2570}{}{Tough Nightkin}
{2580}{}{Tough Ghoul}
{2590}{}{Mobster}
{2600}{}{Yakuza}
{2610}{}{NCR Ranger}
{2620}{}{NCR Ranger}
{2630}{}{Marauder}
{2640}{}{Marauder}
{2650}{}{Pretty Boy Lloyd}
{2660}{}{Vorpal Rat}
{2670}{}{Vault 13 Man}
{2680}{}{Vault 13 Woman}
{2690}{}{Bridge Guardian}
{2700}{}{Mysterious Stranger}
{2710}{}{Mysterious Stranger}
{2720}{}{Hakeswill}
{2730}{}{Big Jesus Mordino}
{2740}{}{Dumar}
{2750}{}{Mother Deathclaw}
{2760}{}{The Dragon}
{2770}{}{Lo Pan}
{2780}{}{Hubologist}
{2790}{}{Hubologist}
{2800}{}{Mysterious Stranger}
{2810}{}{Mysterious Stranger}
{2820}{}{Mysterious Stranger}
{2830}{}{Mysterious Stranger}
{2840}{}{Mysterious Stranger}
{2850}{}{Mysterious Stranger}
{2860}{}{Mysterious Stranger}
{2870}{}{Mysterious Stranger}
{2880}{}{Pres. Bodyguard}
{2890}{}{Deathclaw Egg}
{2900}{}{Metzger}
{2910}{}{Enclave Guard}
{2920}{}{Enclave Guard}
{2930}{}{President}
{2940}{}{Vice President}
{2950}{}{Technicion}
{2960}{}{Badger}
{2970}{}{Dr. Fung}
{2980}{}{Kid}
{2990}{}{Kid}
{3000}{}{Gun Merchant}
{3010}{}{Shi Lab Tech}
{3020}{}{Shi Guard}
{3030}{}{Shi Peasant}
{3040}{}{Shi Peasant}
{3050}{}{Lo Pan Peasant}
{3060}{}{Lo Pan Peasant}
{3070}{}{Dock Worker}
{3080}{}{Shi Merchant}
{3090}{}{Keeng Ra'at}
{3100}{}{Sulik - Stage 1}
{3110}{}{Sulik - Stage 2}
{3120}{}{Sulik - Stage 3}
{3130}{}{Sulik - Stage 4}
{3140}{}{Sulik - Stage 5}
{3150}{}{Sulik - Stage 6}
{3160}{}{Lenny - Stage 1}
{3170}{}{Lenny - Stage 2}
{3180}{}{Lenny - Stage 3}
{3190}{}{Goris - Stage 1}
{3200}{}{Goris - Stage 2}
{3210}{}{Goris - Stage 3}
{3220}{}{Goris - Stage 4}
{3230}{}{Goris - Stage 5}
{3240}{}{Goris - Stage 6}
{3250}{}{Myron - Stage 1}
{3260}{}{Myron - Stage 2}
{3270}{}{Myron - Stage 3}
{3280}{}{Myron - Stage 4}
{3290}{}{Marcus - Stage 1}
{3300}{}{Marcus - Stage 2}
{3310}{}{Marcus - Stage 3}
{3320}{}{Marcus - Stage 4}
{3330}{}{Marcus - Stage 5}
{3340}{}{Cyberdog - Stage 1}
{3350}{}{Cyberdog - Stage 2}
{3360}{}{Cyberdog - Stage 3}
{3370}{}{Cyberdog - Stage 4}
{3380}{}{Cassidy - Stage 1}
{3390}{}{Cassidy - Stage 2}
{3400}{}{Cassidy - Stage 3}
{3410}{}{Cassidy - Stage 4}
{3420}{}{Dogmeat}
{3430}{}{Dogmeat - Stage 1}
{3440}{}{Dogmeat - Stage 2}
{3450}{}{Dogmeat - Stage 3}
{3460}{}{Dogmeat - Stage 4}
{3470}{}{Dogmeat - Stage 5}
{3480}{}{Dogmeat - Stage 6}
{3490}{}{Robobrain - Stage 1}
{3500}{}{Robobrain - Stage 2}
{3510}{}{Robobrain - Stage 3}
{3520}{}{Robobrain - Stage 4}
{3530}{}{Robobrain - Stage 5}
{3540}{}{Queen Alien}
{3550}{}{Black Radscorpion}
{3560}{}{Black Radscorpion}
{3570}{}{Spud}
{3580}{}{Mercenary Captain}
{3590}{}{Mercenary}
{3600}{}{Mercenary}
{3610}{}{Shadow-Who-Walks}
{3620}{}{Punk}
{3630}{}{Punk}
{3640}{}{Marc}
{3650}{}{Dave H.}
{3660}{}{Capt. A. Ron Meyers}
{3670}{}{Chip}
{3680}{}{AHS-9}
{3690}{}{Hubologist Guard}
{3700}{}{Hubologist Guard}
{3710}{}{Juan}
{3720}{}{Vikki}
{3730}{}{Vic - Stage 1}
{3740}{}{Vic - Stage 2}
{3750}{}{Vic - Stage 3}
{3760}{}{Vic - Stage 4}
{3770}{}{Vic - Stage 5}
{3780}{}{Vic - Stage 6}
{3790}{}{RoboBrain - Chimp}
{3800}{}{Robobrain - Abnormal}
{3810}{}{Robobrain - Human}
{3820}{}{Giant Ant}
{3830}{}{Tough Giant Ant}
{3840}{}{Pariah Dog}
{3850}{}{Zurak}
{3860}{}{Imbot}
{3870}{}{Jimmy}
{3880}{}{Wejungh}
{3890}{}{Herb}
{3900}{}{Loopal}
{3910}{}{Jobe}
{3920}{}{Smitty}
{3930}{}{Rube}
{3940}{}{Master Krall}
{3950}{}{Ziggy}
{3960}{}{Master Khung}
{3970}{}{John Bishop}
{3980}{}{Angela Bishop}
{3990}{}{Mrs. Bishop}
{4000}{}{Bishop's Guard 1}
{4010}{}{Bishop's Guard 2}
{4020}{}{Bishop's Thug 1}
{4030}{}{Bishop's Thug 2}
{4040}{}{Angry Brahmin}
{4050}{}{Lil' Jesus}
{4060}{}{Big Jesus}
{4070}{}{Mordino Men 1}
{4080}{}{Mordino Men 2}
{4090}{}{Mordino Men 3}
{4100}{}{Myron's Guard 1}
{4110}{}{Myron's Guard 2}
{4120}{}{Mr. Wright}
{4130}{}{Mrs. Wright}
{4140}{}{Chris Wright}
{4150}{}{Keith Wright}
{4160}{}{Wright Son 1}
{4170}{}{Wright Son 2}
{4180}{}{Wright Daughter 1}
{4190}{}{Wright Daughter 2}
{4200}{}{Mr. Salvatore}
{4210}{}{Mason}
{4220}{}{Salvatore Thug 1}
{4230}{}{Salvatore Thug 2}
{4240}{}{Generic Bartender 1}
{4250}{}{Generic Bartender 2}
{4260}{}{Generic Bartender 3}
{4270}{}{Boxer 1}
{4280}{}{Boxer 2}
{4290}{}{Boxer 3}
{4300}{}{Boxer 4}
{4310}{}{Mike the Masticator}
{4320}{}{Holyfeld}
{4330}{}{McKneely}
{4340}{}{Stuart Little}
{4350}{}{Corsican Brothers}
{4360}{}{Corsican Bitches}
{4370}{}{Father Tully}
{4380}{}{Casino Bouncer 1}
{4390}{}{Casino Bouncer 2}
{4400}{}{Casino Girl}
{4410}{}{Drug Dealer/Pimp1}
{4420}{}{Drug Dealer/Pimp2}
{4430}{}{Drug Dealer/Pimp3}
{4440}{}{Drug Dealer/Pimp4}
{4450}{}{McGee}
{4460}{}{Miss Kitty}
{4470}{}{Generic Slut 1}
{4480}{}{Generic Slut 2}
{4490}{}{Jagged Jimmy J}
{4500}{}{Renesco}
{4510}{}{Scientist}
{4520}{}{Eldridge}
{4530}{}{Algernon}
{4540}{}{Jules}
{4550}{}{Bureaucrat 1}
{4560}{}{Bureaucrat 2}
{4570}{}{Trader 1}
{4580}{}{Trader 2}
{4590}{}{Guard 1}
{4600}{}{Guard 2}
{4610}{}{Guard 3}
{4620}{}{Guard 4}
{4630}{}{Soldier 1}
{4640}{}{Soldier 2}
{4650}{}{Soldier 3}
{4660}{}{Soldier 4}
{4670}{}{Sgt. Stark}
{4680}{}{"Doc" Andrew}
{4690}{}{Bartender}
{4700}{}{Gun Turret}
{4701}{}{This is an automated gun turret equipped with a Dual Plasma Cannon.}
{4710}{}{Generic Cyberdog}
{4720}{}{K-9 (stage 1)}
{4730}{}{K-9 (stage 2)}
{4740}{}{Gun Turret}
{4750}{}{NCR Ranger}
{4760}{}{NCR Ranger}
{4770}{}{Wanamingo Egg}
{4780}{}{Lo Pan Guard}
{4790}{}{Marjorie}
{4800}{}{Auto-Cannon}
{4810}{}{Special Gecko Critter}
{4820}{}{Grim Reaper}
{4830}{}{Frank Horrigan}
{4831}{}{The President's Body Guard}
{4840}{}{Merc Melee}
{4850}{}{Merc Melee}
{4860}{}{Merc Melee}
{4870}{}{Merc Melee}
{4880}{}{Merc Misc}
{4890}{}{Merc SG}
{4900}{}{Merc Misc}
{4910}{}{Merc SG}
{4920}{}{Merc Melee}
{4930}{}{Merc Melee}
{4940}{}{Merc Melee}
{4950}{}{Merc Melee}
{4960}{}{Merc BG}
{4970}{}{Merc BG}
{4980}{}{Merc BG}
{4990}{}{Merc Energy}
{5000}{}{Merc Energy}
{5010}{}{Merc Mutant}
{5020}{}{Merc Mutant}
{5030}{}{Merc Mutant}
{5040}{}{Merc Ghoul Melee}
{5050}{}{Merc Ghoul SG}
{5060}{}{Desert Stalker}
{5070}{}{Endless Walker}
{5080}{}{Bat}
{5090}{}{Beetle}
{5100}{}{Centipede}
{5110}{}{Cougar}
{5120}{}{Cow}
{5130}{}{Venus Mantrap}
{5140}{}{Radtoad}
{5150}{}{Thornslinger}
{5160}{}{Giant Wasp}
{5170}{}{Young Alien}
{5171}{}{This alien still looks very young.}
{5180}{}{NCR Soldier}
{5190}{}{NCR Soldier}
{5200}{}{Gigantic Venus Mantrap}
{5210}{}{Robed Woman}
{5220}{}{Dog Scout}
{5230}{}{Brahmin}
{5231}{}{Brahmin from a Brahmin Run}
{5240}{}{Mother Squeak-Squeak}
{5241}{}{The mighty Mother Squeak-Squeak, don't run, You'll only die tired.}