
#
# Local map
#

# Name, (pid + 1) * 10 + 0
# Music, (pid + 1) * 10 + 5
# Ambient, (pid + 1) * 10 + 6
# NoLogOut, (pid + 1) * 10 + 7

# Map 0, Global, base 10
{10}{}{Global map}
{15}{}{20car}
{15}{}{03wrldmp}
{15}{}{23world}	#wm1.ogg			
{15}{}{23world} #wm2.ogg
{16}{}{blank:100}

# Map 1, base 20
{20}{}{Arroyo Temple}
{25}{}{17arroyo}
{26}{}{gntlwin1:25, gntlwind:25, animal1:20, animal:20, gustwind:5, gustwin1:5}

# Map 2, base 30
{30}{}{Tesla Tower}
{35}{}{08vats}
{36}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 3, base 40
{40}{}{Arena}
{45}{}{01hub}
{46}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 4, base 50
{50}{}{Rail Raiders}
{55}{}{05raider}
{56}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 5, base 60
{60}{}{Buried Rails}
{65}{}{07desert}
{66}{}{gntlwin1:20, gntlwind:20, dogbark:20, dogbark:20, gustwin1:10, gustwind:10}

# Map 6, base 70
{70}{}{Den Business}
{75}{}{05RAIDER}
{76}{}{dogbark:10, dogbark1:10, gntlwind:20, gntlwin1:20, blank:40}

# Map 7, base 80
{80}{}{Desert Encounter Khans 1}
{85}{}{07desert}
{85}{}{05raider}
{85}{}{12junktn}
{86}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 8, base 90
{90}{}{Klamath Canyon}
{95}{}{03wrldmp}
{96}{}{gntlwin1:30, gntlwind:30, gustwin1:10, gustwind:10, vulture:10, vulture1:10}

# Map 9, base 100
{100}{}{Klamath Downtown}
{105}{}{03wrldmp}
{106}{}{laughter:10, laughte1:10, gntlwind:30, gntlwin1:20, brdchir1:10, brdchirp:20}

# Map 10, base 110
{110}{}{Mountains Encounter Khans 2}
{115}{}{07desert}
{115}{}{05raider}
{115}{}{12junktn}
{116}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 11, base 120
{120}{}{Klamath Toxic Caves 1}
{125}{}{13carvrn}
{126}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}

# Map 12, base 130
{130}{}{Klamath Toxic Caves 2}
{135}{}{13carvrn}
{136}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}

# Map 13, base 140
{140}{}{Klamath Toxic Caves 3}
{145}{}{13carvrn}
{146}{}{puddle1:30, puddle:30, water:5, water1:5, pebble:5, pebble1:5}

# Map 14, base 150
{150}{}{Mountains Encounter Khans 3}
{155}{}{07desert}
{155}{}{05raider}
{155}{}{12junktn}
{156}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 15, base 160
{160}{}{Vault City HQ}
{165}{}{22vcity}
{166}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 16, base 170
{170}{}{Vault City Downtown}
{175}{}{22vcity}
{176}{}{blank:40, brdchirp:25, brdchir1:25, potspans:5, potspan1:5}

# Map 17, base 180
{180}{}{Desert Encounter Khans 4}
{185}{}{07desert}
{185}{}{05raider}
{185}{}{12junktn}
{186}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 18, base 190
{190}{}{Modoc Large}
{195}{}{18modoc}
{196}{}{brdchir1:25, brdchirp:25, chimes:15, chimes1:15, dogbark:10, dogbark1:10}

# Map 19, base 200
{200}{}{NCR LA Gold Reserve}
{205}{}{10labone}
{206}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 20, base 210
{210}{}{Vault City Vault Level 1}
{215}{}{22vcity}
{216}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 21, base 220
{220}{}{Vault City Vault Level 2}
{225}{}{22vcity}
{226}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 22, base 230
{230}{}{Vault City Vault Level 3}
{235}{}{22vcity}
{236}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 23, base 240
{240}{}{LA Warehouse}
{245}{}{08vats}
{246}{}{gntlwin1:25, gntlwind:25, animal1:20, animal:20, gustwind:5, gustwin1:5}

# Map 24, base 250
{250}{}{Q Cathedral Basement 1}
{255}{}{08vats}
{256}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 25, base 260
{260}{}{Sierra Army Depot: The Battlefield}
{265}{}{08vats}
{266}{}{gntlwind:30, gntlwin1:30, gustwind:10, gustwin1:10, vulture:10, vulture1:10}

# Map 26, base 270
{270}{}{Sierra Army Depot: Powersub}
{275}{}{08vats}
{276}{}{gntlwind:30, gntlwin1:30, gustwind:10, gustwin1:10, vulture:10, vulture1:10}

# Map 27, base 280
{280}{}{Sierra Army Depot: Level 1}
{285}{}{08vats}
{286}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 28, base 290
{290}{}{Sierra Army Depot: Level 2}
{295}{}{08vats}
{296}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 29, base 300
{300}{}{Sierra Army Depot: Level 3}
{305}{}{08vats}
{306}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 30, base 310
{310}{}{Sierra Army Depot: Level 4}
{315}{}{08vats}
{316}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 31, base 320
{320}{}{Gecko Settlement}
{325}{}{12junktn}
{326}{}{electri1:20, electric:20, gntlwind:20, gntlwin1:20, steam:20, steam1:20}

# Map 32, base 330
{330}{}{Gecko Power Plant}
{335}{}{12junktn}
{336}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 33, base 340
{340}{}{Q Cathedral Basement 2}
{345}{}{08vats}
{346}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 34, base 350
{350}{}{Vault 15 Surface}
{355}{}{15shady}
{356}{}{gntlwin1:20, gntlwind:20, dogbark:20, dogbark:20, gustwin1:10, gustwind:10}

# Map 35, base 360
{360}{}{Vault 15 Level 1}
{365}{}{15shady}
{366}{}{animal:20, pebble:15, pebble1:15, water1:20, water:20, blank:15}

# Map 36, base 370
{370}{}{Vault 15 Level 2}
{375}{}{15shady}
{376}{}{animal:20, pebble:15, pebble1:15, water1:20, water:20, blank:15}

# Map 37, base 380
{380}{}{Vault 15 Level 3}
{385}{}{15shady}
{386}{}{animal:20, pebble:15, pebble1:15, water1:20, water:20, blank:15}

# Map 38, base 390
{390}{}{Q Cathedral Basement 3}
{395}{}{13carvrn}
{396}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 39, base 400
{400}{}{Eventmap 1}
{405}{}{08vats}
{406}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 40, base 410
{410}{}{Gun Runners}
{415}{}{10labone}
{416}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 41, base 420
{420}{}{Q Gun Runners Caravan 1}
{425}{}{12junktn}
{426}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 42, base 430
{430}{}{NCR Residental Area}
{435}{}{01hub}
{436}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 43, base 440
{440}{}{Q Gun Runners Caravan 2}
{445}{}{13carvrn}
{446}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, animal1:15, animal:10}

# Map 44, base 450
{450}{}{Q: SanFran Subway}
{455}{}{14necro}
{456}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 45, base 460
{460}{}{NCR}
{465}{}{01hub}
{466}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 46, base 470
{470}{}{Hub Trainyard}
{475}{}{01hub}
{476}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 47, base 480
{480}{}{Den BoS}
{486}{}{blank:10}

# Map 48, base 490
{490}{}{NCR BoS}
{496}{}{blank:10}

# Map 49, base 500
{500}{}{Military Base Entrance}
{505}{}{07desert}
{506}{}{gntlwin1:20, gntlwind:20, dogbark:20, dogbark:20, gustwin1:10, gustwind:10}

# Map 50, base 510
{510}{}{Military Base Level 1}
{515}{}{08vats}
{516}{}{elevato1:25, elevator:25, electri1:15, electric:15, clank:10, clank1:10}

# Map 51, base 520
{520}{}{Military Base Level 2}
{525}{}{08vats}
{526}{}{elevato1:25, elevator:25, electri1:15, electric:15, clank:10, clank1:10}

# Map 52, base 530
{530}{}{Military Base Level 3}
{535}{}{08vats}
{536}{}{elevato1:25, elevator:25, electri1:15, electric:15, clank:10, clank1:10}

# Map 53, base 540
{540}{}{Military Base Level 4}
{545}{}{08vats}
{546}{}{elevato1:25, elevator:25, electri1:15, electric:15, clank:10, clank1:10}

# Map 54, base 550
{550}{}{New Reno 1}
{555}{}{19reno}
{556}{}{drunkla1:20, drunklaf:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 55, base 560
{560}{}{New Reno 2}
{565}{}{19reno}
{566}{}{drunkla1:20, drunklaf:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 56, base 570
{570}{}{New Reno 3}
{575}{}{19reno}
{576}{}{drunkla1:20, drunklaf:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 57, base 580
{580}{}{New Reno 4}
{585}{}{19reno}
{586}{}{drunkla1:20, drunklaf:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 58, base 590
{590}{}{New Reno Chop Shop}
{595}{}{19reno}
{596}{}{clank:20, clank1:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 59, base 600
{600}{}{Eventmap 2}
{606}{}{}

# Map 60, base 610
{610}{}{Q Brahmin Willow}
{615}{}{18modoc}
{616}{}{brdchir1:25, brdchirp:25, chimes:15, chimes1:15, dogbark:10, dogbark1:10}

# Map 61, base 620
{620}{}{Tobacco Farm}
{625}{}{14necro}
{626}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 62, base 630
{630}{}{Redding}
{635}{}{24redd}
{636}{}{saloon:25, saloon1:25, gustwind:10, laughter:20, footste1:10, footstep:10}

# Map 63, base 640
{640}{}{Redding Mine}
{645}{}{24redd}
{646}{}{animal1:20, animal:20, elevator:15, ore:15, mechpump:20, ore1:10}

# Map 64, base 650
{650}{}{Wanamingo Mine Entrance}
{655}{}{24redd}
{656}{}{animal1:20, animal:20, elevator:15, ore:15, mechpump:20, ore1:10}

# Map 65, base 660
{660}{}{NCRCF}
{665}{}{10labone}
{666}{}{gntlwin1:20, gntlwind:20, dogbark:20, dogbark:20, gustwin1:10, gustwind:10}

# Map 66, base 670
{670}{}{Rails}
{675}{}{07desert}
{676}{}{gntlwin1:20, gntlwind:20, dogbark:20, dogbark:20, gustwin1:10, gustwind:10}

# Map 67, base 680
{680}{}{Q Radscorpion Cave}
{685}{}{12junktn}
{686}{}{animal1:20, animal:20, gustwind:5, gustwin1:5}

# Map 68, base 690
{690}{}{Q Radscorpion Cave Interior}
{695}{}{13carvrn}
{696}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, animal1:15, animal:10}

# Map 69, base 700
{700}{}{Safe house in the city}
{705}{}{07desert}
{705}{}{10labone}
{706}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 70, base 710
{710}{}{Junktown}
{715}{}{12junktn}
{716}{}{gntlwin1:25, gntlwind:25, animal1:20, animal:20, gustwind:5, gustwin1:5}

# Map 71, base 720
{720}{}{Junktown Sub}
{725}{}{12junktn}
{726}{}{blank:10}

# Map 72, base 730
{730}{}{Safe house on the coast}
{735}{}{07desert}
{736}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 73, base 740
{740}{}{Safe house in the desert}
{745}{}{07desert}
{746}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 74, base 750
{750}{}{Safe house in the mountains}
{755}{}{07desert}
{756}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 75, base 760
{760}{}{Cathedral: Enter}
{765}{}{11chilrn}
{766}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 76, base 770
{770}{}{Cathedral: Main}
{775}{}{11chilrn}
{776}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 77, base 780
{780}{}{Cathedral: Level 1}
{785}{}{11chilrn}
{786}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 78, base 790
{790}{}{Cathedral: Level 2}
{795}{}{11chilrn}
{796}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 79, base 800
{800}{}{Cathedral: Level 3}
{805}{}{11chilrn}
{806}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 80, base 810
{810}{}{Cathedral: Cellar Level 1}
{815}{}{16follow}
{816}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 81, base 820
{820}{}{Cathedral: Cellar Level 2}
{825}{}{16follow}
{826}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 82, base 830
{830}{}{Cathedral: Cellar Level 3}
{835}{}{16follow}
{836}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 83, base 840
{840}{}{Cathedral: Cellar Level 4}
{845}{}{16follow}
{846}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 84, base 850
{850}{}{Crater}
{855}{}{16follow}
{856}{}{gntlwind:20, gntlwin1:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 85, base 860
{860}{}{Lost Hills: Entrance}
{865}{}{04brthrh}
{866}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 86, base 870
{870}{}{Lost Hills: Level 1}
{875}{}{04brthrh}
{876}{}{blank:10}

# Map 87, base 880
{880}{}{Lost Hills: Level 2}
{885}{}{04brthrh}
{886}{}{blank:10}

# Map 88, base 890
{890}{}{Lost Hills: Level 3}
{895}{}{04brthrh}
{896}{}{blank:10}

# Map 89, base 900
{900}{}{Lost Hills: Level 4}
{905}{}{04brthrh}
{906}{}{blank:10}

# Map 90, base 910
{910}{}{Vault 13 Level 1}
{915}{}{06Vault}
{916}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 91, base 920
{920}{}{Vault 13 Level 2}
{925}{}{06Vault}
{926}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 92, base 930
{930}{}{Vault 13 Level 3}
{935}{}{06Vault}
{936}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 93, base 940
{940}{}{Vault 13 Level 4}
{945}{}{06Vault}
{946}{}{electri1:15, electric:15, elevator:20, elevato1:15, steam:20, steam:15}

# Map 94, base 950
{950}{}{HQ: Cave Inside}
{955}{}{13carvrn}
{956}{}{animal:20, pebble:15, pebble1:15, water1:20, water:20, blank:15}

# Map 95, base 960
{960}{}{HQ: Cave Outside}
{965}{}{12junktn}
{965}{}{07desert}
{965}{}{05raider}
{966}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 96, base 970
{970}{}{HQ: Building Site}
{975}{}{12junktn}
{976}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 97, base 980
{980}{}{Blockers Map}
{986}{}{}

# Map 98, base 990
{990}{}{Brahmin Ranch}
{995}{}{18modoc}
{996}{}{}

# Map 99, base 1000
{1000}{}{New Reno Sewers}
{1005}{}{08vats}
{1005}{}{13carvrn}
{1005}{}{14necro}
{1006}{}{animal:20, pebble:15, pebble1:15, water1:20, water:20, blank:15}

# Map 100, base 1010
{1010}{}{Ares Military Base: Entrance}
{1015}{}{07desert}
{1015}{}{05raider}
{1015}{}{14necro}
{1016}{}{gntlwin1:20, gntlwind:20,gustwin1:10, gustwind:10}

# Map 101, base 1020
{1020}{}{Ares Military Base: Level 1}
{1025}{}{14necro}
{1025}{}{08vats}
{1026}{}{elevato1:25, elevator:25, electri1:15, electric:15, clank:10, clank1:10}

# Map 102, base 1030
{1030}{}{Ares Military Base: Level 2}
{1035}{}{14necro}
{1035}{}{08vats}
{1036}{}{elevato1:25, elevator:25, electri1:15, electric:15, clank:10, clank1:10}

# Map 103, base 1040
{1040}{}{Ruined Military Bunker Surface}
{1045}{}{08vats}
{1045}{}{14necro}
{1046}{}{gntlwin1:20, gntlwind:20, dogbark:20, dogbark:20, gustwin1:10, gustwind:10}

# Map 104, base 1050
{1050}{}{Ruined Military Bunker Level 1}
{1056}{}{elevato1:25, elevator:25, electri1:15, electric:15, clank:10, clank1:10}

# Map 105, base 1060
{1060}{}{Ruined Military Bunker Level 2}
{1066}{}{elevato1:25, elevator:25, electri1:15, electric:15, clank:10, clank1:10}

# Map 106, base 1070
{1070}{}{Q Ruined Military Bunker}
{1075}{}{07desert}
{1076}{}{brdchir1:25, brdchirp:25, chimes:15, chimes1:15, dogbark:10, dogbark1:10}

# Map 107, base 1080
{1080}{}{Ocean}
{1085}{}{14necro}
{1086}{}{seawind1:25, seawind:25, blank:20}

# Map 108, base 1090
{1090}{}{Old Warehouse}
{1095}{}{16follow}
{1096}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 109, base 1100
{1100}{}{Navarro}
{1105}{}{14necro}
{1106}{}{gntlwin1:25, gntlwind:25, gustwind:10, blank:40}

# Map 110, base 1110
{1110}{}{Old Warehouse Basemenet}
{1115}{}{16follow}
{1116}{}{}

# Map 111, base 1120
{1120}{}{Navarro Sublevel}
{1125}{}{14necro}
{1126}{}{gntlwin1:25, gntlwind:25, gustwind:10, blank:40}

# Map 112, base 1130
{1130}{}{Khans Cave Entrance}
{1135}{}{14necro}
{1136}{}{gntlwin1:25, gntlwind:25, gustwind:10, blank:40}

# Map 113, base 1140
{1140}{}{Khans Cave}
{1145}{}{14necro}
{1146}{}{gntlwin1:25, gntlwind:25, gustwind:10, blank:40}

# Map 114, base 1150
{1150}{}{Khans HQ}
{1155}{}{14necro}
{1156}{}{gntlwin1:25, gntlwind:25, gustwind:10, blank:40}

# Map 115, base 1160
{1160}{}{Broken Hills}
{1165}{}{08vats}
{1166}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 116, base 1170
{1170}{}{Broken Hills Basement}
{1175}{}{08vats}
{1176}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 117, base 1180
{1180}{}{Broken Hills Mine}
{1185}{}{08vats}
{1186}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 118, base 1190
{1190}{}{Broken Hills Dungeon}
{1195}{}{08vats}
{1196}{}{brdchir1:20, brdchirp:20, gntlwind:20, gntlwin1:20, gustwind:10, blank:10}

# Map 119, base 1200
{1200}{}{Old Warehouse Cave}
{1205}{}{16follow}
{1206}{}{}

# Map 120, base 1210
{1210}{}{Hospital}
{1216}{}{}

# Map 121, base 1220
{1220}{}{Old Factory}
{1226}{}{}

# Map 122, base 1230
{1230}{}{Q First Tent 1}
{1235}{}{07desert}
{1236}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 123, base 1240
{1240}{}{Q First Tent 2}
{1245}{}{07desert}
{1246}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 124, base 1250
{1250}{}{Q First Tent 3}
{1255}{}{18modoc}
{1256}{}{brdchir1:25, brdchirp:25, chimes:15, chimes1:15, dogbark:10, dogbark1:10}

# Map 125, base 1260
{1260}{}{Bus Stop}
{1265}{}{03wrldmp}
{1266}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 126, base 1270
{1270}{}{Ghost Town Streets}
{1275}{}{21sf}
{1276}{}{seawind1:25, seawind:25, chimes1:15, chimes:15, blank:20}

# Map 127, base 1280
{1280}{}{Seven Families Village}
{1285}{}{07desert}
{1286}{}{gntlwin1:25, gntlwind:25, gustwind:10, blank:40}

# Map 135, base 1360
{1360}{}{San Fran Tanker}
{1365}{}{21sf}
{1366}{}{seawind1:25, clang:10, waves1:15, clangl:15, waves:15, seawind:20}

# Map 137, base 1380
{1380}{}{San Fran China}
{1385}{}{21sf}
{1386}{}{seawind1:25, seawind:25, chimes1:15, chimes:15, blank:20}

# Map 139, base 1400
{1400}{}{Shi Temple}
{1405}{}{21sf}
{1406}{}{}

# Map 140, base 1410
{1410}{}{San Fran BoS}
{1415}{}{}
{1416}{}{}

# Map 141, base 1420
{1420}{}{Necropolis Hotel}
{1425}{}{14necro}
{1426}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 142, base 1430
{1430}{}{Necropolis Seth}
{1435}{}{11chilrn}
{1436}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 143, base 1440
{1440}{}{Necropolis Pump}
{1445}{}{14necro}
{1446}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 144, base 1450
{1450}{}{Necropolis Sewer}
{1455}{}{14necro}
{1456}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 145, base 1460
{1460}{}{Necropolis Vault Level 1}
{1465}{}{14necro}
{1466}{}{animal:20, pebble:15, pebble1:15, water1:20, water:20, blank:15}

# Map 146, base 1470
{1470}{}{Necropolis Vault Level 2}
{1475}{}{14necro}
{1476}{}{animal:20, pebble:15, pebble1:15, water1:20, water:20, blank:15}

# Map 147, base 1480
{1480}{}{Necropolis Vault Level 3}
{1485}{}{14necro}
{1486}{}{animal:20, pebble:15, pebble1:15, water1:20, water:20, blank:15}

# Map 160, base 1610
{1610}{}{Desert Encounter 1}
{1615}{}{07desert}
{1615}{}{10labone}
{1615}{}{12junktn}
{1615}{}{24redd}
{1616}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 161, base 1620
{1620}{}{Desert Encounter 2}
{1625}{}{07desert}
{1625}{}{10labone}
{1625}{}{12junktn}
{1625}{}{24redd}
{1626}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 162, base 1630
{1630}{}{Desert Encounter 3}
{1635}{}{07desert}
{1635}{}{10labone}
{1635}{}{12junktn}
{1635}{}{24redd}
{1636}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 163, base 1640
{1640}{}{Desert Encounter 4}
{1645}{}{07desert}
{1645}{}{10labone}
{1645}{}{12junktn}
{1645}{}{24redd}
{1646}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 164, base 1650
{1650}{}{Desert Encounter 5}
{1655}{}{07desert}
{1655}{}{10labone}
{1655}{}{12junktn}
{1655}{}{24redd}
{1656}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 165, base 1660
{1660}{}{Desert Encounter 6}
{1665}{}{07desert}
{1665}{}{10labone}
{1665}{}{12junktn}
{1665}{}{24redd}
{1666}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 166, base 1670
{1670}{}{Desert Tree Encounter 1}
{1675}{}{07desert}
{1675}{}{17arroyo}
{1675}{}{18modoc}
{1675}{}{24redd}
{1676}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 167, base 1680
{1680}{}{Desert Tree Encounter 2}
{1685}{}{07desert}
{1685}{}{17arroyo}
{1685}{}{18modoc}
{1685}{}{24redd}
{1686}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 168, base 1690
{1690}{}{Desert Tree Encounter 3}
{1695}{}{07desert}
{1695}{}{17arroyo}
{1695}{}{18modoc}
{1695}{}{24redd}
{1696}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 169, base 1700
{1700}{}{Desert Tree Encounter 4}
{1705}{}{07desert}
{1705}{}{17arroyo}
{1705}{}{18modoc}
{1705}{}{24redd}
{1706}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 170, base 1710
{1710}{}{Mountain Encounter 1}
{1715}{}{07desert}
{1715}{}{08vats}
{1715}{}{10labone}
{1715}{}{18modoc}
{1715}{}{24redd}
{1716}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 171, base 1720
{1720}{}{Mountain Encounter 2}
{1725}{}{07desert}
{1725}{}{08vats}
{1725}{}{10labone}
{1725}{}{18modoc}
{1725}{}{24redd}
{1726}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 172, base 1730
{1730}{}{Mountain Encounter 3}
{1735}{}{07desert}
{1735}{}{08vats}
{1735}{}{10labone}
{1735}{}{18modoc}
{1735}{}{24redd}
{1736}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 173, base 1740
{1740}{}{Mountain Encounter 4}
{1745}{}{07desert}
{1745}{}{08vats}
{1745}{}{10labone}
{1745}{}{18modoc}
{1745}{}{24redd}
{1746}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 174, base 1750
{1750}{}{Mountain Encounter 5}
{1755}{}{07desert}
{1755}{}{08vats}
{1755}{}{10labone}
{1755}{}{18modoc}
{1755}{}{24redd}
{1756}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 175, base 1760
{1760}{}{Mountain Encounter 6}
{1765}{}{07desert}
{1765}{}{08vats}
{1765}{}{10labone}
{1765}{}{18modoc}
{1765}{}{24redd}
{1766}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 176, base 1770
{1770}{}{Mountain Encounter 7}
{1775}{}{07desert}
{1775}{}{08vats}
{1775}{}{10labone}
{1775}{}{18modoc}
{1775}{}{24redd}
{1776}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 177, base 1780
{1780}{}{Mountain Encounter 8}
{1785}{}{07desert}
{1785}{}{08vats}
{1785}{}{10labone}
{1785}{}{18modoc}
{1785}{}{24redd}
{1786}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 178, base 1790
{1790}{}{Mountain Encounter 9}
{1795}{}{07desert}
{1795}{}{08vats}
{1795}{}{10labone}
{1795}{}{18modoc}
{1795}{}{24redd}
{1796}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 180, base 1810
{1810}{}{Cave Encounter Out 1}
{1815}{}{07desert}
{1816}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 181, base 1820
{1820}{}{Cave Encounter Out 2}
{1825}{}{07desert}
{1826}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 182, base 1830
{1830}{}{Cave Encounter Out 3}
{1835}{}{07desert}
{1836}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 183, base 1840
{1840}{}{Cave Encounter Out 4}
{1845}{}{07desert}
{1846}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 184, base 1850
{1850}{}{Cave Encounter Out 5}
{1855}{}{07desert}
{1856}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 185, base 1860
{1860}{}{Cave Encounter In 5}
{1865}{}{13carvrn}
{1865}{}{08vats}
{1866}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, animal1:15, animal:10}

# Map 186, base 1870
{1870}{}{Cave Encounter In 5}
{1875}{}{13carvrn}
{1875}{}{08vats}
{1876}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, animal1:15, animal:10}

# Map 187, base 1880
{1880}{}{Cave Encounter In 5}
{1885}{}{13carvrn}
{1885}{}{08vats}
{1886}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, animal1:15, animal:10}

# Map 188, base 1890
{1890}{}{Cave Encounter In 5}
{1895}{}{13carvrn}
{1895}{}{08vats}
{1896}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, animal1:15, animal:10}

# Map 189, base 1900
{1900}{}{Cave Encounter In 5}
{1905}{}{13carvrn}
{1905}{}{08vats}
{1906}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 190, base 1910
{1910}{}{City Encounter 1}
{1915}{}{10labone}
{1915}{}{14necro}
{1915}{}{16follow}
{1916}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 191, base 1920
{1920}{}{City Encounter 2}
{1925}{}{10labone}
{1925}{}{14necro}
{1925}{}{16follow}
{1926}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 192, base 1930
{1930}{}{City Encounter 3}
{1935}{}{10labone}
{1935}{}{14necro}
{1935}{}{16follow}
{1936}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 193, base 1940
{1940}{}{City Encounter 4}
{1945}{}{10labone}
{1945}{}{14necro}
{1945}{}{16follow}
{1946}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 194, base 1950
{1950}{}{City Encounter 5}
{1955}{}{10labone}
{1955}{}{14necro}
{1955}{}{16follow}
{1956}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 195, base 1960
{1960}{}{City Encounter 6}
{1965}{}{10labone}
{1965}{}{14necro}
{1965}{}{16follow}
{1966}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 196, base 1970
{1970}{}{City Encounter 7}
{1975}{}{10labone}
{1975}{}{14necro}
{1975}{}{16follow}
{1976}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 197, base 1980
{1980}{}{City Encounter 8}
{1985}{}{10labone}
{1985}{}{14necro}
{1985}{}{16follow}
{1986}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 198, base 1990
{1990}{}{City Encounter 9}
{1995}{}{10labone}
{1995}{}{14necro}
{1995}{}{16follow}
{1996}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 199, base 2000
{2000}{}{City Encounter 10}
{2005}{}{10labone}
{2005}{}{14necro}
{2005}{}{16follow}
{2006}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 200, base 2010
{2010}{}{Shoreline Encounter 1}
{2015}{}{07desert}
{2016}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 201, base 2020
{2020}{}{Shoreline Encounter 2}
{2025}{}{07desert}
{2026}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 202, base 2030
{2030}{}{Shoreline Encounter 3}
{2035}{}{07desert}
{2036}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 203, base 2040
{2040}{}{Shoreline Encounter 4}
{2045}{}{07desert}
{2046}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 204, base 2050
{2050}{}{Shoreline Encounter 5}
{2055}{}{07desert}
{2056}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 205, base 2060
{2060}{}{Skyscraper Encounter 1}
{2065}{}{10labone}
{2065}{}{14necro}
{2065}{}{16follow}
{2066}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 206, base 2070
{2070}{}{Skyscraper Encounter 2}
{2075}{}{10labone}
{2075}{}{14necro}
{2075}{}{16follow}
{2076}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 207, base 2080
{2080}{}{Skyscraper Encounter 3}
{2085}{}{10labone}
{2085}{}{14necro}
{2085}{}{16follow}
{2086}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 208, base 2090
{2090}{}{Skyscraper Encounter 4}
{2095}{}{10labone}
{2095}{}{14necro}
{2095}{}{16follow}
{2096}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 209, base 2100
{2100}{}{Skyscraper Encounter 4}
{2105}{}{10labone}
{2105}{}{14necro}
{2105}{}{16follow}
{2106}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 210, base 2110
{2110}{}{Skyscraper Encounter 4}
{2115}{}{10labone}
{2115}{}{14necro}
{2115}{}{16follow}
{2116}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 211, base 2120
{2120}{}{Skyscraper Encounter 5}
{2125}{}{10labone}
{2125}{}{14necro}
{2125}{}{16follow}
{2126}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 212, base 2130
{2130}{}{Cave Encounter In 6}
{2135}{}{13carvrn}
{2135}{}{08vats}
{2136}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, animal1:15, animal:10}

# Map 213, base 2140
{2140}{}{Cave Encounter Out 6}
{2145}{}{07desert}
{2146}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 214, base 2150
{2150}{}{City Coast Encounter 1}
{2155}{}{10labone}
{2156}{}{seawind1:25, seawind:25, waves1:10, seagull:15, seagull1:15, waves:10}

# Map 215, base 2160
{2160}{}{City Coast Encounter 2}
{2165}{}{10labone}
{2166}{}{seawind1:25, seawind:25, waves1:10, seagull:15, seagull1:15, waves:10}

# Map 216, base 2170
{2170}{}{City Coast Encounter 3}
{2175}{}{10labone}
{2176}{}{seawind1:25, seawind:25, waves1:10, seagull:15, seagull1:15, waves:10}

# Map 217, base 2180
{2180}{}{City Encounter 11}
{2185}{}{10labone}
{2185}{}{14necro}
{2185}{}{16follow}
{2186}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 218, base 2190
{2190}{}{City Encounter 12}
{2195}{}{10labone}
{2195}{}{14necro}
{2195}{}{16follow}
{2196}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 221, base 2220
{2220}{}{Hub Downtown}
{2225}{}{01hub}
{2226}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 222, base 2230
{2230}{}{Hub Oldtown}
{2235}{}{01hub}
{2236}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 223, base 2240
{2240}{}{Hub Heights}
{2245}{}{01hub}
{2246}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 224, base 2250
{2250}{}{Hub Watermerchants}
{2255}{}{01hub}
{2256}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 225, base 2260
{2260}{}{Hub Underground}
{2265}{}{01hub}
{2266}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 226, base 2270
{2270}{}{Hub Underground}
{2275}{}{01hub}
{2276}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 227, base 2280
{2280}{}{Hub Arena}
{2285}{}{01hub}
{2286}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 228, base 2290
{2290}{}{Buffer Map}
{2295}{}{}
{2296}{}{}

# Map 229, base 2300
{2300}{}{Caravans}
{2305}{}{}
{2306}{}{}

# Map 230, base 2310
{2310}{}{HQ: Camp}
{2315}{}{07desert}
{2315}{}{05raider}
{2316}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 231, base 2320
{2320}{}{HQ: Khans}
{2325}{}{07desert}
{2325}{}{05raider}
{2326}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 232, base 2330
{2330}{}{HQ: Blades}
{2335}{}{07desert}
{2335}{}{16follow}
{2335}{}{10labone}
{2336}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 233, base 2340
{2340}{}{HQ: Scrapheap}
{2345}{}{07desert}
{2345}{}{18modoc}
{2346}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 234, base 2350
{2350}{}{HQ: Depot}
{2355}{}{07desert}
{2355}{}{05raider}
{2355}{}{10labone}
{2356}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 235, base 2360
{2360}{}{HQ: Cave Inside}
{2365}{}{13carvrn}
{2366}{}{animal:20, pebble:15, pebble1:15, water1:20, water:20, blank:15}

# Map 236, base 2370
{2370}{}{HQ: Cave Outside}
{2375}{}{07desert}
{2375}{}{18modoc}
{2376}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 237, base 2380
{2380}{}{HQ: Bunker Indoor}
{2385}{}{14necro}
{2385}{}{08vats}
{2386}{}{elevato1:25, elevator:25, electri1:15, electric:15, clank:10, clank1:10}

# Map 238, base 2390
{2390}{}{HQ: Bunker Outdoor}
{2395}{}{07desert}
{2395}{}{05raider}
{2395}{}{10labone}
{2395}{}{14necro}
{2396}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 239, base 2400
{2400}{}{HQ: Gasstation}
{2405}{}{07desert}
{2405}{}{10labone}
{2406}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 240, base 2410
{2410}{}{Glow: Entrance}
{2415}{}{09glow}
{2416}{}{electri1:15, electric:15, clank:10, clank1:10, steam:15, steam:10}

# Map 241, base 2420
{2420}{}{Glow: Floor 1}
{2425}{}{09glow}
{2426}{}{electri1:15, electric:15, clank:10, clank1:10, steam:15, steam:10}

# Map 242, base 2430
{2430}{}{Glow: Floor 2}
{2435}{}{09glow}
{2436}{}{electri1:15, electric:15, clank:10, clank1:10, steam:15, steam:10}

# Map 243, base 2440
{2440}{}{Glow: Floor 3}
{2445}{}{09glow}
{2446}{}{electri1:15, electric:15, clank:10, clank1:10, steam:15, steam:10}

# Map 244, base 2450
{2450}{}{Glow: Floor 4}
{2455}{}{09glow}
{2456}{}{electri1:15, electric:15, clank:10, clank1:10, steam:15, steam:10}

# Map 245, base 2460
{2460}{}{Glow: Floor 5}
{2465}{}{09glow}
{2466}{}{electri1:15, electric:15, clank:10, clank1:10, steam:15, steam:10}

# Map 246, base 2470
{2470}{}{Glow: Floor 6}
{2475}{}{09glow}
{2476}{}{electri1:15, electric:15, clank:10, clank1:10, steam:15, steam:10}

# Map 247, base 2480
{2480}{}{New Reno: Golgotha}
{2485}{}{10labone}
{2486}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 260, base 2610
{2610}{}{New Reno: Basement}
{2615}{}{19reno}
{2616}{}{drunkla1:20, drunklaf:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 261, base 2620
{2620}{}{New Reno: Bishop Floor 1}
{2625}{}{19reno}
{2626}{}{drunkla1:20, drunklaf:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 262, base 2630
{2630}{}{New Reno: Bishop Floor 2}
{2635}{}{19reno}
{2636}{}{drunkla1:20, drunklaf:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 263, base 2640
{2640}{}{New Reno: Mordino HQ}
{2645}{}{19reno}
{2646}{}{drunkla1:20, drunklaf:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 264, base 2650
{2650}{}{New Reno: Arms}
{2655}{}{19reno}
{2656}{}{drunkla1:20, drunklaf:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 265, base 2660
{2660}{}{New Reno: Shark Boxing}
{2665}{}{19reno}
{2666}{}{drunkla1:20, drunklaf:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 266, base 2670
{2670}{}{New Reno: Wright}
{2675}{}{19reno}
{2676}{}{drunkla1:20, drunklaf:20, laughter:15, laughte1:15, shots1:15, shots:10}

# Map 267, base 2680
{2680}{}{New Reno: Stables}
{2685}{}{05raider}
{2686}{}{gntlwin1:25, gntlwind:25, gustwind:10, blank:40}

# Map 268, base 2690
{2690}{}{New Reno: Stables 2}
{2695}{}{05raider}
{2696}{}{gntlwin1:25, gntlwind:25, gustwind:10, blank:40}

# Map 269, base 2700
{2700}{}{Modoc: Ghostcave}
{2705}{}{18modoc}
{2706}{}{}

# Map 270, base 2710
{2710}{}{Modoc: Ghostfarm}
{2715}{}{18modoc}
{2716}{}{}

# Map 275, base 2760
{2760}{}{Replication 1}
{2765}{}{07desert}
{2766}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 276, base 2770
{2770}{}{Replication 2}
{2775}{}{07desert}
{2776}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 277, base 2780
{2780}{}{Replication 3}
{2785}{}{07desert}
{2786}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 278, base 2790
{2790}{}{Replication 4}
{2795}{}{07desert}
{2796}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 279, base 2800
{2800}{}{Gunrunner}
{2805}{}{10labone}
{2806}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 280, base 2810
{2810}{}{Adytum}
{2815}{}{10labone}
{2816}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 281, base 2820
{2820}{}{Adytum Sub}
{2825}{}{10labone}
{2826}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 282, base 2830
{2830}{}{Blade}
{2835}{}{16Follow}
{2836}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 283, base 2840
{2840}{}{Library}
{2845}{}{16follow}
{2846}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 284, base 2850
{2850}{}{Library Level 1}
{2855}{}{16follow}
{2856}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 285, base 2860
{2860}{}{Ripper}
{2865}{}{10labone}
{2866}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 286, base 2870
{2870}{}{Ripper Sub}
{2875}{}{10labone}
{2876}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 287, base 2880
{2880}{}{Tent in the desert}
{2885}{}{07desert}
{2886}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 288, base 2890
{2890}{}{Tent in the mountains}
{2895}{}{07desert}
{2896}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 289, base 2900
{2900}{}{Tent on the coast}
{2905}{}{07desert}
{2906}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 290, base 2910
{2910}{}{Tent in the city}
{2915}{}{07desert}
{2915}{}{10labone}
{2916}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 291, base 2920
{2920}{}{Prospect Trees}
{2925}{}{}
{2926}{}{}

# Map 300, base 3010
{3010}{}{Farmhome}
{3015}{}{07desert}
{3016}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 301, base 3020
{3020}{}{Stranded Tanker: Outside}
{3025}{}{07desert}
{3026}{}{seawind1:25, gntlwind:25, gustwind:10, seagull:15, seagull:15, waves:10}

# Map 302, base 3030
{3030}{}{Stranded Tanker: Level 1}
{3035}{}{08vats}
{3036}{}{seawind1:25, gntlwin1:30, clang:10, gustwin1:10, vulture:10, vulture1:10, seawind:20, waves1:15, clangl:15}

# Map 303, base 3040
{3040}{}{Stranded Tanker: Level 2}
{3045}{}{08vats}
{3046}{}{seawind1:25, gntlwin1:30, clang:10, gustwin1:10, vulture:10, vulture1:10, seawind:20, waves1:15, clangl:15}

# Map 304, base 3050
{3050}{}{Stranded Tanker: Level 3}
{3055}{}{08vats}
{3056}{}{seawind1:25, gntlwin1:30, clang:10, gustwin1:10, vulture:10, vulture1:10, seawind:20, waves1:15, clangl:15}

# Map 305, base 3060
{3060}{}{Railroad Gang}
{3065}{}{15shady}
{3066}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 306, base 3070
{3070}{}{Outpost}
{3075}{}{07desert}
{3076}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 307, base 3080
{3080}{}{Hideout}
{3085}{}{07desert}
{3086}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 308, base 3090
{3090}{}{Secret Shelter Out}
{3095}{}{07desert}
{3096}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 309, base 3100
{3100}{}{Secret Shelter In}
{3105}{}{14necro}
{3106}{}{animal:20, pebble:15, pebble1:15, water1:20, water:20, blank:15}

# Map 310, base 3110
{3110}{}{Treasure}
{3115}{}{07desert}
{3116}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 311, base 3120
{3120}{}{Ambush!}
{3125}{}{10labone}
{3126}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 312, base 3130
{3130}{}{Abandoned Howitzer}
{3135}{}{07desert}
{3136}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 313, base 3140
{3140}{}{Crashed Hummer}
{3145}{}{07desert}
{3146}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 314, base 3150
{3150}{}{Battleground}
{3155}{}{}
{3156}{}{}

# Map 315, base 3160
{3160}{}{BoS bunker level 1}
{3165}{}{14necro}
{3166}{}{}

# Map 316, base 3170
{3170}{}{BoS bunker level 2}
{3175}{}{14necro}
{3176}{}{}

# Map 317, base 3180
{3180}{}{BoS bunker level 3}
{3185}{}{14necro}
{3186}{}{}

# Map 325, base 3260
{3260}{}{Replication 5}
{3265}{}{21sf}
{3266}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 326, base 3270
{3270}{}{Replication 6}
{3275}{}{07desert}
{3276}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 327, base 3280
{3280}{}{Replication 7}
{3285}{}{24redd}
{3286}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 328, base 3290
{3290}{}{Salvager Camp}
{3295}{}{10labone}
{3296}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 340, base 3410
{3410}{}{Crashed Vertibird}
{3415}{}{07desert}
{3416}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 341, base 3420
{3420}{}{Crashed Vertibird Desert}
{3425}{}{07desert}
{3426}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 342, base 3430
{3430}{}{Crashed Vertibird City}
{3435}{}{07desert}
{3436}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 343, base 3440
{3440}{}{Crashed Vertibird Coast}
{3445}{}{07desert}
{3446}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 344, base 3450
{3450}{}{Crashed Vertibird Mountain}
{3455}{}{07desert}
{3456}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 345, base 3460
{3460}{}{Desert Encounter 5}
{3465}{}{07desert}
{3465}{}{10labone}
{3465}{}{12junktn}
{3465}{}{24redd}
{3466}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 346, base 3470
{3470}{}{Desert Encounter 6}
{3475}{}{07desert}
{3475}{}{10labone}
{3475}{}{12junktn}
{3475}{}{24redd}
{3476}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 347, base 3480
{3480}{}{Highway 1}
{3485}{}{07desert}
{3485}{}{10labone}
{3485}{}{12junktn}
{3485}{}{24redd}
{3486}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 348, base 3490
{3490}{}{Highway 2}
{3495}{}{07desert}
{3495}{}{10labone}
{3495}{}{12junktn}
{3495}{}{24redd}
{3496}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 370, base 3710
{3710}{}{Mining Site}
{3715}{}{07desert}
{3716}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 371, base 3720
{3720}{}{Mining Site Inside}
{3725}{}{08vats}
{3726}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 372, base 3730
{3730}{}{San Francisco Mining Site}
{3735}{}{21sf}
{3736}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 373, base 3740
{3740}{}{San Francisco Mining Site Inside}
{3745}{}{08vats}
{3746}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 374, base 3750
{3750}{}{Klamath Mining Site}
{3755}{}{15shady}
{3756}{}{gntlwin1:25, gntlwind:25, gustwind:10, brdchirp:10, rattle1:15, vulture:10}

# Map 375, base 3760
{3760}{}{Klamath Mining Site Inside}
{3765}{}{08vats}
{3766}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 376, base 3770
{3770}{}{NCR Mining Site}
{3775}{}{01hub}
{3776}{}{gntlwin1:25, gntlwind:25, gustwind:10, brdchirp:10, rattle1:15, vulture:10}

# Map 377, base 3780
{3780}{}{Vault City Mining Site}
{3785}{}{07desert}
{3786}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 378, base 3790
{3790}{}{Vault City Mine Inside}
{3795}{}{08vats}
{3796}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 379, base 3800
{3800}{}{Junktown Mining Site}
{3805}{}{12junktn}
{3806}{}{gntlwin1:25, gntlwind:25, animal1:20, animal:20, gustwind:5, gustwin1:5}

# Map 380, base 3810
{3810}{}{Jail}
{3815}{}{07desert}
{3816}{}{elevato1:25, elevator:25, electri1:15, electric:15, clank:10, clank1:10}

# Map 385, base 3860
{3860}{}{HQ: Tents}
{3865}{}{07desert}
{3865}{}{17arroyo}
{3866}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 400, base 4010
{4010}{}{Cave Encounter In 7}
{4015}{}{13carvrn}
{4015}{}{08vats}
{4016}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, animal1:15, animal:10}

# Map 401, base 4020
{4020}{}{Cave Encounter Out 7}
{4025}{}{07desert}
{4026}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 450, base 4510
{4510}{}{Slaverun 1}
{4515}{}{07desert}
{4516}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 451, base 4520
{4520}{}{Slaverun 2}
{4525}{}{07desert}
{4526}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 452, base 4530
{4530}{}{Slaverun 3}
{4535}{}{07desert}
{4536}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 453, base 4540
{4540}{}{Slaverun 4}
{4545}{}{07desert}
{4546}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 454, base 4550
{4550}{}{Slaverun 5}
{4555}{}{07desert}
{4556}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 455, base 4560
{4560}{}{Slaverun 6}
{4565}{}{10labone}
{4566}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 500, base 5010
{5010}{}{Desert Encounter 7}
{5015}{}{07desert}
{5015}{}{10labone}
{5015}{}{12junktn}
{5015}{}{24redd}
{5016}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 501, base 5020
{5020}{}{Desert Encounter 8}
{5025}{}{07desert}
{5025}{}{10labone}
{5025}{}{12junktn}
{5025}{}{24redd}
{5026}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 502, base 5030
{5030}{}{Desert Encounter 9}
{5035}{}{07desert}
{5035}{}{10labone}
{5035}{}{12junktn}
{5035}{}{24redd}
{5036}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 503, base 5040
{5040}{}{Desert Encounter 10}
{5045}{}{07desert}
{5045}{}{10labone}
{5045}{}{12junktn}
{5045}{}{24redd}
{5046}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 504, base 5050
{5050}{}{Desert Encounter 11}
{5055}{}{07desert}
{5055}{}{10labone}
{5055}{}{12junktn}
{5055}{}{24redd}
{5056}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 505, base 5060
{5060}{}{Desert Encounter Necropolis 1}
{5065}{}{07desert}
{5065}{}{05raider}
{5065}{}{12junktn}
{5065}{}{14necro}
{5066}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 506, base 5070
{5070}{}{Desert Encounter Necropolis 2}
{5075}{}{07desert}
{5075}{}{05raider}
{5075}{}{12junktn}
{5075}{}{14necro}
{5076}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 507, base 5080
{5080}{}{Desert Encounter Necropolis 3}
{5085}{}{07desert}
{5085}{}{05raider}
{5085}{}{12junktn}
{5085}{}{14necro}
{5086}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 508, base 5090
{5090}{}{Desert Encounter Necropolis 4}
{5095}{}{07desert}
{5095}{}{05raider}
{5095}{}{12junktn}
{5095}{}{14necro}
{5096}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 509, base 5100
{5100}{}{Desert Encounter Rails 1}
{5105}{}{07desert}
{5105}{}{10labone}
{5106}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 511, base 5120
{5120}{}{Desert Encounter Water 1}
{5125}{}{07desert}
{5125}{}{10labone}
{5126}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 512, base 5130
{5130}{}{Desert Encounter Water 2}
{5135}{}{07desert}
{5136}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 513, base 5140
{5140}{}{Desert Encounter Water 3}
{5145}{}{07desert}
{5146}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 514, base 5150
{5150}{}{Desert Encounter 12}
{5155}{}{07desert}
{5156}{}{gustwind:30, gustwin1:30, rattle:10, rattle1:20, vulture:10, vulture1:10}

# Map 549, base 5500
{5500}{}{Tipperary}
{5505}{}{24redd}
{5506}{}{}

# Map 550, base 5510
{5510}{}{Warzone}
{5515}{}{07desert}
{5516}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 551, base 5520
{5520}{}{Warzone}
{5525}{}{07desert}
{5526}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 552, base 5530
{5530}{}{San Fransisco Train Station}
{5535}{}{21sf}
{5536}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 553, base 5540
{5540}{}{Boneyard Train Station}
{5545}{}{01hub}
{5546}{}{gntlwin1:25, gntlwind:25, dogbark:20, rattle:15, gustwin1:10, vulture:10}

# Map 554, base 5550
{5550}{}{NCR  Train Station}
{5555}{}{07desert}
{5556}{}{gntlwin1:25, gntlwind:25, brdchir1:10, brdchirp:10, blank:30}

# Map 555, base 5560
{5560}{}{Vault City Train Station}
{5565}{}{22vcity}
{5566}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 556, base 5570
{5570}{}{Junkyard}
{5575}{}{junkyard.ogg}
{5576}{}{}

# Map 557, base 5580
{5580}{}{Spawn 1 in}
{5585}{}{07desert}
{5586}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 558, base 5590
{5590}{}{Spawn 1 out}
{5595}{}{07desert}
{5596}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 559, base 5600
{5600}{}{Spawn 2 in}
{5605}{}{07desert}
{5606}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 560, base 5610
{5610}{}{Spawn 2 out}
{5615}{}{07desert}
{5616}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 561, base 5620
{5620}{}{Spawn 3 in}
{5625}{}{07desert}
{5626}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 562, base 5630
{5630}{}{Spawn 3 out}
{5635}{}{07desert}
{5636}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 563, base 5640
{5640}{}{Ant Pit 1}
{5645}{}{07desert}
{5646}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 564, base 5650
{5650}{}{Themepark}
{5655}{}{07desert}
{5656}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 565, base 5660
{5660}{}{Waterworks}
{5665}{}{waterworks.ogg}
{5666}{}{gustwind:20, gustwin1:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 566, base 5670
{5670}{}{Gordon's Gas Station}
{5675}{}{07desert}
{5676}{}{gntlwin1:20, gntlwind:20, rattle:15, rattle1:15, vulture:15, vulture1:15}

# Map 567, base 5680
{5680}{}{Mountain Passage}
{5685}{}{07desert}
{5686}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 568, base 5690
{5690}{}{Slaver Camp}
{5695}{}{07desert}
{5696}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

# Map 569, base 5700
{5700}{}{Military Camp}
{5705}{}{07desert}
{5706}{}{gntlwin1:25, gntlwind:25, gustwind:10, rattle:15, rattle1:15, vulture:10}

#
# Global map
#

# Name, (pid + 100) * 1000 + 0
# Info, (pid + 100) * 1000 + 5
# Radius, (pid + 100) * 1000 + 10, 6,12,24
# Fid location, (pid + 100) * 1000 + 20
# Fid tab, (pid + 100) * 1000 + 30
# Count entires, (pid + 100) * 1000 + 90
# Entire X name, (pid + 100) * 1000 + 100 + X*10 + 1
# Entire X pic x, (pid + 100) * 1000 + 100 + X*10 + 2
# Entire X pic y, (pid + 100) * 1000 + 100 + X*10 + 3

# The Den, pid 1, base 101000
{101000}{}{The Den}
{101005}{}{A town of junkies and slavers.}
{101010}{}{24}
{101020}{}{art\intrface\twnden.frm}
{101030}{}{art\intrface\WM_DEN.FRM}
{101090}{}{3}
{101101}{}{Downtown}
{101102}{}{124}
{101103}{}{293}
{101111}{}{East Side}
{101112}{}{262}
{101113}{}{330}
{101121}{}{South Side}
{101122}{}{205}
{101123}{}{357}

# Klamath, pid 2, base 102000
{102000}{}{Klamath}
{102005}{}{A small town of trappers. Geckos are the lifeblood of this small community.}
{102010}{}{24}
{102020}{}{art\intrface\twnklama.frm}
{102030}{}{art\intrface\WM_KLAM.FRM}
{102090}{}{4}
{102101}{}{Downtown}
{102102}{}{363}
{102103}{}{186}
{102111}{}{Hunting Ground}
{102112}{}{377}
{102113}{}{297}
{102121}{}{Trapper Town}
{102122}{}{191}
{102123}{}{320}
{102131}{}{Forest}
{102132}{}{207}
{102133}{}{134}

# Modoc, pid 3, base 103000
{103000}{}{Modoc}
{103005}{}{A small farming community.}
{103010}{}{24}
{103020}{}{art\intrface\twnmodoc.frm}
{103030}{}{art\intrface\WM_MODOC.FRM}
{103090}{}{3}
{103101}{}{South}
{103102}{}{312}
{103103}{}{212}
{103111}{}{North}
{103112}{}{258}
{103113}{}{69}
{103121}{}{East}
{103122}{}{360}
{103123}{}{136}

# Vault City, pid 4, base 104000
{104000}{}{Vault City}
{104005}{}{A high-tech settlement. Established by the inhabitants of Vault 8.}
{104010}{}{24}
{104020}{}{art\intrface\twnvcity.frm}
{104030}{}{art\intrface\WM_VLTCT.FRM}
{104090}{}{1}
{104101}{}{Vault City}
{104102}{}{306}
{104103}{}{246}

# Gecko, pid 5, base 105000
{105000}{}{Gecko}
{105005}{}{A town of ghouls built around a leaking nuclear power plant.}
{105010}{}{24}
{105020}{}{art\intrface\twngecko.frm}
{105030}{}{art\intrface\WM_GECKO.FRM}
{105090}{}{4}
{105101}{}{Settlement}
{105102}{}{155}
{105103}{}{246}
{105111}{}{South West}
{105112}{}{40}
{105113}{}{156}
{105121}{}{Scrapyard}
{105122}{}{279}
{105123}{}{169}
{105131}{}{Reactor}
{105132}{}{168}
{105133}{}{147}

# Broken Hills, pid 6, base 106000
{106000}{}{Broken Hills}
{106005}{}{A town of humans, mutants and ghouls. Racism is rampant.}
{106010}{}{24}
{106020}{}{art\intrface\twnbrokn.frm}
{106030}{}{art\intrface\WM_HILLS.FRM}
{106090}{}{3}
{106101}{}{Downtown}
{106102}{}{125}
{106103}{}{276}
{106111}{}{Residental}
{106112}{}{367}
{106113}{}{284}
{106121}{}{South Side}
{106122}{}{246}
{106123}{}{359}

# New Reno, pid 7, base 107000
{107000}{}{New Reno}
{107005}{}{A town of casinos, drugs and debauchery.}
{107010}{}{24}
{107020}{}{art\intrface\twnreno.frm}
{107030}{}{art\intrface\WM_RENO.FRM}
{107090}{}{5}
{107101}{}{Virgin Street}
{107102}{}{230}
{107103}{}{300}
{107111}{}{2nd Street}
{107112}{}{230}
{107113}{}{210}
{107121}{}{Commercial Row}
{107122}{}{100}
{107123}{}{210}
{107131}{}{East side}
{107132}{}{360}
{107133}{}{210}
{107141}{}{Gas station}
{107142}{}{360}
{107143}{}{100}

# Sierra, pid 8, base 108000
{108000}{}{Sierra}
{108005}{}{An old military warehouse.}
{108010}{}{12}
{108020}{}{art\intrface\twnsad.frm}
{108030}{}{art\intrface\WM_ARMY.FRM}
{108090}{}{1}
{108101}{}{Sierra}
{108102}{}{130}
{108103}{}{150}

# Vault 15, pid 9, base 109000
{109000}{}{Vault 15}
{109005}{}{An old Vault.}
{109010}{}{12}
{109020}{}{art\intrface\twnv15.frm}
{109030}{}{art\intrface\WM_VLT15.FRM}
{109090}{}{1}
{109101}{}{Surface}
{109102}{}{80}
{109103}{}{256}

# NCR, pid 10, base 110000
{110000}{}{NCR}
{110005}{}{Shady Sands, the central government of the New California Republic. The most powerful city in the wastes.}
{110010}{}{24}
{110020}{}{art\intrface\twnncr.frm}
{110030}{}{art\intrface\WM_NCR.FRM}
{110090}{}{3}
{110101}{}{Bazaar}
{110102}{}{258}
{110103}{}{175}
{110111}{}{Vortis Holding Center}
{110112}{}{183}
{110113}{}{134}
{110121}{}{Residence}
{110122}{}{318}
{110123}{}{241}

# Cathedral, pid 11, base 111000
{111000}{}{Cathedral}
{111005}{}{An old Cathedral among city ruins, lighted up by burning barrels. People are wandering outside in a large crowd.}
{111010}{}{6}
{111020}{}{art\intrface\twnmap11.frm}
{111030}{}{art\intrface\wm_cathedral.frm}
{111090}{}{1}
{111101}{}{Entrance}
{111102}{}{73}
{111103}{}{341}

# Mariposa Military Base, pid 12, base 112000
{112000}{}{Mariposa Military Base}
{112005}{}{A military facility built to house the Forced Evolutionary Virus}
{112010}{}{12}
{112020}{}{art\intrface\twnmilbs.frm}
{112030}{}{art\intrface\WM_MLTRY.FRM}
{112090}{}{1}
{112101}{}{Entrance}
{112102}{}{125}
{112103}{}{58}

# Redding, pid 13, base 113000
{113000}{}{Redding}
{113005}{}{A mining town. The primary producer and distributor of gold in the wasteland.}
{113010}{}{24}
{113020}{}{art\intrface\twnredng.frm}
{113030}{}{art\intrface\WM_RED.FRM}
{113090}{}{3}
{113101}{}{Downtown}
{113102}{}{160}
{113103}{}{231}
{113111}{}{South Side}
{113112}{}{82}
{113113}{}{304}
{113121}{}{Mine}
{113122}{}{115}
{113123}{}{204}

# San Francisco, pid 14, base 114000
{114000}{}{San Francisco}
{114005}{}{A high-tech city built by the descendants of a Chinese submarine.}
{114010}{}{24}
{114020}{}{art\intrface\twnsanfr.frm}
{114030}{}{art\intrface\WM_SANFN.FRM}
{114090}{}{3}
{114101}{}{Downtown}
{114102}{}{339}
{114103}{}{147}
{114111}{}{Ruins}
{114112}{}{301}
{114113}{}{164}
{114121}{}{Tanker}
{114122}{}{344}
{114123}{}{115}

# Navarro, pid 15, base 115000
{115000}{}{Navarro}
{115005}{}{An Enclave military base.}
{115010}{}{12}
{115020}{}{art\intrface\twnnavro.frm}
{115030}{}{art\intrface\WM_NAVAR.FRM}
{115090}{}{1}
{115101}{}{GAS station}
{115102}{}{278}
{115103}{}{233}

# Arroyo, pid 16, base 116000
{116000}{}{Arroyo}
{116005}{}{A small, isolated tribal village, founded by Vault 13 exiles.}
{116010}{}{12}
{116020}{}{art\intrface\twnarroy.frm}
{116030}{}{art\intrface\WM_ARROY.FRM}
{116090}{}{1}
{116101}{}{Temple}
{116102}{}{200}
{116103}{}{90}

# Junktown, pid 17, base 117000
{117000}{}{Junktown}
{117005}{}{The town was built after the Great War out of random pieces of junk, mostly of broken cars.}
{117010}{}{24}
{117020}{}{art\intrface\Twnmap03.frm}
{117030}{}{art\intrface\Wm_03.frm}
{117090}{}{2}
{117101}{}{North Entrance}
{117102}{}{154}
{117103}{}{226}
{117111}{}{South Entrance}
{117112}{}{412}
{117113}{}{323}

# Brotherhood of Steel, pid 18, base 118000
{118000}{}{Brotherhood of Steel}
{118005}{}{The Lost Hills old government bunker is the headquarters of the Brotherhood of Steel.}
{118010}{}{12}
{118020}{}{art\intrface\Twnmap07.frm}
{118030}{}{art\intrface\Wm_07.frm}
{118090}{}{1}
{118101}{}{Entrance}
{118102}{}{184}
{118103}{}{173}

# The Glow, pid 19, base 119000
{119000}{}{The Glow}
{119005}{}{West Tek was destroyed in the nuclear holocaust of 2077 leaving a gaping hole.}
{119010}{}{24}
{119020}{}{art\intrface\Twnmap09.frm}
{119030}{}{art\intrface\Wm_09.frm}
{119090}{}{1}
{119101}{}{Exterior}
{119102}{}{352}
{119103}{}{155}

# Golgotha, pid 20, base 120000
{120000}{}{Golgotha}
{120005}{}{Golgotha.}
{120010}{}{6}

# New Reno Stables, pid 21, base 121000
{121000}{}{New Reno Stables}
{121005}{}{The New Reno Stables owned and operated by the Mordinos.}
{121010}{}{6}

# Ghost Farm, pid 22, base 122000
{122000}{}{Ghost Farm}
{122005}{}{A small farm created by the Slags above their underground settlement.}
{122010}{}{6}

# Vault 13, pid 23, base 123000
{123000}{}{Vault 13}
{123005}{}{A Vault very well hidden in the mountains.}
{123010}{}{12}
{123020}{}{art\intrface\twnv13.frm}
{123030}{}{art\intrface\WM_VLT13.FRM}
{123090}{}{1}
{123101}{}{Cave}
{123102}{}{214}
{123103}{}{309}

# Necropolis, pid 24, base 124000
{124000}{}{Necropolis}
{124005}{}{A town built upon the charred remains of Bakersfield; the grim aftermath of Vault 12.}
{124010}{}{24}
{124020}{}{art\intrface\Twnmap05.frm}
{124030}{}{art\intrface\Wm_05.frm}
{124090}{}{3}
{124101}{}{Motel}
{124102}{}{410}
{124103}{}{271}
{124111}{}{Hall of the Dead}
{124112}{}{251}
{124113}{}{230}
{124121}{}{Watershed}
{124122}{}{91}
{124123}{}{213}

# Hub, pid 25, base 125000
{125000}{}{Hub}
{125005}{}{A major trading city with a large community of traders, gamblers and various other types of scum.}
{125010}{}{24}
{125020}{}{art\intrface\Twnmap06.frm}
{125030}{}{art\intrface\Wm_06.frm}
{125090}{}{5}
{125101}{}{Entrance}
{125102}{}{211}
{125103}{}{58}
{125111}{}{Market}
{125112}{}{203}
{125113}{}{132}
{125121}{}{Oldtown}
{125122}{}{273}
{125123}{}{118}
{125131}{}{The Heights}
{125132}{}{142}
{125133}{}{146}
{125141}{}{Water Merchants}
{125142}{}{198}
{125143}{}{210}

# New Adytum, pid 26, base 126000
{126000}{}{New Adytum}
{126005}{}{Amongst decimated skyscrapers lies the small industrial town named New Adytum.}
{126010}{}{12}
{126020}{}{art\intrface\Twnmap10.frm}
{126030}{}{art\intrface\Wm_10.frm}
{126090}{}{1}
{126101}{}{Adytum}
{126102}{}{288}
{126103}{}{245}

# Raiders, pid 27, base 127000
{127000}{}{Raiders}
{127005}{}{Northern Raider hideout.}
{127010}{}{12}
{127020}{}{art\intrface\Twnmap04.frm}
{127030}{}{art\intrface\Wm_04.frm}
{127090}{}{2}
{127101}{}{Cave Entrance}
{127102}{}{210}
{127103}{}{300}
{127111}{}{Cave}
{127112}{}{287}
{127113}{}{237}

# Ares Rocket Silo, pid 28, base 128000
{128000}{}{Ares Rocket Silo}
{128005}{}{In the distance you can see the remains of an old rocket silo. It seems like someone has pitched his camp there a short while ago.}
{128010}{}{6}

# Raiders South, pid 29, base 129000
{129000}{}{Raiders South}
{129005}{}{Southern Raider hideout.}
{129010}{}{12}
{129020}{}{art\intrface\twnmap04.frm}
{129030}{}{art\intrface\Wm_04.frm}
{129090}{}{1}
{129101}{}{Camp}
{129102}{}{210}
{129103}{}{300}

# Quarry, pid 30, base 130000
{130000}{}{Quarry}
{130005}{}{A well guarded NCR quarry.}
{130010}{}{6}

# Mining Site, pid 31, base 131000
{131000}{}{Mining Site}
{131005}{}{This mining site has been closed many years ago.}
{131010}{}{6}
{131020}{}{art\intrface\TWNMAP12.png}
{131090}{}{2}
{131101}{}{East}
{131102}{}{206}
{131103}{}{176}
{131111}{}{West}
{131112}{}{138}
{131113}{}{189}

# Mining Site, pid 32, base 132000
{132000}{}{Mining Site}
{132005}{}{This small mining site is run by a bunch of trappers from Klamath.}
{132010}{}{6}

# Mining Site, pid 33, base 133000
{133000}{}{Mining Site}
{133005}{}{A small industrial mining site, run by the San Francisco Communist Party.}
{133010}{}{6}

# Mining Site, pid 34, base 134000
{134000}{}{Mining Site}
{134005}{}{A small private underground mining site.}
{134010}{}{6}

# Crater, pid 35, base 135000
{135000}{}{Crater}
{135005}{}{The smell of death lies on this ground.}
{135010}{}{6}

# Library, pid 36, base 136000
{136000}{}{Library}
{136005}{}{The Public Library serves as the headquarters of the Followers of the Apocalypse.}
{136010}{}{8}
{136020}{}{art\intrface\Twnmap10.frm}
{136090}{}{1}
{136101}{}{Library}
{136102}{}{158}
{136103}{}{120}

# Warehouse, pid 37, base 137000
{137000}{}{Warehouse}
{137005}{}{An old warehouse between the ruins.}
{137010}{}{6}
{137020}{}{art\intrface\Twnmap10.frm}
{137090}{}{1}
{137101}{}{Warehouse}
{137102}{}{297}
{137103}{}{165}

# Salvagers, pid 38, base 138000
{138000}{}{Salvagers}
{138005}{}{Downtown is the home and headquarter for the salvagers of the Angel's Boneyard.}
{138010}{}{8}
{138020}{}{art\intrface\Twnmap10.frm}
{138090}{}{1}
{138101}{}{Boneyard Downtown}
{138102}{}{241}
{138103}{}{201}

# Gun Runners, pid 39, base 139000
{139000}{}{Gun Runners}
{139005}{}{The Fortress is surrounded by a moat of glowing green goo. This intimidating location is the home of the Gun Runners.}
{139010}{}{8}
{139020}{}{art\intrface\Twnmap10.frm}
{139090}{}{1}
{139101}{}{Gun Runners}
{139102}{}{358}
{139103}{}{120}

# Replication 1, pid 40, base 140000
{140000}{}{Replication 1}
{140005}{}{A small camp for the injured}
{140010}{}{6}

# Replication 2, pid 41, base 141000
{141000}{}{Replication 2}
{141005}{}{A small camp for the injured.}
{141010}{}{6}

# Replication 3, pid 42, base 142000
{142000}{}{Replication 3}
{142005}{}{A small camp for the injured.}
{142010}{}{6}

# Replication 4, pid 43, base 143000
{143000}{}{Replication 4}
{143005}{}{A small camp for the injured}
{143010}{}{6}

# Eventlocation 1, pid 44, base 144000
{144000}{}{Eventlocation 1}
{144005}{}{}
{144010}{}{12}

# Replication 5, pid 45, base 145000
{145000}{}{Replication 5}
{145005}{}{A small camp for the injured.}
{145010}{}{6}

# Replication 6, pid 46, base 146000
{146000}{}{Replication 6}
{146005}{}{A small camp for the injured.}
{146010}{}{6}

# Replication 7, pid 47, base 147000
{147000}{}{Replication 7}
{147005}{}{A small camp for the injured}
{147010}{}{6}

# Replication 8, pid 48, base 148000
{148000}{}{Replication 8}
{148005}{}{A small camp for the injured.}
{148010}{}{6}

# Tesla Tower, pid 49, base 149000
{149000}{}{Tesla Tower}
{149005}{}{A wireless  telecommunication tower, in control by the Brotherhood of Steel. Due to this tower, it was possible to greatly increase the general radio reception.}
{149010}{}{12}

# Hinkley, pid 50, base 150000
{150000}{}{Hinkley}
{150005}{}{A recreational area consisting of a few combat arenas for relaxation and training.}
{150010}{}{10}

# Crashed Hummer, pid 51, base 151000
{151000}{}{Crashed Hummer}
{151005}{}{A crashed Hummer and it's crew.}
{151010}{}{6}

# Battleground, pid 52, base 152000
{152000}{}{Battleground}
{152005}{}{This place has recently seen a battle between few Brotherhood soldiers and a group of Supermutants.}
{152010}{}{6}

# An Old Bunker, pid 53, base 153000
{153000}{}{An Old Bunker}
{153005}{}{}
{153010}{}{6}

# Prison, pid 54, base 154000
{154000}{}{Prison}
{154005}{}{A New California Republic Correctional Facility.}
{154010}{}{10}

# Train Ambush: Rail Raiders, pid 55, base 155000
{155000}{}{Train Ambush: Rail Raiders}
{155005}{}{A train ambush!}
{155010}{}{6}

# Train Ambush: Buried Rails, pid 56, base 156000
{156000}{}{Train Ambush: Buried Rails}
{156005}{}{The rails have been buried by rubble piles!}
{156010}{}{24}

# Khan Mountains, pid 57, base 157000
{157000}{}{Khan Mountains}
{157005}{}{}
{157010}{}{6}

# Khan Mountains, pid 58, base 158000
{158000}{}{Khan Mountains}
{158005}{}{}
{158010}{}{6}

# Khan Mountains, pid 59, base 159000
{159000}{}{Khan Mountains}
{159005}{}{}
{159010}{}{6}

# Khan Desert, pid 60, base 160000
{160000}{}{Khan Desert}
{160005}{}{}
{160010}{}{6}

# NCR LA Gold Reserve, pid 61, base 161000
{161000}{}{NCR LA Gold Reserve}
{161005}{}{A strash of the NCRs national gold reserve in the Angel's Boneyard.}
{161010}{}{6}

# Industrial Park, pid 62, base 162000
{162000}{}{Industrial Park}
{162005}{}{Lots of empty and locked warehouses can be found in the industrial park.}
{162010}{}{6}

# Cathedral Basement, pid 63, base 163000
{163000}{}{Cathedral Basement}
{163005}{}{The cathedral cellar.}
{163010}{}{6}

# Mutants Hideout, pid 64, base 164000
{164000}{}{Mutants Hideout}
{164005}{}{A cavern hideout in the mountains. It's occupied by a group of Super Mutant Remnants.}
{164010}{}{6}

# SanFran Subway, pid 65, base 165000
{165000}{}{SanFran Subway}
{165005}{}{}
{165010}{}{6}

# Hub Trainyard, pid 66, base 166000
{166000}{}{Hub Trainyard}
{166005}{}{}
{166010}{}{6}

# Eventlocation 2, pid 67, base 167000
{167000}{}{Eventlocation 2}
{167005}{}{}
{167010}{}{12}

# Brahmin Willow, pid 68, base 168000
{168000}{}{Brahmin Willow}
{168005}{}{A brahmin willow from the Westin ranch.}
{168010}{}{6}

# Tobacco Farm, pid 69, base 169000
{169000}{}{Tobacco Farm}
{169005}{}{An abandoned tobacco farm with wild growing plants, occupying the ruined city streets.}
{169010}{}{6}

# Radscorpion Cave, pid 70, base 170000
{170000}{}{Radscorpion Cave}
{170005}{}{Behind a bunch of junked cars you can see a small entrance into the mountain...}
{170010}{}{6}

# Safe House, pid 71, base 171000
{171000}{}{Safe House}
{171005}{}{}
{171010}{}{6}

# Safe House, pid 72, base 172000
{172000}{}{Safe House}
{172005}{}{}
{172010}{}{6}

# Safe House, pid 73, base 173000
{173000}{}{Safe House}
{173005}{}{}
{173010}{}{6}

# Safe House, pid 74, base 174000
{174000}{}{Safe House}
{174005}{}{}
{174010}{}{6}

# Cave HQ, pid 75, base 175000
{175000}{}{Cave HQ}
{175005}{}{}
{175010}{}{6}

# Building Site, pid 76, base 176000
{176000}{}{Building Site}
{176005}{}{}
{176010}{}{6}

# Blocker Location, pid 77, base 177000
{177000}{}{Blocker Location}
{177005}{}{}
{177010}{}{24}

# Brahmin Ranch, pid 78, base 178000
{178000}{}{Brahmin Ranch}
{178005}{}{A brahmin ranch waiting for herd to be delivered.}
{178010}{}{6}

# Ruined Military Base, pid 79, base 179000
{179000}{}{Ruined Military Base}
{179005}{}{An abandoned military bunker. You can see the big gates from the distance.}
{179010}{}{12}

# Dead Body, pid 80, base 180000
{180000}{}{Dead Body}
{180005}{}{You see a dead body under a tree.}
{180010}{}{24}

# Ocean 1, pid 81, base 181000
{181000}{}{Ocean 1}
{181005}{}{The wide, dirty ocean.}
{181010}{}{24}

# Old Warehouse, pid 82, base 182000
{182000}{}{Old Warehouse}
{182005}{}{Old warehouse, perhaps there is still something valuable inside.}
{182010}{}{6}

# Old Factory, pid 83, base 183000
{183000}{}{Old Factory}
{183005}{}{}
{183010}{}{6}

# Tent in the Wasteland, pid 84, base 184000
{184000}{}{Tent in the Wasteland}
{184005}{}{A tent, it seems like some people are living there.}
{184010}{}{6}

# Hospital, pid 85, base 185000
{185000}{}{Hospital}
{185005}{}{}
{185010}{}{6}

# Abandoned Farmhouse, pid 86, base 186000
{186000}{}{Abandoned Farmhouse}
{186005}{}{A small, rat-ridden farm.}
{186010}{}{6}

# Bus Stop, pid 87, base 187000
{187000}{}{Bus Stop}
{187005}{}{A bus stop on the highway.}
{187010}{}{6}

# Ghost Town, pid 88, base 188000
{188000}{}{Ghost Town}
{188005}{}{Ghost Town, a place of weeping and pking.}
{188010}{}{18}
{188020}{}{art\intrface\Twnmap05.frm}
{188030}{}{art\intrface\Wm_05.frm}
{188090}{}{2}
{188101}{}{North West}
{188102}{}{65}
{188103}{}{220}
{188111}{}{North East}
{188112}{}{334}
{188113}{}{184}

# Seven Famillies, pid 89, base 189000
{189000}{}{Seven Famillies}
{189005}{}{A small village on the desert.}
{189010}{}{12}
{189020}{}{art\intrface\Twnmap02.frm}
{189030}{}{art\intrface\Wm_02.frm}
{189090}{}{2}
{189101}{}{Village entrance}
{189102}{}{218}
{189103}{}{326}
{189111}{}{Back of the village}
{189112}{}{216}
{189113}{}{59}

# Desert 1, pid 101, base 201000
{201000}{}{Desert 1}
{201005}{}{}
{201010}{}{6}

# Desert 2, pid 102, base 202000
{202000}{}{Desert 2}
{202005}{}{}
{202010}{}{6}

# Desert 3, pid 103, base 203000
{203000}{}{Desert 3}
{203005}{}{}
{203010}{}{6}

# Desert 4, pid 104, base 204000
{204000}{}{Desert 4}
{204005}{}{}
{204010}{}{6}

# Desert 5, pid 105, base 205000
{205000}{}{Desert 5}
{205005}{}{}
{205010}{}{6}

# Desert 6, pid 106, base 206000
{206000}{}{Desert 6}
{206005}{}{}
{206010}{}{6}

# Desert Tree 1, pid 107, base 207000
{207000}{}{Desert Tree 1}
{207005}{}{}
{207010}{}{6}

# Desert Tree 2, pid 108, base 208000
{208000}{}{Desert Tree 2}
{208005}{}{}
{208010}{}{6}

# Desert Tree 3, pid 109, base 209000
{209000}{}{Desert Tree 3}
{209005}{}{}
{209010}{}{6}

# Desert Tree 4, pid 110, base 210000
{210000}{}{Desert Tree 4}
{210005}{}{}
{210010}{}{6}

# Desert Tree 5, pid 111, base 211000
{211000}{}{Desert Tree 5}
{211005}{}{}
{211010}{}{6}

# Desert Tree 6, pid 112, base 212000
{212000}{}{Desert Tree 6}
{212005}{}{}
{212010}{}{6}

# Highway 1, pid 113, base 213000
{213000}{}{Highway 1}
{213005}{}{}
{213010}{}{6}

# Highway 2, pid 114, base 214000
{214000}{}{Highway 2}
{214005}{}{}
{214010}{}{6}

# Mountain 1, pid 121, base 221000
{221000}{}{Mountain 1}
{221005}{}{}
{221010}{}{6}

# Mountain 2, pid 122, base 222000
{222000}{}{Mountain 2}
{222005}{}{}
{222010}{}{6}

# Mountain 3, pid 123, base 223000
{223000}{}{Mountain 3}
{223005}{}{}
{223010}{}{6}

# Mountain 4, pid 124, base 224000
{224000}{}{Mountain 4}
{224005}{}{}
{224010}{}{6}

# Mountain 5, pid 125, base 225000
{225000}{}{Mountain 5}
{225005}{}{}
{225010}{}{6}

# Mountain 6, pid 126, base 226000
{226000}{}{Mountain 6}
{226005}{}{}
{226010}{}{6}

# Mountain 7, pid 127, base 227000
{227000}{}{Mountain 7}
{227005}{}{}
{227010}{}{6}

# Mountain 8, pid 128, base 228000
{228000}{}{Mountain 8}
{228005}{}{}
{228010}{}{6}

# Mountain 9, pid 129, base 229000
{229000}{}{Mountain 9}
{229005}{}{}
{229010}{}{6}

# Cavern 0, pid 140, base 240000
{240000}{}{Cavern 0}
{240005}{}{}
{240010}{}{6}

# Cavern 1, pid 141, base 241000
{241000}{}{Cavern 1}
{241005}{}{}
{241010}{}{6}

# Cavern 2, pid 142, base 242000
{242000}{}{Cavern 2}
{242005}{}{}
{242010}{}{6}

# Cavern 3, pid 143, base 243000
{243000}{}{Cavern 3}
{243005}{}{}
{243010}{}{6}

# Cavern 4, pid 144, base 244000
{244000}{}{Cavern 4}
{244005}{}{}
{244010}{}{6}

# Cavern 5, pid 145, base 245000
{245000}{}{Cavern 5}
{245005}{}{}
{245010}{}{6}

# Cavern 6, pid 146, base 246000
{246000}{}{Cavern 6}
{246005}{}{}
{246010}{}{6}

# City 1, pid 161, base 261000
{261000}{}{City 1}
{261005}{}{}
{261010}{}{6}

# City 2, pid 162, base 262000
{262000}{}{City 2}
{262005}{}{}
{262010}{}{6}

# City 3, pid 163, base 263000
{263000}{}{City 3}
{263005}{}{}
{263010}{}{6}

# City 4, pid 164, base 264000
{264000}{}{City 4}
{264005}{}{}
{264010}{}{6}

# City 5, pid 165, base 265000
{265000}{}{City 5}
{265005}{}{}
{265010}{}{6}

# City 6, pid 166, base 266000
{266000}{}{City 6}
{266005}{}{}
{266010}{}{6}

# City 7, pid 167, base 267000
{267000}{}{City 7}
{267005}{}{}
{267010}{}{6}

# City 8, pid 168, base 268000
{268000}{}{City 8}
{268005}{}{}
{268010}{}{6}

# City 9, pid 169, base 269000
{269000}{}{City 9}
{269005}{}{}
{269010}{}{6}

# City 10, pid 170, base 270000
{270000}{}{City 10}
{270005}{}{}
{270010}{}{6}

# City 11, pid 171, base 271000
{271000}{}{City 11}
{271005}{}{}
{271010}{}{6}

# City 12, pid 172, base 272000
{272000}{}{City 12}
{272005}{}{}
{272010}{}{6}

# Skyscraper 1, pid 175, base 275000
{275000}{}{Skyscraper 1}
{275005}{}{}
{275010}{}{6}

# Skyscraper 2, pid 176, base 276000
{276000}{}{Skyscraper 2}
{276005}{}{}
{276010}{}{6}

# Skyscraper 3, pid 177, base 277000
{277000}{}{Skyscraper 3}
{277005}{}{}
{277010}{}{6}

# Skyscraper 4-1, pid 179, base 279000
{279000}{}{Skyscraper 4-1}
{279005}{}{}
{279010}{}{6}

# Skyscraper 5, pid 180, base 280000
{280000}{}{Skyscraper 5}
{280005}{}{}
{280010}{}{6}

# Coast 1, pid 181, base 281000
{281000}{}{Coast 1}
{281005}{}{}
{281010}{}{6}

# Coast 2, pid 182, base 282000
{282000}{}{Coast 2}
{282005}{}{}
{282010}{}{6}

# Coast 3, pid 183, base 283000
{283000}{}{Coast 3}
{283005}{}{}
{283010}{}{6}

# Coast 4, pid 184, base 284000
{284000}{}{Coast 4}
{284005}{}{}
{284010}{}{6}

# Coast 5, pid 185, base 285000
{285000}{}{Coast 5}
{285005}{}{}
{285010}{}{6}

# City Coast 1, pid 186, base 286000
{286000}{}{City Coast 1}
{286005}{}{}
{286010}{}{6}

# City Coast 2, pid 187, base 287000
{287000}{}{City Coast 2}
{287005}{}{}
{287010}{}{6}

# Coast 8, pid 188, base 288000
{288000}{}{Coast 8}
{288005}{}{}
{288010}{}{6}

# Outpost, pid 202, base 302000
{302000}{}{Outpost}
{302005}{}{A big-sized base with a house and temporary walls.}
{302010}{}{6}

# Cabin, pid 203, base 303000
{303000}{}{Cabin}
{303005}{}{A medium-sized base with a house and a few tents.}
{303010}{}{6}

# House Ruins, pid 204, base 304000
{304000}{}{House Ruins}
{304005}{}{A medium-sized building with smaller buildings around it.}
{304010}{}{6}

# Scrapheap, pid 205, base 305000
{305000}{}{Scrapheap}
{305005}{}{A medium-sized building with a lot of junk around it.}
{305010}{}{6}

# NPC Map, pid 206, base 306000
{306000}{}{NPC Map}
{306005}{}{Good luck trying to get out of here.}
{306010}{}{6}

# Secret Cave, pid 207, base 307000
{307000}{}{Secret Cave}
{307005}{}{A small secret cave hideout.}
{307010}{}{6}

# Old Bunker, pid 208, base 308000
{308000}{}{Old Bunker}
{308005}{}{A abandoned bunker, hidden in the mountains.}
{308010}{}{6}

# Caravans, pid 209, base 309000
{309000}{}{Caravans}
{309005}{}{}
{309010}{}{6}

# Depot, pid 210, base 310000
{310000}{}{Depot}
{310005}{}{An old car depot with its own power generator.}
{310010}{}{6}

# Tent, pid 211, base 311000
{311000}{}{Tent}
{311005}{}{A small tent in the desert.}
{311010}{}{6}

# Tent, pid 212, base 312000
{312000}{}{Tent}
{312005}{}{A small tent between mountains.}
{312010}{}{6}

# Tent, pid 213, base 313000
{313000}{}{Tent}
{313005}{}{A small tent at the coast.}
{313010}{}{6}

# Tent, pid 214, base 314000
{314000}{}{Tent}
{314005}{}{A small tent in the city.}
{314010}{}{6}

# Farmhome, pid 220, base 320000
{320000}{}{Farmhome}
{320005}{}{A small farm in the middle of nowhere.}
{320010}{}{6}

# Stranded Tanker, pid 221, base 321000
{321000}{}{Stranded Tanker}
{321005}{}{A rusty giant stranded at the coastline.}
{321010}{}{6}

# Rail Line Gang, pid 222, base 322000
{322000}{}{Rail Line Gang}
{322005}{}{The camping place of the Horatius rail line gang.}
{322010}{}{6}

# Lost Hills Outpost, pid 223, base 323000
{323000}{}{Lost Hills Outpost}
{323005}{}{On a edge between the mountains, you can see a small shining light.}
{323010}{}{6}

# Hideout, pid 224, base 324000
{324000}{}{Hideout}
{324005}{}{A small camp fire is burning in the distance.}
{324010}{}{6}

# Secret Shelter, pid 225, base 325000
{325000}{}{Secret Shelter}
{325005}{}{A small hidden bomb shelter.}
{325010}{}{6}

# Secret Treasure, pid 226, base 326000
{326000}{}{Secret Treasure}
{326005}{}{A family grave.}
{326010}{}{6}

# Ambush!, pid 227, base 327000
{327000}{}{Ambush!}
{327005}{}{}
{327010}{}{6}

# Abandoned Howitzer, pid 228, base 328000
{328000}{}{Abandoned Howitzer}
{328005}{}{Abandoned Howitzer}
{328010}{}{6}

# Woods, pid 230, base 330000
{330000}{}{Woods}
{330005}{}{}
{330010}{}{6}

# Crashed Vertibird Water, pid 240, base 340000
{340000}{}{Crashed Vertibird Water}
{340005}{}{}
{340010}{}{6}

# Crashed Vertibird Desert, pid 241, base 341000
{341000}{}{Crashed Vertibird Desert}
{341005}{}{}
{341010}{}{6}

# Crashed Vertibird City, pid 242, base 342000
{342000}{}{Crashed Vertibird City}
{342005}{}{}
{342010}{}{6}

# Crashed Vertibird Mountain, pid 243, base 343000
{343000}{}{Crashed Vertibird Mountain}
{343005}{}{}
{343010}{}{6}

# Crashed Vertibird Coast, pid 244, base 344000
{344000}{}{Crashed Vertibird Coast}
{344005}{}{}
{344010}{}{6}

# Gasstation Camp, pid 245, base 345000
{345000}{}{Gasstation Camp}
{345005}{}{A small-sized base with a house and temporary tents.}
{345010}{}{6}

# Trapper Camp, pid 246, base 346000
{346000}{}{Trapper Camp}
{346005}{}{A small-sized tent camp with fireplaces.}
{346010}{}{6}

# Slaverun 1, pid 271, base 371000
{371000}{}{Slaverun 1}
{371005}{}{A tribal camp}
{371010}{}{6}

# Slaverun 2, pid 272, base 372000
{372000}{}{Slaverun 2}
{372005}{}{A tribal camp}
{372010}{}{6}

# Slaverun 3, pid 273, base 373000
{373000}{}{Slaverun 3}
{373005}{}{A resting caravan}
{373010}{}{6}

# Slaverun 4, pid 274, base 374000
{374000}{}{Slaverun 4}
{374005}{}{A small farm}
{374010}{}{6}

# Slaverun 5, pid 275, base 375000
{375000}{}{Slaverun 5}
{375005}{}{A highway gas station}
{375010}{}{6}

# Slaverun 6, pid 276, base 376000
{376000}{}{Slaverun 6}
{376005}{}{A house full of junkies}
{376010}{}{6}

# Jail, pid 280, base 380000
{380000}{}{Jail}
{380005}{}{You are trapped here. Damn!}
{380010}{}{6}

# Desert 7, pid 300, base 400000
{400000}{}{Desert 7}
{400005}{}{}
{400010}{}{6}

# Desert 8, pid 301, base 401000
{401000}{}{Desert 8}
{401005}{}{}
{401010}{}{6}

# Desert 9, pid 302, base 402000
{402000}{}{Desert 9}
{402005}{}{}
{402010}{}{6}

# Desert 10, pid 303, base 403000
{403000}{}{Desert 10}
{403005}{}{}
{403010}{}{6}

# Desert 11, pid 304, base 404000
{404000}{}{Desert 11}
{404005}{}{}
{404010}{}{6}

# Necro 1, pid 305, base 405000
{405000}{}{Necro 1}
{405005}{}{}
{405010}{}{6}

# Necro 2, pid 306, base 406000
{406000}{}{Necro 2}
{406005}{}{}
{406010}{}{6}

# Necro 3, pid 307, base 407000
{407000}{}{Necro 3}
{407005}{}{}
{407010}{}{6}

# Necro 4, pid 308, base 408000
{408000}{}{Necro 4}
{408005}{}{}
{408010}{}{6}

# Desert Rails 1, pid 309, base 409000
{409000}{}{Desert Rails 1}
{409005}{}{}
{409010}{}{6}

# Desert Rails 2, pid 310, base 410000
{410000}{}{Desert Rails 2}
{410005}{}{}
{410010}{}{6}

# Desert Water 1, pid 311, base 411000
{411000}{}{Desert Water 1}
{411005}{}{}
{411010}{}{6}

# Desert Water 2, pid 312, base 412000
{412000}{}{Desert Water 2}
{412005}{}{}
{412010}{}{6}

# Desert Water 3, pid 313, base 413000
{413000}{}{Desert Water 3}
{413005}{}{}
{413010}{}{6}

# Desert 12, pid 314, base 414000
{414000}{}{Desert 12}
{414005}{}{}
{414010}{}{6}

# Tipperary, pid 349, base 449000
{449000}{}{Tipperary}
{449005}{}{}
{449010}{}{6}

# Warzone, pid 350, base 450000
{450000}{}{Warzone}
{450005}{}{An old gas station, much junk, dead bodies all around. This ain't be a good place.}
{450010}{}{12}

# Warzone, pid 351, base 451000
{451000}{}{Warzone}
{451005}{}{The ruins of the past, the ash is still in the air. Today, this place will burn again...}
{451010}{}{12}

# San Francisco Train Station, pid 352, base 452000
{452000}{}{San Francisco Train Station}
{452005}{}{A busy train station, which can be used for fast traveling to various places.}
{452010}{}{9}

# Boneyard Train Station, pid 353, base 453000
{453000}{}{Boneyard Train Station}
{453005}{}{An old train station, controlled by the Regulators of Adytum and Boneyard. The train station can be used for fast traveling to various places.}
{453010}{}{9}

# NCR Train Station, pid 354, base 454000
{454000}{}{NCR Train Station}
{454005}{}{A NCR outpost with active train station that can be used for fast traveling to various places.}
{454010}{}{9}

# Vault City Train Station, pid 355, base 455000
{455000}{}{Vault City Train Station}
{455005}{}{One of the first new train stations in the north. The train station can be used for fast traveling to various places.}
{455010}{}{9}

# Junkyard, pid 356, base 456000
{456000}{}{Junkyard}
{456005}{}{A small and old junkyard. You can see the stacked cars already from far away.}
{456010}{}{6}

# Spawnpoint 1, pid 357, base 457000
{457000}{}{Spawnpoint 1}
{457005}{}{A place in the dirt.}
{457010}{}{6}

# Spawnpoint 2, pid 358, base 458000
{458000}{}{Spawnpoint 2}
{458005}{}{A place in the dirt.}
{458010}{}{6}

# Spawnpoint 3, pid 359, base 459000
{459000}{}{Spawnpoint 3}
{459005}{}{A place in the dirt.}
{459010}{}{6}

# Ant Lair, pid 360, base 460000
{460000}{}{Ant Lair}
{460005}{}{A place in the dirt.}
{460010}{}{6}

# Themepark, pid 361, base 461000
{461000}{}{Themepark}
{461005}{}{A part of an old and abandoned themepark.}
{461010}{}{6}

# Waterworks, pid 362, base 462000
{462000}{}{Waterworks}
{462005}{}{An abandoned industrial facility for water purification.}
{462010}{}{6}

# Klamath Toxic Caves, pid 363, base 463000
{463000}{}{Klamath Toxic Caves}
{463005}{}{A radioactive cave inhabited by Geckos.}
{463010}{}{6}

# Gordon's Gas Station, pid 364, base 464000
{464000}{}{Gordon's Gas Station}
{464005}{}{A small gas station in the middle of the desert.}
{464010}{}{6}

# Quarry, pid 365, base 465000
{465000}{}{Quarry}
{465005}{}{A well guarded quarry, run by the Junktown town folks.}
{465010}{}{6}

# Mountain Passage, pid 366, base 466000
{466000}{}{Mountain Passage}
{466005}{}{A small pathway through the mountains.}
{466010}{}{6}

# Slaver Camp, pid 367, base 467000
{467000}{}{Slaver Camp}
{467005}{}{A hidden slaver breakpoint.}
{467010}{}{8}

# Fort Seth, pid 368, base 468000
{468000}{}{Fort Seth}
{468005}{}{A military outpost of the NCR, composed of a few barracks and protective walls.}
{468010}{}{6}

#
# Worldmap Encounter messages
#

# message (ugly hack:P)
{10000000}{}{You encounter: @lex str1@}
{10000001}{}{You encounter: @lex str1@}
{10000002}{}{You encounter: @lex str1@@lex str2@}
{10000003}{}{You encounter: @lex str1@@lex str2@@lex str3@}
{10000004}{}{You encounter: @lex str1@@lex str2@@lex str3@@lex str4@}
{10000005}{}{You encounter: @lex str1@@lex str2@@lex str3@@lex str4@@lex str5@}
{10000006}{}{You encounter: @lex str1@@lex str2@@lex str3@@lex str4@@lex str5@@lex str6@}
{10000007}{}{You encounter: @lex str1@@lex str2@@lex str3@@lex str4@@lex str5@@lex str6@@lex str7@}
{10000008}{}{You encounter: @lex str1@@lex str2@@lex str3@@lex str4@@lex str5@@lex str6@@lex str7@@lex str8@}
{10000009}{}{You encounter: @lex str1@@lex str2@@lex str3@@lex str4@@lex str5@@lex str6@@lex str7@@lex str8@@lex str9@}

{10000010}{}{Do you wish to encounter: @lex str1@}
{10000011}{}{Do you wish to encounter: @lex str1@}
{10000012}{}{Do you wish to encounter: @lex str1@@lex str2@}
{10000013}{}{Do you wish to encounter: @lex str1@@lex str2@@lex str3@}
{10000014}{}{Do you wish to encounter: @lex str1@@lex str2@@lex str3@@lex str4@}
{10000015}{}{Do you wish to encounter: @lex str1@@lex str2@@lex str3@@lex str4@@lex str5@}
{10000016}{}{Do you wish to encounter: @lex str1@@lex str2@@lex str3@@lex str4@@lex str5@@lex str6@}
{10000017}{}{Do you wish to encounter: @lex str1@@lex str2@@lex str3@@lex str4@@lex str5@@lex str6@@lex str7@}
{10000018}{}{Do you wish to encounter: @lex str1@@lex str2@@lex str3@@lex str4@@lex str5@@lex str6@@lex str7@@lex str8@}
{10000019}{}{Do you wish to encounter: @lex str1@@lex str2@@lex str3@@lex str4@@lex str5@@lex str6@@lex str7@@lex str8@@lex str9@}

# count (prefix) TODO
{10000020}{}{a small group of }
{10000021}{}{a group of }

# action
{10000030}{}{fighting }
{10000131}{}{fending off}

#
# New encounters 20000000 + <group>
#

{20000000}{}{Raiders}
{20000001}{}{Radscorpions}
{20000002}{}{Giant rats}
{20000003}{}{Merchant party}
{20000004}{}{Mantis}
{20000005}{}{Deathclaws}
{20000006}{}{Geckos}
{20000007}{}{Molerats}
{20000008}{}{Pigrats}
{20000009}{}{Dogs}
{20000010}{}{Brahmins}
{20000011}{}{Rats}
{20000012}{}{Pigrats}
{20000013}{}{Small Radscorpions}
{20000014}{}{Silver Geckos}
{20000015}{}{Spore Plants}
{20000016}{}{Hunting party}
{20000017}{}{War party}
{20000018}{}{Cannibals}
{20000019}{}{Outcasts}
{20000020}{}{Holy people}
{20000021}{}{Nomads}
{20000022}{}{Molerats}
{20000023}{}{Geckos}
{20000024}{}{Trappers}
{20000025}{}{Bandits}
{20000026}{}{Homeless people}
{20000027}{}{Farmers}
{20000028}{}{Golden Geckos}
{20000029}{}{Caravan}
{20000030}{}{Scorpions}
{20000031}{}{Molerats and Pigrats}
{20000032}{}{Caravan}
{20000033}{}{Robbers}
{20000034}{}{Highwaymen}
{20000035}{}{Golden Geckos}
{20000036}{}{Radscorpions}
{20000037}{}{Slavers}
{20000038}{}{Slave run}
{20000039}{}{Slaves}
{20000040}{}{Rave party}
{20000041}{}{Molerats}
{20000042}{}{Moonshiners}
{20000043}{}{Wild Brahmins}
{20000044}{}{Mantis}
{20000045}{}{Robbers}
{20000046}{}{Highwaymen}
{20000047}{}{Wild dogs}
{20000048}{}{Swarm of Mantis}
{20000049}{}{Caravan}
{20000050}{}{Trader}
{20000051}{}{Mutated Molerats}
{20000052}{}{Mutated Pigrats}
{20000053}{}{Lone Wanderer}
{20000054}{}{Vault City patrol}
{20000055}{}{Strong Slavers}
{20000056}{}{Ghoul Crazies}
{20000057}{}{Crazies}
{20000058}{}{Ghoul Scavengers}
{20000059}{}{Scavengers}
{20000060}{}{Mutated Rats}
{20000061}{}{Geckos}
{20000062}{}{Fishermen}
{20000063}{}{Wilder}
{20000064}{}{Den caravan}
{20000065}{}{Vault City caravan}
{20000066}{}{New Reno caravan}
{20000067}{}{Redding caravan}
{20000068}{}{Bootlegger}
{20000069}{}{Trappers}
{20000070}{}{Prospector}
{20000071}{}{Claim jumper}
{20000072}{}{Wolves}
{20000073}{}{Homesteaders}
{20000074}{}{Broken Hills caravan}
{20000075}{}{Gecko caravan}
{20000076}{}{Raiders}
{20000077}{}{Fire geckos}
{20000078}{}{Tough Fire Geckos}
{20000079}{}{Aliens}
{20000080}{}{Tough Aliens}
{20000081}{}{Deathclaws}
{20000082}{}{Centaurs}
{20000083}{}{Floaters}
{20000084}{}{Floaters and Centaurs}
{20000085}{}{Enclave patrol}
{20000086}{}{Mercenaries}
{20000087}{}{Elronologists}
{20000088}{}{Press Gang}
{20000089}{}{San Francisco caravan}
{20000090}{}{Unity patrol}
{20000091}{}{Rogues}
{20000092}{}{Mobsters}
{20000093}{}{Yakuza...shit!}
{20000094}{}{Gang}
{20000095}{}{Traveller}
{20000096}{}{Rangers}
{20000097}{}{Marauders}
{20000098}{}{Super Mutant remnants}
{20000099}{}{NCR caravan}
{20000100}{}{Vault 15 caravan}
{20000101}{}{Vault 15 squatters}
{20000102}{}{Bounty Hunters}
{20000103}{}{Bounty Hunters}
{20000104}{}{Bounty Hunters}
{20000105}{}{Bounty Hunters}
{20000106}{}{Bounty Hunters}
{20000107}{}{Morton brothers}
{20000108}{}{Ants}
{20000109}{}{Hub patrol}
{20000110}{}{Brotherhood patrol}
{20000111}{}{Regulators}
{20000112}{}{Salvagers}
{20000113}{}{Junktown scouts}
{20000114}{}{Desert Stalker}
{20000115}{}{Powder Ganger}
{20000116}{}{Hoover Dam caravan}
{20000117}{}{Endless Walker}
{20000118}{}{Radtoads}
{20000119}{}{Hermit}
{20000120}{}{Followers of the Apocalypse}
{20000121}{}{Farm Thug}
{20000122}{}{Outcasted Trappers}
{20000123}{}{Spiked Fists}
{20000124}{}{Bloodbeasts}
{20000125}{}{Irwine Jules Ganger}
{20000126}{}{Mad Dogs}
{20000127}{}{Hell Razors}
{20000128}{}{Desert Hounds}
{20000129}{}{Jackals}
{20000130}{}{Vipers}
{20000131}{}{NCR Army}
{20000132}{}{80s}
{20000133}{}{Brotherhood Initiate Patrol}
{20000134}{}{The what?}
