# Created on 17.10.2007 Cvet  

#
#
#

{4}{}{%d. }
{5}{}{Current progress: }

#
# Number
# Name
#

#
# Number formula:
#	VariableId * 1000 + Value (1-100) - The text that appears at a given value of the variable (current objective).
#	VariableId * 1000 + 101 - Name of quest tab.
#	VariableId * 1000 + 102 - Permanent quest description.

#=======================================
# 6001
# Raiders induction quest
#=======================================
{6001001}{}{Metzger pointed me to his business contact, Stokes. Stokes is said to spend his time in The Hole.}
{6001002}{}{Stokes told me to visit the Khans' southern outpost and talk to Raynes, the local leader.}
{6001003}{}{Deal with the renegade raider.}
{6001101}{}{Den: Join the raiders}
{6001102}{}{Join the raiders}

#=======================================
# 6111
# NCR, pick up a few smokes for buster
#=======================================
{6111001}{}{Buster wants me to buy him some cigarettes from the Rawhide.}
{6111002}{}{I have to return the cigarettes to Buster.}
#{6111003}{}{Quest Completed.}
{6111003}{}{I've given the cigarettes to Buster.

:: Quest Completed ::}
{6111101}{}{NCR: Buy cigarettes for Buster}
{6111102}{}{Buy cigarettes for Buster}

#=======================================
# 6112
# NCR, return Mira's debt
#=======================================

{6112001}{}{Mira asked me to return the debt she owes to Dusty.}
{6112002}{}{I've returned the debt. I should go back and speak to Mira.}
#{6112003}{}{Quest Completed.}
{6112003}{}{I've helped Mira return the debt.

:: Quest Completed ::}
{6112101}{}{NCR: Return Mira's debt}
{6112102}{}{Return Mira's debt}

#=======================================
# 6122
# Redding, Resupply Redding with Jet
#=======================================

{6122001}{}{There's hardly enough Jet for everyone in Redding. Dan McGrew wants me to talk to some doctor or pharmacist or something in New Reno about it.}
{6122002}{}{Renesco wants a proof there will be enough costumers in Redding for his Jet shipments, before sending another one that way.}
{6122003}{}{Doc. Johnson's list of Jet costumers in Redding could persuade Renesco there's a stable demand for Jet in Redding. I should bring it to him right away.}
{6122004}{}{Renesco is going to send more Jet to Redding. I have to let Dan McGrew know about this as soon as possible.}
{6122005}{}{The problem with Redding's Jet shipments has been solved.

::Quest Completed::}
{6122101}{}{Redding: Increase Redding's Jet supply}
{6122102}{}{Find out how to raise the current supply of Jet in Redding}

#=======================================
# 6200
# Den, repair Becky's gaming table
#=======================================

{6200001}{}{Becky asked me to repair one of her gaming tables.}
{6200002}{}{I've repaired Becky's gaming table.}
{6200003}{}{I've failed to repair Becky's table.}
{6200004}{}{Becky's table will stay broken. I couldn't fix it.

::Quest Failed::}
{6200005}{}{I've managed to repair Becky's table.

:: Quest Completed ::}
{6200101}{}{Den: Repair one of Becky's gaming tables}
{6200102}{}{Repair one of Becky's gaming tables}

#=======================================
# 7004
# Junktown, abandoned bunker
#=======================================
{7004001}{}{A scout in Junktown told me stories about an old trapper who might know some nice places to hang around.}
{7004005}{}{Got a hint that the trapper might have gone to Necropolis. I should check this out.}
{7004016}{}{The name of that trapper is Wally. Wonder where he is now...}
{7004021}{}{Finally. The ghouls say that I can find Wally at the Watershed. He has to live there somewhere.}
# Questlog deactivated for now, because it's all messed up.
#{7004101}{}{Junktown: The old trapper}
#{7004102}{}{The old trapper.}

#=======================================
# 7005
# Redding, Rats in Mines
#=======================================
{7005001}{}{In order to help Marge Le Barge in Redding with some rats in mines, I have to prove myself by taking care of a job for Caminetto, a guy hanging around in Redding's Malamute Saloon.}
{7005002}{}{Accepted to bring five Radscorpion Tales to Caminetto in Redding.}
{7005003}{}{After taking care of Caminetto's job, I got his recommendation and should talk to Marge about exterminating those rats from Redding mines.}
{7005004}{}{There was no rats in mines, ever. The whole ruckus was about getting some stuff done for Caminetto.

:: Quest Completed ::}
{7005005}{}{Never managed to get to those rats down in Redding mines. What the hell, there must be some other job for me to do now.

:: Quest Failed ::}
{7005101}{}{Redding: Rats in Mines}
{7005102}{}{Help Marge deal with rats in Redding Mines}

#=======================================
# 7008
# Hub, sad wife quest
#=======================================
{7008001}{}{There was a sad woman in the Hub, Oldtown. She told me she was worried about her Husband who was traveling to the Boneyard. I will keep my eyes open for him.}
{7008002}{}{Joseph really was in the Boneyard. But sadly he was hanging from a lamp post. I should go back to the woman and tell her.}
{7008003}{}{I told that woman about her husband. It's a sad day today.

:: Quest Completed ::}
{7008004}{}{I made fun of the dead man's wife and told her horrible stories. I am such a bad person.

:: Quest Completed ::}
{7008101}{}{Hub: Find Joseph, the scavenger}
{7008102}{}{Find Joseph, the scavenger}

#=======================================
#7009
#Hub, Wasteland Band
#=======================================
{7009001}{}{A peculiar man named Mick has asked me to find his friend Ronnie in Junktown and ask him to form a band. He is known to hang around the Skum Pitt, so I should start there.}
{7009002}{}{Ronnie agreed to join Mick's band. I need to report back to the Hub now.}
{7009003}{}{Mick threw me a few caps and told me I need to locate a man named Charlie, who lives somewhere in San Francisco.}
{7009004}{}{Charlie made my job easy. Back to the Hub to see if Mick needs anything else}
{7009005}{}{Mick swears this is the last one. All I have to do is convince Keith in Gecko to join, and my job is done.}
{7009006}{}{Keith was a pain in the ass, but I've done it. Time to tell Mick the good news.}

:: Quest Completed ::}
{7009007}{}{I've assembled the band, Mick is happy, and I've been paid.

:: Quest Completed ::}
{7009101}{}{Hub: Wasteland Band}
{7009102}{}{Assemble the Band}

#=======================================
# 7011
# NCR, Spawn Quest
#=======================================
{7011001}{}{Man, what a night. I barely survived the horrific sand storm yesterday by taking cover in an old mining pit. When I was crawling back to the surface I met a lone man called Feelslong who lives in this area. He asked me to deliver a message to someone named Harris. Harris should be in the Rawhide Saloon... like always.}
{7011002}{}{I've delivered the message, my job is done. Who knows, maybe I will meet Feelslong again some day...

:: Quest Completed ::}
{7011101}{}{NCR: The Message}
{7011102}{}{The Message}

#=======================================
# 7013
# NCR, Horatius Rail Line Gang
#=======================================
{7013001}{}{Feargus in the foreroom told me, Gunther might have a special job for me...}
{7013002}{}{I've got the job to take care of a rail line gang that is located to the north east of the NCR. Could be a hot job, maybe I should get some backup for myself.}
{7013003}{}{The gang leader, called Horatius, is dead.}
{7013004}{}{The rail line gang will leave this place. It was a non-violent resolution.}
{7013005}{}{I killed all of the gang members. Now they will not be a problem again.}
{7013010}{}{I've reported back to Gunther.}
{7013011}{}{Feargus gave me my reward and with this, the job is done.

:: Quest Completed ::}
{7013012}{}{Someone else took care of the rail line gang. Seems like I was too late.

:: Quest Failed ::}
{7013101}{}{NCR: The Rail Line Gang}
{7013102}{}{The Rail Line Gang}

#=======================================
# 7017
# Boneyard Train Station, CoC Administrator
#=======================================
{7017001}{}{A member from the Children of the Cathedral told me that someone from the Boneyard train station administration might have some work for me.}
{7017002}{}{One of the Boneyard Train Station administrators wants me to bring him a new Deans Electronics book.}
{7017003}{}{I delivered the book and job is done. That's how it runs.

:: Quest Completed ::}
{7017101}{}{Boneyard: Get a Deans Electronics book}
{7017102}{}{Get a Deans Electronics book}

#=======================================
# 7018
# Vault City, Medical Investigation
#=======================================
{7018001}{}{Doctor Andrew in Vault City gave me an interesting job. He told me about the New Californian Republic rail line and where I can find the next closest train station. From there I should start asking everyone if they are ill or know someone who is ill. After that, I have to report back to doctor Andrew. I guess talking to four people in each station should be enough...}
{7018002}{}{It seems like the people at the San Francisco station are seriously ill. Feels like a pandemic is spreading around. I should report back to doctor Andrew.}
{7018003}{}{The people at the Boneyard train station are not in the best condition, but beside this, all seems normal. I should report back to doctor Andrew.}
{7018004}{}{At the NCR train station, everyone seems to be in good condition. I should report back to doctor Andrew.}
{7018005}{}{After talking to the people at the Vault City train station, it seems clear that everything is okay. I should report back to doctor Andrew.}
{7018006}{}{It took me some time, but I've reported back the status of every available train station. With this, my job is done.

:: Quest Completed ::}
{7018101}{}{Vault City: Medical Investigation}
{7018102}{}{Medical Investigation}

#=======================================
# 7019
# Boneyard, A Man's Job
#=======================================
{7019001}{}{Hammilton, quite a busy man in the Library of the Followers of the Apocalypse, gave me a job, where one "has to be a tough motherfucker", as he said. I have to find a middle-aged man in leather armor with a black bull painted on it. Hammilton said it's one of his... workers. He wants me to find and kill him. I should ask around at the train stations. Maybe someone saw him there.}
{7019002}{}{Someone told me that I should check out a shady man in leather jacket at the NCR train station. He should know more about my target...}
{7019003}{}{I've talked to the leather jacket man at the NCR train station. He told me where to find my target. The man is hiding somewhere between the mountains, west of the NCR.}
{7019004}{}{The man in the leather armor with the black bull on it is dead. My job here is done. Guess I should report back to Hammilton for my reward.}
{7019007}{}{I decided not to kill Greg. I doubt Hammilton will be very happy about it... Maybe I should try to lie about this.}
{7019009}{}{I've killed Gregs daughter. I am a goddamn motherfucker.}

{7019010}{}{Frisco done}
{7019011}{}{LA done}
{7019012}{}{NCR done}
{7019013}{}{VC done}
{7019014}{}{I reported back to Hammilton and got my reward. It's good to be done with a Man's job.

:: Quest Completed ::}
{7019015}{}{I've told Hammilton that I didn't kill the man. He wasn't very happy to hear this and I'll guess I can count on future activity from his side.

:: Quest Completed ::}
{7019016}{}{I needed too much time. The target could be through the mountains already and is now impossible to find.

:: Quest Failed ::}
{7019101}{}{Boneyard: A Man's Job}
{7019102}{}{A Man's Job}

#=======================================
# 7021
# Frisco ant lair quest
#=======================================
{7021001}{}{Doctor Wong gave me the task to smoke out the ant lair in the north east of San Francisco.}
{7021002}{}{I've killed all ants. I should go back to Doctor Wong for my reward.}
{7021003}{}{The ant lair is dead and I got my reward from Doctor Wong. He also said that I can check back later, if I want to kill some more ants...}
{7021101}{}{San Francisco: It came from the desert}
{7021102}{}{It came from the desert}

#=======================================
# 7031
# Gecko, Spawn Quest
#=======================================
{7031001}{}{Man, what a night. I barely survived the horrific sand storm yesterday by taking cover in an old rotten building. When I was crawling back to the surface I met a ghoul caravan which was on its way back to a town called Gecko. One of the ghouls, Leeroy, asked me to deliver a message to a woman in Vault City. He told me to talk to a woman with pretty obvious hair in the local bar.}
{7031002}{}{I've delivered the message, my job is done. Who knows, maybe I will meet Leeroy again some day...

:: Quest Completed ::}
{7031005}{}{Man, what a night. I barely survived the horrific sand storm yesterday by taking cover in an old rotten building. When I was crawling back to the surface I met a ghoul caravan which was on its way back to a town called Gecko. I've pissed off one of the ghouls. His name was Leeroy. Maybe I should say sorry...}
{7031101}{}{Gecko: The Vault City Contact}
{7031102}{}{The Vault City Contact}

#=======================================
# 7032
# Hub, Spawn Quest
#=======================================
{7032001}{}{Man, what a night. I barely survived the horrific sand storm yesterday by taking cover in a sand hole under an old tent. When I was crawling back to the surface I met a big caravan that was on its way to the Hub, a big trade center in this area. The caravan leader asked me to be a messenger for them. I should go to the Far Go Traders and tell them that the caravan will need some more time.}
{7032002}{}{I've delivered the message, my job is done. Who knows, maybe I will meet the caravan folks again some day...

:: Quest Completed ::}
{7032101}{}{Hub: Far Go Scout}
{7032102}{}{Far Go Scout}

#=======================================
# 7036
# Klamath, Stranded Rust quest
#=======================================
{7036001}{}{I've met a stinky trapper in Klamath who told me something about a kind of stranded ship. I should bring him a metallic brief case from there. He will show me the position when I look strong enough and have some backup with me.}
{7036002}{}{The stinky trapper in Klamath want's me to bring him a metal case from an old stranded ship. He gave me the position on my PiPBoy map. I should check it out and see what I can find.}
{7036003}{}{Meloy got his metal case and with this, my job is done.

:: Quest Completed ::}
{7036004}{}{Seems like I was too slow and someone else faster than me. The metallic brief case is gone and I can't bring it back to Meloy.

:: Quest Failed ::}
{7036101}{}{Klamath: Stranded Rust}
{7036102}{}{Stranded Rust}

#=======================================
# 7042
# Boneyard, repair the waterpump
#=======================================
{7042001}{}{I've asked Montag, if I should take a look at his water pump. Maybe I can fix it.}
{7042002}{}{It was not easy, but I could fix the machine.}
{7042003}{}{Looks like I am not able to repair the water pump.}
{7042004}{}{I've reported to Montag, that I couldn't fix the water pump.

:: Quest Failed ::}
{7042005}{}{I've reported to Montag, that I've fixed the water pump.

:: Quest Completed ::}
{7042101}{}{Boneyard: Montag's Water Pump}
{7042102}{}{Montag's Water Pump}

#=======================================
# 7043
# Boneyard, Dogs of LA
#=======================================
{7043001}{}{Hendriks, one of the regulators, gave me the job to kill one of the local dog groups. He gave me the position on my PipBoy.}
{7043002}{}{I've wiped out the group of dogs. I should go back to Hendriks for my reward.}
{7043003}{}{The pack of dogs is dead and I reported back to Hendriks. I can check back later, because he is sure that there will be more work.}
{7043101}{}{Boneyard: Dogs of LA}
{7043102}{}{Dogs of LA}

#=======================================
# 7047
# Boneyard, Howitzer Shells
#=======================================
{7047001}{}{Sergeant from the scavenger camp asked me to get him some more shells for his howitzer. Jargo, the gunsmith in Adytum, is in charge of the ammunition production. I should try to convince him.}
{7047002}{}{Jargo agreed to produce some extra howitzer shells. My job is done.

:: Quest Completed ::}
{7047003}{}{Jargo doesn't want to produce extra howitzer shells, as they are too expensive. Anyway, my job is done...

:: Quest Failed ::}
{7047004}{}{I've met Sergeant again. He was pretty happy about the additional howitzer ammunition and gave me an unused train ticket.

:: Quest Completed ::}
{7047101}{}{Boneyard: Howitzer Shells}
{7047102}{}{Howitzer Shells}

#=======================================
# 7070
# Hub, Iguana Pete missing son
#=======================================
{7070001}{}{Iguana Pete is upset because he misses his son. I should visit his son in the New California Republic.}
{7070002}{}{Iguana 'Miky' told me he got his Iguana stand from a mutant at the Rawhide Saloon}
{7070003}{}{The drunk mutant was very unhelpful, he informed me that Pete's son can be found south of an area beginning with 'New' that is unsafe for mutants.}
{7070005}{}{I have visited Golgotha and discovered a fresh corpse that looks a bit like Pete. I should let Pete know.}
{7070006}{}{I found Pete's son and delivered the message. He gave me the reward himself.

:: Quest Completed ::}
{7070007}{}{I have told Pete about his dead son and received my reward. He was very upset.}

{7070101}{}{The Hub: Iguana Pete's Missing Son}
{7070102}{}{Find Iguana Pete's Missing Son}

#=======================================
# 7074
# NCR,Den, or SF
#=======================================
{7074001}{}{My first assignment as a Recruit in the Brotherhood of Steel is to collect ten radscorpion tails and return with them.}
{7074011}{}{I've turned in all of the scorpion tails.}
{7074012}{}{Now I have to scout out Navarro and investigate a 'suspicious red device.'}
{7074013}{}{I've identified the Nuka-Cola machine. The Brotherhood of Steel mystery has been solved.}
{7074014}{}{I've completed my second assignment. I now need to speak to the quartermaster.}
{7074015}{}{I've been promoted to Initiate, and I can now either deal with Eldridge's gun shipment in New Reno or investigate this Ghost Farm place.}
{7074016}{}{Ghost Farm is as it sounds. Dead. I need to report back with this information.}
{7074017}{}{An entire civilization exists under Ghost Farm. I need to report back with this information.}
{7074018}{}{Eldridge has promised to reimburse the Brotherhood for not delivering. I should report this information.}
{7074019}{}{I've helped Eldridge get his caravan rolling again. The Brotherhood will be pleased to hear this.}
{7074020}{}{I've completed my third mission and have been rewarded. I should return for my next mission.}
{7074021}{}{I now either need to help the hummer between Reno and Gordon's or the injured patrol near Mariposa.}
{7074022}{}{I spoke to Gordon and brought the parts back to the hummer.}
{7074023}{}{I was able to get the hummer on its way to Gordon without any additional delay.}
{7074024}{}{Apprentice Snyder was in pretty bad shape, but managed to get him on his feet with some meds.}
{7074025}{}{I was able to create a makeshift splint for Snyder, and his leg will heal properly now.}
{7074026}{}{I've completed my fourth mission and have again been rewarded. I should return for my next mission.}
{7074027}{}{I've been ordered to investigate a BoS bunker on lockdown near Necropolis, collect survivors, and most importantly, retrieve data from the base's main terminal.}
{7074028}{}{I was able to extract the data, but the bunker is compromised and there were no survivors. I should report to Lost Hills with this information.}

{7074101}{}{Brotherhood of Steel: Welcome to the Brotherhood}
{7074102}{}{Rise among the ranks of the Brotherhood of Steel.}

#=======================================
# 7077
# Modoc, Kill the Rancher
#=======================================
{7077001}{}{A strange looking man in Modoc has hired me to kill a rancher at his ranch nearby. The ranch is guarded so I should disguise myself as a delivery boy to gain access. He mentioned there would be a bonus if I destroy the ranch.}
{7077002}{}{I have killed the Rancher, I could report back to the man in Modoc or find a way to destroy the ranch.}
{7077003}{}{I have destroyed the ranch and killed the rancher by causing his ranch to collapse into an underground cavern. I should report to the man in Modoc.}
{7077004}{}{I have disabled the safety measures that kept the mine personnel alive. I can now investigate the mine without being harassed.}
{7077005}{}{I have reported to the man in Modoc and received my reward.

:: Quest Completed ::}
{7077101}{}{Modoc: Kill the Rancher}
{7077102}{}{Kill the Rancher}

#=======================================
# 7082
# Redding, Wilson the conman
#=======================================
{7082001}{}{A card cheat named Wilson offered me a large sum of caps if I exchange some chips for him at the local casino.}
{7082002}{}{I gave Wilson's chips to the cashier. She was sceptical as to their origins. I think I should get out of here.

:: Quest Completed ::}

{7082101}{}{Redding: Cash Wilson's chips}
{7082102}{}{Cash Wilson's chips}

#=======================================
#7091
# Raiders, MAIN QUEST
#=======================================
{7091001}{}{My first assignment as a Raider prospect is to get a beer. I should go find a beer.}
{7091002}{}{I got a beer for the raider. I should ask if he wants anything else.}
{7091003}{}{I have been given a quest to clean the toilets at the raider camp with a water bag. I should use a water bag on the toilets.}
{7091004}{}{I cleaned the toilet, I should report my success to the raider.}
{7091005}{}{My orders are to find some jimmy hats and report back to the raider.}
{7091006}{}{I delivered the jimmy hats to the raider. It sounds like I may have another important mission waiting for me.}
{7091007}{}{I have been told to investigate a cave filled with radscorpions and bring back whatever I find in the footlocker near the back.}
{7091008}{}{There was only junk in the footlocker, I should tell the raider.}
{7091009}{}{It was all a stupid joke. I have been told to report to the leader of the Raiders.}
{7091010}{}{Ren, the leader, has asked me to get rid of some farmers for him. I should make this quick.}
{7091011}{}{I killed the farmers. Ren will want to hear about this.}
{7091012}{}{Ren was happy, he told me to check in at the supply depot in the raider base.}
{7091013}{}{I need to find ten combat knives for the supply shed.}
{7091014}{}{I need to find nine combat knives for the supply shed.}
{7091015}{}{I need to find eight combat knives for the supply shed.}
{7091016}{}{I need to find seven combat knives for the supply shed.}
{7091017}{}{I need to find six combat knives for the supply shed.}
{7091018}{}{I need to find five combat knives for the supply shed.}
{7091019}{}{I need to find four combat knives for the supply shed.}
{7091020}{}{I need to find three combat knives for the supply shed.}
{7091021}{}{I need to find two combat knives for the supply shed.}
{7091022}{}{I need to find the last combat knife for the supply shed.}
{7091023}{}{I found all of the combat knives, I should ask if Lumpy wants anything else.}
{7091024}{}{Lumpy asked me to assault a rancher for her, she didn't say if I should kill him or not.}
{7091025}{}{I punched the rancher a few times, I should let Lumpy know he won't be bothering her for awhile.}
{7091026}{}{Lumpy told me to talk to Jim, the treasurer.}
{7091027}{}{Jim asked me to deliver a message to his girl in NCR.}
{7091028}{}{I delivered Jim's message. I should get back to him.}
{7091029}{}{I delivered Jim's message. I should get back to him.}
{7091030}{}{I should report to Ren.}
{7091031}{}{A man in at the Malumute in Redding is waiting for this shipment of Jet, I should hurry there.}
{7091032}{}{The Jet has been delivered. I should get back for my reward.}
{7091033}{}{I need to purchase a caravan schedule from a caravan guard in NCR.}
{7091034}{}{I got the schedule. Now to hand it over to the Raiders.}
{7091035}{}{I couldn't get the schedule. Dammnit.}
{7091036}{}{Ren told me to speak to Lumpy again.}
{7091037}{}{I have to deliver 10 Mausers to a man in the vault city bar.}
{7091038}{}{I delivered the Mausers alright, time to get my reward.}
{7091039}{}{Ren wanted to speak to me.}

{7091101}{}{Raiders: MAIN QUEST}
{7091102}{}{MAIN QUEST}

#=======================================
# 7097
# Train Ambush, Rail Raiders
#=======================================
{7097001}{}{Beginning text}
{7097002}{}{Our group managed it to kill all the Rail Raiders!

:: Quest Completed ::}
{7097003}{}{Thanks to our fearful appearance, our group managed it to scare the Rail Raiders away.

:: Quest Completed ::}
{7097004}{}{It has cost our group a lot, but money doesn't weight as much as a human life. We paid the Rail Raiders money and they went away, letting us all alive.

:: Quest Completed ::}
{7097005}{}{The skillful use of our groups diplomatic abilities saved a lot human lifes today. We managed it to talk over the Rail Raiders to leave this place.

:: Quest Completed ::}
{7097006}{}{You've been running away! text

:: Quest Failed ::}
{7097101}{}{Traim Ambush: Rail Raiders}
{7097102}{}{Rail Raiders}

#=======================================
# 7102
# Boneyard, Warehouse Rape Party :>
#=======================================
{7102001}{}{I've got the job to deliver a message to some folks in the industrial park, Boneyard westside.}
{7102002}{}{The message was a trap. A few punks showed up and wanted to rape me, but I fled from the scene.

:: Quest Completed ::}
{7102003}{}{The message was a trap. A few punks showed up and wanted to rape me, but I was able to kill them all.

:: Quest Completed ::}
{7102004}{}{The message was a trap. A few punks showed up and raped me. There was nothing I could do against it...

:: Quest Completed ::}
{7102005}{}{I didn't delivered the message to the industrial park.

:: Quest Failed ::}
{7102006}{}{The message was a trap. A few punks showed up, but ran away after a brief conversation. I am not exactly sure why, though...

:: Quest Completed ::}
{7102101}{}{Boneyard: Industrial Park Message}
{7102102}{}{Deliver the message to the Industrial Park}

#=======================================
# 7106
# Cathedral, Cellar Dwellar
#=======================================
{7106001}{}{Patrick, one of the hobos in the Cathedral, told me about a rat plague in the basement cellar of the Cathedral. It seems like the rats grow stronger and stronger over time. If nothing will be done in time, the rats will fully take over the underground.}
{7106002}{}{On the second basement floor was a glowing ghoul who most likely is the source for the mutated rats. I've killed him.}
{7106003}{}{I've killed all the mutated venus mantrap plants that I could find. This should stop them to poison the ground water.}
{7106004}{}{The cathedral cellar is cleaned up and the source of the mutated rats is exterminated.

:: Quest Completed ::}
{7106005}{}{The basement cellar has been taken over by an army of mutated rats.

:: Quest Failed ::}
{7106101}{}{Cathedral: Explore the Cathedral Cellar}
{7106102}{}{Explore the Cathedral Cellar}

#=======================================
# 7112
# Boneyard, Gun Runners Caravan
#=======================================
{7112001}{}{Marshall from the Gun Runners got a job for me, if I can get a team together of at least four people. It's about a package that has been stolen by a group of Super Mutant remnants. It's dangerous but should be worth it.}
{7112002}{}{The deal is clear: Marshall from the Gun Runners told me to bring him back the Gun Runners metal box with weapon manufacturing plans inside. The metal case is rigged with explosives, so we shouldn't touch them or it goes BOOM! He also told me that nobody else should get the package... Not the Brotherhood and not the Khans, not anyone else. 

The mutants are using some heavy weaponry- our group should prepare for that.}
{7112003}{}{The Gun Runners got their weapon manufacturing plans back. Marshall told me to visit Ralph for our payment.}
{7112004}{}{The weapon manufacturing plans have been given to the Brotherhood of Steel. They made angry faces and played assholes, but at least they paid for it.

:: Quest Completed ::}
{7112005}{}{The weapon manufacturing plans have been given to the Khans. They seemed to be very happy about it.

:: Quest Completed ::}
{7112006}{}{The Super Mutant Remnants have abandoned their hideout. If we couldn't have picked up the Gun Runners package before, it is now gone forever.}
{7112007}{}{The package is lost, quest failed.

:: Quest Failed ::}
{7112008}{}{I've got the payment from the Gun Runners, the job is done.

:: Quest Completed ::}
{7112101}{}{Boneyard: Gun Runners Caravan Package}
{7112102}{}{Gun Runners Caravan Package}

#=======================================
# 7116
# Frisco Replication, Squatter Subway
#=======================================
{7116001}{}{The San Francisco Subway Station has been taken over by radscorpions. As long as the place is occupied, the squatters can't get back to their homes. Chen told me about a lot dead people, who got poisoned or killed by the scorpions while trying to exterminate them.}
{7116002}{}{Taking things into my own hands: I told Chen that I will check out the subway and get rid of the radscorpions.}
{7116003}{}{The radscorpion family in the subway tunnels is dead. I should head back to Chen for my reward.}
{7116004}{}{The subway tunnels are clear to go again and Chen gave me my reward.

:: Quest Completed ::}
{7116005}{}{The radscorpion family was growing bigger over time and occupied all subway tunnels. Without a heavily armed force, it will not be possible anymore to get rid of them.

:: Quest Failed ::}

{7116101}{}{San Francisco: Radscorpion Subway}
{7116102}{}{Radscorpion Subway}

#=======================================
# 7120
# Hub, Water Merchant Contracts
#=======================================
{7120001}{}{The independent merchants in the Hub have to pay high taxes on given out water galons to the Water Merchants. I could try and setup new terms for their contracts.}
{7120002}{}{I haven't been able to negotiate a new discussion about the contracts between the independent merchants and the Water Merchants.

:: Quest Completed ::}
{7120003}{}{I could negotiate a new discussion about the contracts between the independent merchants and the Water Merchants for the next conference of the Hub's Central Council.

:: Quest Completed ::}

{7120101}{}{Hub: Water Merchant Contracts}
{7120102}{}{Water Merchant Contracts}

#=======================================
# 7122
# Junktown, Optimize the power house
#=======================================
{7122001}{}{Junktown is struggeling with being close to an energy crisis. Thomas, the person in charge, asked me to help him with repairing and optimizing the power house generators. 

In order to do this, I have to find new electronic parts with that I can repair the generators. After the machines are repaired, I can try to optimize them.}
{7122002}{}{You have fully repaired all power house generators. They can be further optimized now.}
{7122003}{}{You have been able to optimize Junktown's power house generators. Turning around the power switches will bring the machines back to full capacity.}
{7122004}{}{You turn the switches and the machines are starting up again.}
{7122005}{}{Junktown's power house is now running with optimal capacity again. 

:: Quest Completed ::}

{7122101}{}{Junktown: Optimizing the Power House}
{7122102}{}{Optimizing the Power House}

#=======================================
# 7124
# Junktown, Repairing the Mr. Handy Robot
#=======================================
{7124001}{}{Thomas' Mr. Handy robot isn't working. He told me that there might be a problem with the motivator unit and that Mitch in the Hub most likely has a working replacement part.}
{7124002}{}{I've been able to get a robot motivator unit from Mitch in the Hub. With this part, I should be able to fix the Mr. Handy robot without big problems.}
{7124003}{}{I have been able to fix the Mr. Handy unit for Thomas. 

:: Quest Completed ::}

{7124101}{}{Junktown: The inoperative Mr. Handy Robot}
{7124102}{}{The inoperative Mr. Handy Robot}

#=======================================
# 7128
# Hub, Gun Runner Delivery
#=======================================
{7128001}{}{Jacob in the Hub, Oldtown, needs more weapons and ammunition in his next supply delivery from the Gun Runners. He has sent me to talk with Marshal about it, the head honcho of the Gun Runners in the Angel's Boneyard.}
{7128002}{}{Marshal isn't happy about the deal with Jacob and doesn't want to send more weaponry and ammunition. I should talk with Jacob about it.}
{7128003}{}{Jacob agrees on paying more money for the next gun deliveries, but wants to have the next one to be delivered earlier.}
{7128004}{}{?not used?}
{7128005}{}{I've been able to negotiate a new deal with the Gun Runners for Jacob.}
{7128006}{}{A new deal between the Gun Runners and Jacob has been negotiated and both parties agreed on it.

:: Quest Completed ::}

{7128101}{}{Hub: The Gun Runner Delivery}
{7128102}{}{The Gun Runner Delivery}

#=======================================
# 7132
# NCR, Westin Ranch Quest 1, Brahmin herdsman
#=======================================
{7132001}{}{Got a new job as brahmin herdsman for the Roger Westin. I've been told to talk to Felix, the foreman. He will guide me to the willow, where I am supposed to take care of the brahmin herd.}
{7132002}{}{Felix guided me to the brahmin willow.}
{7132003}{}{Nothing of interest happened for quite some time, until a gang of children showed up. They wanted to startle the brahmin herd, but I chased them away.}
{7132004}{}{A gang of children showed up. They wanted to startle the brahmin herd, but I killed them.}
{7132005}{}{I've reported back to Roger Westin at the Westin Ranch. He paid me and that's it.

:: Quest Completed ::}

{7132006}{}{I've reported back to Roger Westin at the Westin Ranch. He didn't paid me, because I've killed children.

:: Quest Completed ::}

{7132007}{}{I've killed the brahmin of Roger Westin. I doubt he will be happy, if he finds out what I did.}
{7132008}{}{Westin had found out about the dead brahmin and fired me. I've told the guard at entrance a pack of lies to cover my guilt. It doesn't seem like they ate it, I should probably lay low for a while.

:: Quest Failed ::}

{7132101}{}{NCR: A Brahmin Herdsman' Job}
{7132102}{}{A Brahmin Herdsman' Job}

#=======================================
# 7135
# NCR, Westin Ranch Quest 2, Holodisk Delivery
#=======================================
{7135001}{}{My second job from Roger Westin is to deliver a special Holodisk to a man named Thomas Moore in Vault City.}
{7135002}{}{I have given the Holodisk to Thomas Moore. Now I'll have to report back to Roger Westin.}
{7135003}{}{I've reported back to Roger Westin at the Westin Ranch and he paid me for the delivery.

:: Quest Completed ::}

{7135101}{}{NCR: Holodisk for Thomas Moore}
{7135102}{}{Holodisk for Thomas Moore}


#=======================================
# 7139
# Junktown, Bring Scorpion Eggs
#=======================================
{7139001}{}{Close to Junktown is a cave with highly venomous Black Claw Radscorpions. Doc Larrikin wants me to go there and collect at least five Radscorpion eggs for him, as he isn't able to do it by himself.}
{7139002}{}{Eggs given :: Not Used ::.}
{7139003}{}{Doc Larrikin seemed to be quite happy when I gave him the requested Radscorpion eggs. 

:: Quest Completed ::}
{7139004}{}{I couldn't deliver Radscorpion eggs to Doc Larrikin in time.

:: Quest Failed ::}

{7139101}{}{Junktown: Collect the Radscorpion Eggs}
{7139102}{}{Collect the Radscorpion Eggs}

#=======================================
# 7147
# Boneyard, Gun Runners Courier
#=======================================
{7147001}{}{Marshal from the Gun Runners gave me a special shipment for Jargo, the local gunsmith in New Adytum.}
{7147002}{}{Marshal from the Gun Runners gave me a special shipment for Jacob, the arms dealer in Oldtown.}
{7147003}{}{Marshal from the Gun Runners gave me a special shipment for Mai Da Chiang in the Red 888 Guns shop.}
{7147004}{}{Marshal from the Gun Runners gave me a special shipment for Eldridge at the New Reno Arms gun store in New Reno West Side.}
{7147005}{}{Marshal from the Gun Runners gave me a special shipment for Buster, the local arms dealer at the NCR Bazaar.}
{7147006}{}{Marshal from the Gun Runners gave me a special shipment for Jeremiah Darkwater in Junktown. I've been told, that his shop is at the center of the town and I can't miss it.}
{7147007}{}{The package has been delivered and I am now on my way back to Marshal.}
{7147008}{}{The package has been delivered and I've got my reward from the Gun Runners.

:: Quest Completed ::}
{7147009}{}{The package never arrived at it's target. The Gun Runners had been pretty angry. I should stay away from them for the next time.

:: Quest Failed ::}

{7147101}{}{Boneyard: Deliver the Gun Runners package}
{7147102}{}{Deliver the Gun Runners package}

#=======================================
# 7300
# New Reno, Corsican Brothers, Dissapear
#=======================================
{7300001}{}{Marti, the head of the Corsican Brothers in New Reno wants me to get rid of a dead body. I should talk to Snake about it.}
{7300002}{}{Snake passed the dead body on to me and mentioned a creepy place known as Golgotha, just a bit south of New Reno. I should drop it off there and get rid of it somehow.}
{7300003}{}{The dead body has been properly burried. Unfortunately, there was nothing more I could do for that poor, tormented soul. Time to inform Marty about it.}
{7300004}{}{Good riddance! Burning down the dead body on Golgotha was the best way to make it disappear. I should talk to Marty at once.}
{7300005}{}{The dead body has been taken care of.

:: Quest Completed ::}
{7300006}{}{The dead body has been taken care of. Somewhat sloppy work, but it's finally gone.

:: Quest Completed ::}
{7300007}{}{Following Snake's instructions for dealing with the dead body was simply too much for you.

:: Quest Failed ::}
{7300101}{}{New Reno, Corsican Brothers: Make it disappear}
{7300102}{}{Make it disappear}

#=======================================
# 7301
# New Reno, Corsican Brothers, Tattoo
#=======================================
{7301001}{}{Marty thinks I could lend a hand to them Corsican Brothers and invites me to join the bunch. I should immidiately visit a tattoo shop and ask for the official Corsican Brothers tattoo there.}
{7301002}{}{The Corsican Brothers tattoo looks rather fancy. I should show it to Marty as soon as possible.}
{7301003}{}{You have joined the Corsican Brothers

:: Quest Completed ::}
{7301101}{}{New Reno, Corsican Brothers: Join the Corsican Brothers}
{7301102}{}{Join the Corsican Brothers}

#=======================================
# 7311
# Brahmin Run quest
#=======================================
{7311001}{}{I was asked to lead brahmin herd to a ranch. I shouldn't stop in any towns on my way or the herdsman will go without me.}
{7311002}{}{I wasn't able to protect the brahmin.

:: Quest Failed ::}
{7311003}{}{Herdsman was killed, the barhmin won't follow me anymore.

:: Quest Failed ::}
{7311004}{}{Herdsman took brahmin and continued journey without me.

:: Quest Failed ::}
{7311005}{}{I left the brahmin to their doom.

:: Quest Failed ::}
{7311006}{}{I was badly injoured when I tried to defend the brahmin. I don't know what happened to them.

:: Quest Failed ::}
{7311007}{}{I managed to lead the brahmin herd to the ranch. I should return for my reward.}
{7311008}{}{I got some caps as a reward. Maybe I should drop by later for some more work.

:: Quest Completed ::}
{7311009}{}{It took me too long to take brahmin where I was supposed to. Herdsman took brahmin and continued journey without me.}
{7311101}{}{Brahmin Run}
{7311102}{}{Lead herd of brahmin to a ranch.}

#=======================================
# 7322
# First Tent quest
#=======================================
{7322001}{}{During my journeys through the wasteland I noticed a small tent in this area. Maybe I should check it out.}
{7322002}{}{I met a family of farmers living in the tent. They escaped from a farmhouse infested with giant mutated rats. I promised to help them out.}
{7322003}{}{I killed all the mutated rats in the farm. I should return to the family and tell them that they can come back home safely.}
{7322004}{}{The family living in the tent was very happy to hear that they can finally come back home. Before leaving they gave me their tent.

:: Quest Completed ::}
{7322005}{}{I didn't help the farmers and now their tent is gone. Maybe they moved somewhere else or the wasteland claimed their lifes...

:: Quest Failed ::}
{7322101}{}{A Tent in the Wasteland}
{7322102}{}{Investigate a certain tent in the wasteland.}
