# TODO:
# 1000 - 1530

# DONE:



#
# Created 21.04.08, Cvet
#
# В данном файле сценаристы могут создавать свои строки.
#
#
# Manufacture, Alcohol
#

#
# Generic messages
#




{400}{}{Your character with your IP is connected to the server already. Dropping the connection, try to login again now.}


# taken from SDK:
{500}{}{Gets @lex result@ on a die roll} # Dice
{510}{}{Magic 8-Ball says: Yes} # Magic ball
{511}{}{Magic 8-Ball says: No} # Magic ball
{520}{}{Preens @sex@|him||her|self} # Cosmetic
{530}{}{. Puffs on a cig .oO} # Cigarettes


# Use
{1500}{}{The distillation device is out of order.}
{1501}{}{Firewood needed.}
{1502}{}{You are watching the wood burning in a stove.}
{1503}{}{There is fresh-brewed beer in the tank!}
{1504}{}{A tank with home-distilled alcohol is fulled to the brim.}
# Use empty bottles
{1505}{}{You poured the beer into the bottles.}
{1506}{}{You poured alcohol into the bottles.}
{1507}{}{You have not enough tare.}
# Use firewood
{1508}{}{This device is broken.}
{1509}{}{Need more firewood. What you have is probably not enough.}
{1510}{}{You don't know what ingredients to use and how much.}
{1511}{}{You prepared and poured in the stuff. You lit a fire in the stove. Distillation has begun.}
{1512}{}{You lit a fire in the stove and poured in the stuff. Home-distilated vodka has begun to fill in the tank.}
{1513}{}{There is enough wood there already.} 
{1514}{}{At first you have to pour out brewed beer.}
{1515}{}{At first you have to pour out just distilled vodka.}
# To broke
{1516}{}{You have just broken the brewing equipment.}
{1517}{}{You have just broken the distilling device.} 
{1518}{}{The boiler did not sustain the pressure and exploded!}
{1519}{}{Boiling water sprays in to your eyes!.}
# Repair
{1520}{}{Looks like you need some details.}
{1521}{}{You need tools to fix this.}
{1522}{}{You have succesfully fixed the device.}
{1523}{}{You have failed at repairing and broken some parts.}
# Science
{1524}{}{This device can be fixed, but you need a wrench or something like that.}
{1525}{}{Your wrench has been broken as well as the device.}
{1526}{}{During repairing you dismounted half of the device. Now you need to assemble it back somehow.}
{1527}{}{You fixed something carefully but it has not brought any result.}
{1528}{}{You have fixed the brewing device. Now you'll need much less firewood.}
{1529}{}{You have fixed the distillation device. Now you'll need much less firewood.}
{1530}{}{You have failed to fix the device. Luckily, nothing got broken.}
# Scenery
{1560}{}{Some cereals lay here. They are cleared and dried.}
{1561}{}{In these tanks fermentation of raw materials for alcohol takes place.}

# Smart cursor info
{1800}{}{Error}
{1801}{}{Extract Iron}
{1802}{}{Extract HQ Iron}
{1803}{}{Extract Minerals}
{1804}{}{Extract HQ minerals}
{1805}{}{Extract Uranium}
{1806}{}{Extract Gold}
{1807}{}{Extract Fibres}
{1808}{}{Shovel Dung}
{1809}{}{Chop Wood}
{1810}{}{Dig Grave}

#
# Casino
#

{2000}{}{*Ring-a-ling*}
{2000}{}{*Zzzzzzz*}
{2000}{}{*Bing*}
{2000}{}{*Dingity-ding*}
{2000}{}{*Ding*}
{2000}{}{*Kaa-ching*}

#
# Car, car.fos
#

{2100}{}{Number: @lex number@. Fuel: @lex fuel@/@lex fuel_tank@. Damage: @lex wear@%.}

#
# Getting firewood from tree (use axe on tree)
#

{2200}{}{This is a suitable tree. You can cut fire wood... but only with healthy hands.}
{2201}{}{You need to rest.}
{2202}{}{You hit your hand instead of the tree!}
{2203}{}{You've cut some fire wood.}
{2204}{}{You've cut some fire wood, but can't carry all of it.}
{2205}{}{You've cut some fire wood, but can't carry any of it.}

#
# Production
#
{3000}{}{You can't do this right now.}
{3001}{}{You are lacking the skills to do that.}
{3008}{}{You've gathered some seeds from the plant.}
{3009}{}{You've harvested some tobacco from the plant.}
{3010}{}{You've butchered some brahmin, and obtained some hide and meat.}
{3011}{}{You've harvested some fruits from the tree.}
{3012}{}{You've dug some ore.}
{3013}{}{You've dug some minerals.}
{3014}{}{You've found some junk.}
{3015}{}{You've gathered some high-quality excrements.}
{3016}{}{You've chopped some wood.}
{3017}{}{You've distilled a marvellous beverage.}
{3018}{}{You need to prepare the still first.}
{3019}{}{Now when you have all the ingredients, you need to start a fire.}
{3020}{}{You started a fire, now you need to add distilling material.}
{3021}{}{You've inserted fruit into the still.}
{3022}{}{Fire already burning.}
{3023}{}{You started a fire, product will be ready soon.}
{3024}{}{Everything needed is already there.}
{3025}{}{Fire is ready, but you need to add distilling material.}
{3026}{}{Everything is ready to go.}
{3027}{}{Everything is set up.}
{3030}{}{The resources have been depleted.}
{3031}{}{You've dug some uranium ore.}
{3040}{}{You've found xander root.}
{3041}{}{You didn't find anything interesting here.}
{3042}{}{It's better to leave that piece of rock before you get hurt.}
{3043}{}{You've found piece of flint.}
{3044}{}{You've found broc flower.}
{3045}{}{You've obtained some fiber.}
{3046}{}{To get the fiber, you need to cut the plant.}
{3047}{}{You'll need a knife to start butchering your brahmin on that table.}
{3048}{}{There are no fruits on this plant.}
{3049}{}{There is no fiber left on this plant.}
{3050}{}{There are no brahmins left to butcher.}
{3051}{}{There is not much of wood left on this stump.}
{3052}{}{There is nothing interesting here.}
{3053}{}{There are no leaves left on this plant.}
{3054}{}{There are no spikes left on this plant.}
{3060}{}{You stumbled upon a lost brahmin.}
# Wrecked car
{3061}{}{No, with this car you won't go far.}
{3062}{}{You've found something that might be useful.}
# Campfire
{3065}{}{You need to toss more wood.}
{3066}{}{The fire is burning.}
# Broken computer
{3070}{}{You've managed to obtain some electronic parts.}
{3071}{}{You were unable to obtain anything useful.}
{3072}{}{Without proper approach, this broken computer isn't of any use.}
{3073}{}{There are no interesting parts left inside. Looks like it already been scavenged.}
# Chemicals
{3075}{}{You've managed to fetch some chemical compounds.}
{3076}{}{Without proper approach, you won't obtain anything useful.}
# Nuka Cola
{3077}{}{You've crated a marvellous beverage.}
{3078}{}{You need to prepare the Nuka Cola machine first.}
{3079}{}{Now when you have all the ingredients, you need to exchange the machine battery.}
{3080}{}{You exchanged the battery, now you need to add recipe material.}
{3081}{}{You've inserted fruit into the Nuka Cola machine.}
{3082}{}{Battery already exchanged.}
{3083}{}{You exchanged the battery, product will be ready soon.}
{3084}{}{Everything needed is already there.}
{3085}{}{Battery is exchanged, but you need to add recipe material.}
{3086}{}{Everything is ready to go.}
{3087}{}{Everything is set up.}
{3088}{}{Machine is not yet ready.}
# Ep+ computer
{3089}{}{You've managed to obtain some high-quality electronic parts.}
{3090}{}{You were unable to obtain anything useful.}
# Chem+
{3091}{}{You've managed to fetch some rare, high quality chemical compounds.}
{3092}{}{You were unable to obtain anything useful.}

# Veins
{3100}{}{You've dug some iron ore.}
{3101}{}{This iron vein has depleted.}
{3102}{}{You need a primitive tool, sledgehammer or a super sledge to extract iron.}
{3103}{}{You've dug some high quality iron ore.}
{3104}{}{This high quality iron vein has depleted.}
{3105}{}{You need a sledgehammer or a super sledge to extract high quality iron.}
{3106}{}{You've dug some minerals.}
{3107}{}{This source of minerals has depleted.}
{3108}{}{You need a primitive tool, sledgehammer or a super sledge to extract minerals.}
{3109}{}{You've dug some high quality minerals.}
{3110}{}{This source of high quality minerals has depleted.}
{3111}{}{You need a super sledge to extract high quality minerals.}
{3112}{}{You've dug some uranium ore.}
{3113}{}{This uranium vein has depleted.}
{3114}{}{You need a super sledge to extract uranium.}
{3115}{}{You've dug a gold nugget.}
{3116}{}{This gold vein has depleted.}
{3117}{}{You need a super sledge to extract gold.}

#
# Radiation
#

{4000}{}{You've received dose of radiation.}
{4001}{}{You've received a large dose of radiation.}
{4002}{}{Your radiation level has been lowered.}
# Radiation levels
{4010}{}{You feel a little nauseous.}
{4010}{}{You feel some slight tingling in your face.}
{4011}{}{You feel pretty ill.}
{4011}{}{A metallic taste fills your mouth.}
{4012}{}{You feel very nauseous.}
{4012}{}{Your whole face is tingling.}
{4013}{}{You feel extremely awful.}
{4013}{}{Your face feels like it's burning.}
{4014}{}{You feel like you are slowly dying.}
{4014}{}{You are extremely dizzy and nauseous, your vision swimming and head throbbing.}
{4015}{}{Due to radiation, you are dying in intense agony.}
# Other side effects
{4030}{}{You find yourself covered in @lex name@'s bile.}
{4031}{}{Your hair is falling out.}
{4032}{}{Your skin is peeling off.}
{4033}{}{You're vomitting.}
{4034}{}{You're suffering from radiation sickness.}

# Geiger
{4050}{}{You've scanned your body with the geiger counter. It reads: @lex rems@.}

# Vomits
{4060}{}{You've cleaned it with your bare hands. Thank you.}
{4061}{}{Investigating this piece of bile, you come to the conclusion that it's irradiated.}
{4062}{}{You are unable to determine what diet caused this.}
{4063}{}{You feel something slippy under your feet.}

# Flare
{4070}{}{You light up the flare.}

#
# Drugs and addictions
#

# Jet
{4100}{}{Everything is moving so slowly... you need to get some more Jet, right NOW!}
{4101}{}{You feel better.}
{4102}{}{***Pshhh***}
# Mentats
{4110}{}{You feel groggy.}
{4111}{}{You feel better.}

#
# Brahmin dung
# Proofread!
#
{4200}{}{No matter how hard you try, you can't clean it barehanded. Now you just stink.}
{4201}{}{The diet of that brahmin was rich in cellulose.} # high doc or science
{4202}{}{Yeah, it's funny to play with it.} # low doc or science
{4203}{}{Whoops, is it a minefield?} # walked into the shit
{4204}{}{You've cleaned the dung using your shovel.}
{4205}{}{Holy shit! Now you REALLY stink.} # slipped on the shit
{4206}{}{The brahmin around you look agitated.} # brahmin got mad



#
# antiblock
#
{4300}{}{You better move.}
{4301}{}{Really.}

#
# Lock
#
{4400}{}{You've locked the container with a lock.}

#
# Guards features
#
# Taking items while killed in guarded area
{4500}{}{|4291317840 You've been killed in a guarded area. Your items have been taken by guards.}
{4501}{}{|4291317840 You've caused troubles in this town, guards will not protect you.}
{4502}{}{|4291317840 You recognize @lex name@ as troublemaker.} # not used
{4503}{}{@lex name@, seems like @lex thief@ is interested in your possesions.}
{4504}{}{|4291317840 @lex name@ has been spotted by guards while stealing.}

# Rooms
{4600}{}{Uhh...my head hurts... How did I end up here?} # Replicate in room

# Trains
{4700}{}{San Francisco}
{4701}{}{Boneyard}
{4702}{}{NCR}
{4703}{}{Vault City}
{4704}{}{NCR}
{4705}{}{Boneyard}

{4720}{}{, next day}
{4721}{}{A train to @lex dest@ leaves in @lex ttl@ minutes!}
{4721}{}{Attention, a train to @lex dest@ leaves in @lex ttl@ minutes!}
{4721}{}{The train leaves soon, please get in!}
{4722}{}{The train has arrived!}
{4722}{}{The train has arrived, prepare to get on board!}
{4722}{}{The train has arrived, you may take your seats now.}

# Stealth Boy
{4800}{}{You've used a Stealth Boy. You're more stealthy now.}
{4801}{}{You've prolonged your increased stealth.}
{4802}{}{Your Stealth Boy has been used up.}
{4803}{}{Stealth Boy bug. Please report this.}

# Motion sensor
{4900}{}{Motion sensor has no charges left.}
{4901}{}{Motion sensor is on.}
{4902}{}{Motion sensor is off.}
{4903}{}{Motion sensor charged.}
{4904}{}{Motion sensor charge will last for another @lex time@.}

# Toggle switch
{4920}{}{*click* *click* Nothing happens. It looks like you are too far away from the explosives.}

# Geiger counter
{10350}{}{Geiger counter has no charges left.}
{10351}{}{Geiger counter is on.}
{10352}{}{Geiger counter is off.}
{10353}{}{You pass the Geiger counter over your body. The rem counter reads: @lex rem@.}
{10354}{}{The rem counter reads: @lex rem@.}
{10355}{}{Nothing happens.}
{10356}{}{Geiger counter charged.}
{10357}{}{Geiger counter charge is @lex cur@/@lex max@.}

# Throwing
{10400}{}{You've thrown @lex what@.}
{10401}{}{You've thrown @lex what@ and missed.}

#
# Production, pt. 2
#

# rotgut still
{10500}{}{You need to put some fruits into the still.}
{10501}{}{You've put the fruits in the still.}
{10502}{}{You need to prepare some firewood to boil the ingredients.}
{10503}{}{You've tossed some wood.}
{10504}{}{You've started the process.}
{10505}{}{The machine is still working.}
{10506}{}{|0xFF00FF **Puff**}
{10506}{}{|0xFF00FF **Sss**}
# beer
{10600}{}{You need to put some barley into the still.}
{10601}{}{You've put some barley in the still.}
{10602}{}{You need to add water to the ingredients.}
{10603}{}{You've added some water.}
{10604}{}{You've started the brewing process.}
{10605}{}{The machine is still working.}
{10606}{}{|0xFF00FF **Puff**}
{10606}{}{|0xFF00FF **Sss**}
{10606}{}{|0xFF00FF **Bubbles**}
# nukacola
{10700}{}{You need to put some fruits into the machine.}
{10701}{}{You've put the fruits in the machine.}
{10702}{}{The process require some water.}
{10703}{}{You've added some water.}
{10704}{}{The machine started to work.}
{10705}{}{The machine is still working.}
{10706}{}{|0xFF00FF **Beep**}
{10706}{}{|0xFF00FF **Rrrr**}
# cigs
{10800}{}{You need to put some leaves into the bench.}
{10801}{}{You've put the leaves.}
{10804}{}{You've started preparing tobacco leaves for cigarettes.}
{10805}{}{The machine is still working.}
{10806}{}{}
# hq fibers
{10900}{}{You've started refining process.}
{10901}{}{The machine is still working.}
{10902}{}{**Rrrrr**}
{10910}{}{You need to put some fiber to refine.}
{10911}{}{You've placed the fiber in the machine.}
{12000}{}{Reserved}

# Achievements
# 20000-22549
# 20000 + (id*10)    title
# 20000 + (id*10)+1  description
{20000}{}{Man of Steel}
{20001}{}{Slaying every enemy, hiding behind friends back or throwing rocks from safe distance -- you know all ways to survive in harsh wasteland, without visiting a hospital.\nTruly hero you are... or stinking coward.}
{22540}{}{GM ABUSE}
{22541}{}{You just executed your first cheat-command.\nRemember... Don't fuck up anything.}

# Faction names
#
# Each even string (beginning from 0) is faction 'official' name
# Each odd string is the alias
#
{1000000}{}{Unknown}
{1000001}{}{Unknown}
{1000002}{}{None}
{1000003}{}{None}
{1000004}{}{Brotherhood Of Steel}
{1000005}{}{Brotherhood Of Steel}
{1000005}{}{Brotherhood}
{1000005}{}{BoS}
{1000006}{}{Enclave}
{1000007}{}{Enclave}
{1000007}{}{The Enclave}
{1000008}{}{The Unity}
{1000009}{}{The Unity}
{1000009}{}{Unity}
{1000010}{}{New California Republic}
{1000011}{}{New California Republic}
{1000011}{}{NCR}
{1000012}{}{Vault City}
{1000013}{}{Vault City}
{1000013}{}{Vault-City}
{1000013}{}{VaultCity}
{1000013}{}{VC}
{1000014}{}{Raiders}
{1000015}{}{Raiders}
{1000016}{}{The Slags}
{1000017}{}{The Slags}
{1000017}{}{Slags}
{1000018}{}{The Skags}
{1000019}{}{The Skags}
{1000019}{}{Skags}
{1000020}{}{The Khans}
{1000021}{}{The Khans}
{1000021}{}{Khans}
{1000022}{}{The Vipers}
{1000023}{}{The Vipers}
{1000023}{}{Vipers}
{1000024}{}{The Jackals}
{1000025}{}{The Jackals}
{1000025}{}{Jackals}
{1000026}{}{Blackfoots}
{1000027}{}{Blackfoots}
{1000028}{}{Hangdogs}
{1000029}{}{Hangdogs}
{1000030}{}{Scaven Pickers}
{1000031}{}{Scaven Pickers}
{1000032}{}{The Salvatores}
{1000033}{}{The Salvatores}
{1000033}{}{Salvatores}
{1000034}{}{The Mordinos}
{1000035}{}{The Mordinos}
{1000035}{}{Mordinos}
{1000036}{}{The Bishops}
{1000037}{}{The Bishops}
{1000037}{}{Bishops}
{1000038}{}{The Wrights}
{1000039}{}{The Wrights}
{1000039}{}{Wrights}
{1000040}{}{The Far-Go Traders}
{1000041}{}{The Far-Go Traders}
{1000041}{}{Far-Go Traders}
{1000041}{}{Fargo Traders}
{1000042}{}{The Friendly Loans Company}
{1000043}{}{The Friendly Loans Company}
{1000043}{}{Friendly Loans}
{1000044}{}{The Water Merchants}
{1000045}{}{The Water Merchants}
{1000045}{}{Water Merchants}
{1000046}{}{The Morton Brothers}
{1000047}{}{The Morton Brothers}
{1000047}{}{Morton Brothers}
{1000048}{}{The Skullz}
{1000049}{}{The Skullz}
{1000049}{}{Skullz}
{1000050}{}{Crimson Caravan}
{1000051}{}{Crimson Caravan}
{1000052}{}{Desert Rangers}
{1000053}{}{Desert Rangers}
{1000054}{}{Gun Runners}
{1000055}{}{Gun Runners}
{1000056}{}{The Reavers}
{1000057}{}{The Reavers}
{1000057}{}{Reavers}
{1000058}{}{The Regulators}
{1000059}{}{The Regulators}
{1000059}{}{Regulators}
{1000060}{}{Reilly's Rangers}
{1000061}{}{Reilly's Rangers}
{1000062}{}{The Rippers}
{1000063}{}{The Rippers}
{1000063}{}{Rippers}
{1000064}{}{The Shi}
{1000065}{}{The Shi}
{1000065}{}{Shi}
{1000066}{}{The Squatters}
{1000067}{}{The Squatters}
{1000067}{}{Squatters}
{1000068}{}{Yakuza}
{1000069}{}{Yakuza}
{1000070}{}{Thieves' Guild}
{1000071}{}{Thieves' Guild}
{1000072}{}{The Blades}
{1000073}{}{The Blades}
{1000073}{}{Blades}
{1000074}{}{The Beastlords}
{1000075}{}{The Beastlords}
{1000075}{}{Beastlords}
{1000076}{}{The Tanker Vagrants}
{1000077}{}{The Tanker Vagrants}
{1000077}{}{Vagrants}
{1000078}{}{Union of Atomic Workers}
{1000079}{}{Union of Atomic Workers}
{1000079}{}{Atomic Workers}
{1000080}{}{The Butter Boys}
{1000081}{}{The Butter Boys}
{1000081}{}{Butter Boys}
{1000082}{}{The Laserists}
{1000083}{}{The Laserists}
{1000083}{}{Laserists}
{1000084}{}{The Big Barons}
{1000085}{}{The Big Barons}
{1000085}{}{Big Barons}
{1000085}{}{Barons}
{1000086}{}{The Orlocks}
{1000087}{}{The Orlocks}
{1000087}{}{Orlocks}
{1000088}{}{The Rogues}
{1000089}{}{The Rogues}
{1000089}{}{Rogues}
{1000090}{}{The Electric Eliminators}
{1000091}{}{The Electric Eliminators}
{1000091}{}{Electric Eliminators}
{1000091}{}{Eliminators}
{1000092}{}{The Warriors}
{1000093}{}{The Warriors}
{1000093}{}{Warriors}
{1000094}{}{The Riffs}
{1000095}{}{The Riffs}
{1000095}{}{Riffs}
{1000096}{}{The Saracens}
{1000097}{}{The Saracens}
{1000097}{}{Saracens}
{1000098}{}{The Van Cortlandt Rangers}
{1000099}{}{The Van Cortlandt Rangers}
{1000099}{}{Van Cortlandt Rangers}
{1000100}{}{The Latics}
{1000101}{}{The Latics}
{1000101}{}{Latics}
{1000102}{}{The Albion}
{1000103}{}{The Albion}
{1000103}{}{Albion}
{1000104}{}{The Amboy Dukes}
{1000105}{}{The Amboy Dukes}
{1000106}{}{Heighton Armistice}
{1000107}{}{Heighton Armistice}
{1000108}{}{Lamstow Barracudas}
{1000109}{}{Lamstow Barracudas}
{1000110}{}{Virgin Street Man Dem}
{1000111}{}{Virgin Street Man Dem}
{1000112}{}{The Klamath Big Boys}
{1000113}{}{The Klamath Big Boys}
{1000114}{}{The Gecko Irreducibles}
{1000115}{}{The Gecko Irreducibles}
{1000116}{}{The Affirmative Actions}
{1000117}{}{The Affirmative Actions}
{1000118}{}{The Bharatiya Janata Party}
{1000119}{}{The Bharatiya Janata Party}
{1000119}{}{Bharatiya Janata Party}
{1000120}{}{The Redding Guttersnipes}
{1000121}{}{The Redding Guttersnipes}
{1000122}{}{The Den Hoodlums}
{1000123}{}{The Den Hoodlums}
{1000124}{}{West Side Roughboys}
{1000125}{}{West Side Roughboys}
{1000126}{}{The Wagner Loves}
{1000127}{}{The Wagner Loves}
{1000128}{}{Rasczak's Roughnecks}
{1000129}{}{Rasczak's Roughnecks}
{1000130}{}{Vault City Courtyard Bicycle Gang}
{1000131}{}{Vault City Courtyard Bicycle Gang}
{1000131}{}{VC Courtyard Gang}
{1000132}{}{The Tasty Dudes}
{1000133}{}{The Tasty Dudes}
{1000134}{}{The Christmas Tree Club}
{1000135}{}{The Christmas Tree Club}
{1000136}{}{The Broken Hills Paramours}
{1000137}{}{The Broken Hills Paramours}
{1000137}{}{Broken Hills Paramours}
{1000138}{}{The Almighty Gaylords}
{1000139}{}{The Almighty Gaylords}
{1000140}{}{Master Batino and the Daughters of Voltaire}
{1000141}{}{Master Batino and the Daughters of Voltaire}
{1000141}{}{BDV}
{1000142}{}{The Lester Smooths}
{1000143}{}{The Lester Smooths}
{1000144}{}{The Grenadines}
{1000145}{}{The Grenadines}
{1000146}{}{The Turnbull ACs}
{1000147}{}{The Turnbull ACs}
{1000148}{}{The Orphans}
{1000149}{}{The Orphans}
{1000150}{}{The Boppers}
{1000151}{}{The Boppers}
{1000152}{}{The Panzers}
{1000153}{}{The Panzers}
{1000154}{}{The Gladiators}
{1000155}{}{The Gladiators}
{1000156}{}{Division de Comerciantes Desplazados}
{1000157}{}{Division de Comerciantes Desplazados}
{1000157}{}{Desplazados}
{1000158}{}{The Alleycats}
{1000159}{}{The Alleycats}
{1000160}{}{The Black Hands}
{1000161}{}{The Black Hands}
{1000162}{}{The Blackjacks}
{1000163}{}{The Blackjacks}
{1000164}{}{The Big Trains}
{1000165}{}{The Big Trains}
{1000166}{}{The Charlemagnes}
{1000167}{}{The Charlemagnes}
{1000168}{}{The Colt 45's}
{1000169}{}{The Colt 45's}
{1000170}{}{The Dealers}
{1000171}{}{The Dealers}
{1000172}{}{The Easy Aces}
{1000173}{}{The Easy Aces}
{1000174}{}{The Fastballs}
{1000175}{}{The Fastballs}
{1000176}{}{The Five Points}
{1000177}{}{The Five Points}
{1000178}{}{The Gerrards}
{1000179}{}{The Gerrards}
{1000180}{}{The Go Hards}
{1000181}{}{The Go Hards}
{1000182}{}{The Homeboys}
{1000183}{}{The Homeboys}
{1000184}{}{The Howitzers}
{1000185}{}{The Howitzers}
{1000186}{}{The High Rollers}
{1000187}{}{The High Rollers}
{1000188}{}{The Judas Bunch}
{1000189}{}{The Judas Bunch}
{1000190}{}{The Jupiters}
{1000191}{}{The Jupiters}
{1000192}{}{The Knockdowns}
{1000193}{}{The Knockdowns}
{1000194}{}{The Locos}
{1000195}{}{The Locos}
{1000196}{}{The Meatpackers}
{1000197}{}{The Meatpackers}
{1000198}{}{The Nickel Steaks}
{1000199}{}{The Nickel Steaks}
{1000200}{}{The Plainsmen}
{1000201}{}{The Plainsmen}
{1000202}{}{The Real Boys}
{1000203}{}{The Real Boys}
{1000204}{}{The Roadmasters}
{1000205}{}{The Roadmasters}
{1000206}{}{The Dutch Lizards}
{1000207}{}{The Dutch Lizards}
{1000208}{}{The Stilletos}
{1000209}{}{The Stilletos}
{1000210}{}{The Yo-Yos}
{1000211}{}{The Yo-Yos}
{1000212}{}{The Whispers}
{1000213}{}{The Whispers}
{1000214}{}{B.S.U}
{1000215}{}{B.S.U}
{1000216}{}{Colby Loop}
{1000217}{}{Colby Loop}
{1000218}{}{Crazy S.O.B.s}
{1000219}{}{Crazy S.O.B.s}
{1000220}{}{Cadillac Crips}
{1000221}{}{Cadillac Crips}
{1000222}{}{The Cobras}
{1000223}{}{The Cobras}
{1000224}{}{The Radscorpions}
{1000225}{}{The Radscorpions}
{1000226}{}{Pura Familia Loca}
{1000227}{}{Pura Familia Loca}
{1000228}{}{Patrons of Purgatory}
{1000229}{}{Patrons of Purgatory}
{1000230}{}{The Philistines}
{1000231}{}{The Philistines}
{1000232}{}{The Chartists}
{1000233}{}{The Chartists}
{1000234}{}{The Cato Street Conspiracy}
{1000235}{}{The Cato Street Conspiracy}
{1000235}{}{Cato Street Conspiracy}
{1000236}{}{The Luddites}
{1000237}{}{The Luddites}
{1000238}{}{Mad Andrew's Ornery Jet Addicts}
{1000239}{}{Mad Andrew's Ornery Jet Addicts}
{1000239}{}{Jet Addicts}
{1000240}{}{Slam Mafia}
{1000241}{}{Slam Mafia}
{1000242}{}{Street Queens}
{1000243}{}{Street Queens}
{1000244}{}{East Side Weirdboys}
{1000245}{}{East Side Weirdboys}
{1000246}{}{The Widowmakers}
{1000247}{}{The Widowmakers}
{1000248}{}{The Wildsiders}
{1000249}{}{The Wildsiders}
{1000250}{}{Young Conservative Women's Association}
{1000251}{}{Young Conservative Women's Association}
{1000251}{}{YCWA}
{1000252}{}{The Willy Shakers}
{1000253}{}{The Willy Shakers}
{1000254}{}{The Thugs of Modoc}
{1000255}{}{The Thugs of Modoc}
{1000256}{}{The Fuckest Uppest}
{1000257}{}{The Fuckest Uppest}
{1000258}{}{New Reno Untouchable}
{1000259}{}{New Reno Untouchable}
{1000260}{}{Born Sick Gang}
{1000261}{}{Born Sick Gang}
{1000262}{}{The Holy Smokes}
{1000263}{}{The Holy Smokes}
{1000264}{}{South Reno Chopstiks Gang}
{1000265}{}{South Reno Chopstiks Gang}
{1000266}{}{The Absolute Darlings}
{1000267}{}{The Absolute Darlings}
{1000268}{}{North Side Chuggy Chix}
{1000269}{}{North Side Chuggy Chix}
{1000270}{}{Chosen Soldiers}
{1000271}{}{Chosen Soldiers}
{1000271}{}{CS}
{1000272}{}{Reno's Most Wanted}
{1000273}{}{Reno's Most Wanted}
{1000274}{}{The Jeeperz}
{1000275}{}{The Jeeperz}
{1000276}{}{Piff City Bangers}
{1000277}{}{Piff City Bangers}
{1000278}{}{Bang Bang Smash}
{1000279}{}{Bang Bang Smash}
{1000279}{}{BBS}
{1000280}{}{Legends of Shady Sands}
{1000281}{}{Legends of Shady Sands}
{1000282}{}{Prime Time Soldiers}
{1000283}{}{Prime Time Soldiers}
{1000284}{}{Modoc Terror Zone}
{1000285}{}{Modoc Terror Zone}
{1000286}{}{Stick em Up Kidz}
{1000287}{}{Stick em Up Kidz}
{1000288}{}{Junction Boys}
{1000289}{}{Junction Boys}
{1000290}{}{Mash Force}
{1000291}{}{Mash Force}
{1000292}{}{The Armiagos}
{1000293}{}{The Armiagos}
{1000294}{}{The Truckstop Transients}
{1000295}{}{The Truckstop Transients}
{1000296}{}{The Rust Nobles}
{1000297}{}{The Rust Nobles}
{1000298}{}{The Suicide Kings}
{1000299}{}{The Suicide Kings}
{1000300}{}{The Bootleheads}
{1000301}{}{The Bootleheads}
{1000302}{}{Grim's Reapers}
{1000303}{}{Grim's Reapers}
{1000304}{}{Jerry's Juveniles}
{1000305}{}{Jerry's Juveniles}
{1000306}{}{Iron Hand's Irregulars}
{1000307}{}{Iron Hand's Irregulars}
{1000308}{}{The Spades}
{1000309}{}{The Spades}
{1000310}{}{The Night Dragons}
{1000311}{}{The Night Dragons}
{1000312}{}{The Hawks}
{1000313}{}{The Hawks}
{1000314}{}{The Sump Sharks}
{1000315}{}{The Sump Sharks}
{1000316}{}{The Sparkle Boys}
{1000317}{}{The Sparkle Boys}
{1000318}{}{The Unique Units}
{1000319}{}{The Unique Units}
{1000320}{}{The Barbarian Lions}
{1000321}{}{The Barbarian Lions}
{1000322}{}{The Muddy Stumpers}
{1000323}{}{The Muddy Stumpers}
{1000324}{}{The Clever Horndogs}
{1000325}{}{The Clever Horndogs}
{1000326}{}{The Diamond Dollies}
{1000327}{}{The Diamond Dollies}
{1000328}{}{The Hangtuffs}
{1000329}{}{The Hangtuffs}
{1000330}{}{The Desert Boys}
{1000331}{}{The Desert Boys}
{1000332}{}{The Terrible Shitheads}
{1000333}{}{The Terrible Shitheads}
{1000334}{}{The Highway Pirates}
{1000335}{}{The Highway Pirates}
{1000336}{}{The Sand Fucks}
{1000337}{}{The Sand Fucks}
{1000338}{}{The Bearskins}
{1000339}{}{The Bearskins}
{1000340}{}{The Bow Wow Rad Dogs}
{1000341}{}{The Bow Wow Rad Dogs}
{1000342}{}{The SF Ra Ras}
{1000343}{}{The SF Ra Ras}
{1000344}{}{The Seekers}
{1000345}{}{The Seekers}
{1000346}{}{The Fists}
{1000347}{}{The Fists}
{1000348}{}{The One Millioners}
{1000349}{}{The One Millioners}
{1000350}{}{The Nutjobs}
{1000351}{}{The Nutjobs}
{1000352}{}{The New Reno Lazy Boys}
{1000353}{}{The New Reno Lazy Boys}
{1000354}{}{The Redding Turn Ups}
{1000355}{}{The Redding Turn Ups}
{1000356}{}{The NCR Short Guns}
{1000357}{}{The NCR Short Guns}
{1000358}{}{The San Fran Fuckups}
{1000359}{}{The San Fran Fuckups}
{1000360}{}{The Broken Hills Flashbangs}
{1000361}{}{The Broken Hills Flashbangs}
{1000361}{}{Broken Hills Flashbangs}
{1000362}{}{The San Francisco Foolers}
{1000363}{}{The San Francisco Foolers}
{1000364}{}{The Vault City Argonauts}
{1000365}{}{The Vault City Argonauts}
{1000366}{}{The Bang Bang Buffout Boys}
{1000367}{}{The Bang Bang Buffout Boys}
{1000367}{}{Bang Bang Buffout Boys}
{1000367}{}{Buffout Boys}
{1000368}{}{The Sacred Spirits}
{1000369}{}{The Sacred Spirits}
{1000370}{}{North Street Shitstorm}
{1000371}{}{North Street Shitstorm}
{1000372}{}{The Gecko Bastards}
{1000373}{}{The Gecko Bastards}
{1000374}{}{The North East Mountain Howlers}
{1000375}{}{The North East Mountain Howlers}
{1000375}{}{North East Mountain Howlers}
{1000375}{}{Mountain Howlers}
{1000376}{}{The Southern Desert Runners}
{1000377}{}{The Southern Desert Runners}
{1000377}{}{Southern Desert Runners}
{1000378}{}{The Massive Backstrokes}
{1000379}{}{The Massive Backstrokes}
{1000380}{}{The Repo Men}
{1000381}{}{The Repo Men}
{1000382}{}{The Iron Lilypads}
{1000383}{}{The Iron Lilypads}
{1000384}{}{The Muscle Malones}
{1000385}{}{The Muscle Malones}
{1000386}{}{The Hellhounds}
{1000387}{}{The Hellhounds}
{1000388}{}{Mom's Diner Clean-Up Boys}
{1000389}{}{Mom's Diner Clean-Up Boys}
{1000390}{}{The Wasteland Bandits}
{1000391}{}{The Wasteland Bandits}
{1000392}{}{The Wasteland Marauders}
{1000393}{}{The Wasteland Marauders}
{1000394}{}{The Wasteland Rockafellas}
{1000395}{}{The Wasteland Rockafellas}
{1000396}{}{The Red Elvises}
{1000397}{}{The Red Elvises}
{1000398}{}{The West Canyon Deathclaws}
{1000399}{}{The West Canyon Deathclaws}
{1000399}{}{West Canyon Deathclaws}
{1000400}{}{The Southern Cave Shakers}
{1000401}{}{The Southern Cave Shakers}
{1000402}{}{The Wasteland Uncles}
{1000403}{}{The Wasteland Uncles}
{1000404}{}{The Kokoweef Yeah Yeahs}
{1000405}{}{The Kokoweef Yeah Yeahs}
{1000406}{}{The VC Halfways}
{1000407}{}{The VC Halfways}
{1000408}{}{The Vault City Jazzers}
{1000409}{}{The Vault City Jazzers}
{1000410}{}{The Modoc Throws}
{1000411}{}{The Modoc Throws}
{1000412}{}{The Wasteland Dice Dogs}
{1000413}{}{The Wasteland Dice Dogs}
{1000414}{}{The Amuchuma}
{1000415}{}{The Amuchuma}
{1000416}{}{The Chinkororo}
{1000417}{}{The Chinkororo}
{1000418}{}{The Dead Tree Rain Downs}
{1000419}{}{The Dead Tree Rain Downs}
{1000420}{}{The VC Bleachers}
{1000421}{}{The VC Bleachers}
{1000422}{}{The Gecko Spitters}
{1000423}{}{The Gecko Spitters}
{1000424}{}{The Fooly Coolies}
{1000425}{}{The Fooly Coolies}
{1000426}{}{The Black Engines}
{1000427}{}{The Black Engines}
{1000428}{}{The New Day Co-Op}
{1000429}{}{The New Day Co-Op}
{1000430}{}{The Dockyard Dip Downs}
{1000431}{}{The Dockyard Dip Downs}
{1000432}{}{The Reno Card Sharps}
{1000433}{}{The Reno Card Sharps}
{1000434}{}{The South Street Card Sharps}
{1000435}{}{The South Street Card Sharps}
{1000435}{}{South Street Card Sharps}
{1000436}{}{The NCR 200s}
{1000437}{}{The NCR 200s}
{1000438}{}{The NCR Happy Guys}
{1000439}{}{The NCR Happy Guys}
{1000440}{}{The No Ways!}
{1000441}{}{The No Ways!}
{1000442}{}{The Sit Down Boys}
{1000443}{}{The Sit Down Boys}
{1000444}{}{The NCR Big Bads}
{1000445}{}{The NCR Big Bads}
{1000446}{}{Team Handsome}
{1000447}{}{Team Handsome}
{1000448}{}{The Broken Hills Rollers}
{1000449}{}{The Broken Hills Rollers}
{1000450}{}{The Vault Rats}
{1000451}{}{The Vault Rats}
{1000451}{}{Vault Rats}
{1000452}{}{The Face Kickers}
{1000453}{}{The Face Kickers}
{1000454}{}{The Head Hurters}
{1000455}{}{The Head Hurters}
{1000456}{}{Post-Work-Knock-Abouts}
{1000457}{}{Post-Work-Knock-Abouts}
{1000458}{}{Men Who Do Lunch}
{1000459}{}{Men Who Do Lunch}
{1000460}{}{The Jukebox Juvies}
{1000461}{}{The Jukebox Juvies}
{1000462}{}{The Go Go Bombers}
{1000463}{}{The Go Go Bombers}
{1000464}{}{The Rad Beat Docs}
{1000465}{}{The Rad Beat Docs}
{1000466}{}{The Mad Bad Radicals}
{1000467}{}{The Mad Bad Radicals}
{1000468}{}{59th Street Killers}
{1000469}{}{59th Street Killers}
{1000470}{}{Copper Cable Thieves}
{1000471}{}{Copper Cable Thieves}
{1000472}{}{The Critical Failure Gang}
{1000473}{}{The Critical Failure Gang}
{1000474}{}{The Church of 1800 Caps}
{1000475}{}{The Church of 1800 Caps}
{1000476}{}{The Choha}
{1000477}{}{The Choha}
{1000477}{}{Choha}
{1000478}{}{Slaves Of The Lost Interrupt}
{1000479}{}{Slaves Of The Lost Interrupt}
{1000479}{}{Slaves of the Lost}
{1000480}{}{Vault Silene Brahminy}
{1000481}{}{Vault Silene Brahminy}
{1000481}{}{Vault of Mad Brahmin}
{1000481}{}{VSB}
{1000482}{}{Cajuns}
{1000483}{}{Cajuns}
{1000484}{}{The Guardians}
{1000485}{}{The Guardians}
{1000486}{}{Ego Slayers}
{1000487}{}{Ego Slayers}
{1000488}{}{The Pie Eaters}
{1000489}{}{The Pie Eaters}
{1000490}{}{The Children Of The War}
{1000491}{}{The Children Of The War}
{1000492}{}{The Avengers}
{1000493}{}{The Avengers}
{1000494}{}{The We Do Doing}
{1000495}{}{The We Do Doing}
{1000496}{}{The Black Sun Gang}
{1000497}{}{The Black Sun Gang}
{1000498}{}{The Radicals}
{1000499}{}{The Radicals}
{1000500}{}{The Space Monkeys}
{1000501}{}{The Space Monkeys}
{1000501}{}{Space Monkeys}
{1000502}{}{The Acid Drinkers}
{1000503}{}{The Acid Drinkers}
{1000504}{}{The Dead Rats}
{1000505}{}{The Dead Rats}
{1000505}{}{Dead Rats}
{1000506}{}{The Radiated Rangers}
{1000507}{}{The Radiated Rangers}
{1000508}{}{The Collectors}
{1000509}{}{The Collectors}
{1000510}{}{The Flowers Lovers}
{1000511}{}{The Flowers Lovers}
{1000512}{}{The Eyes Shooters}
{1000513}{}{The Eyes Shooters}
{1000514}{}{The Black Inquisitors}
{1000515}{}{The Black Inquisitors}
{1000515}{}{Black Inquisitors}
{1000516}{}{The Field Medics}
{1000517}{}{The Field Medics}
{1000518}{}{The Butcher Doctors}
{1000519}{}{The Butcher Doctors}
{1000520}{}{The Hashpipes}
{1000521}{}{The Hashpipes}
{1000522}{}{The Professors Gang}
{1000523}{}{The Professors Gang}
{1000524}{}{The Modus Operandi}
{1000525}{}{The Modus Operandi}
{1000525}{}{Modus Operandi}
{1000526}{}{The Boom Boom Suiciders}
{1000527}{}{The Boom Boom Suiciders}
{1000527}{}{Boom Boom Suiciders}
{1000528}{}{The Suicide Bombers}
{1000529}{}{The Suicide Bombers}
{1000530}{}{Tim & Tom & Ted Lawyer Agency}
{1000531}{}{Tim & Tom & Ted Lawyer Agency}
{1000531}{}{Tim & Tom & Ted}
{1000531}{}{Lawyer Agency}
{1000531}{}{TTTLA}
{1000532}{}{Union of Past Future}
{1000533}{}{Union of Past Future}
{1000534}{}{Union Of A New Tomorrow}
{1000535}{}{Union Of A New Tomorrow}
{1000536}{}{The Meatbags}
{1000537}{}{The Meatbags}
{1000538}{}{The Cappers}
{1000539}{}{The Cappers}
{1000540}{}{The Rotten Throat Camp}
{1000541}{}{The Rotten Throat Camp}
{1000542}{}{The Order of Forever}
{1000543}{}{The Order of Forever}
{1000544}{}{The Throats Slashers}
{1000545}{}{The Throats Slashers}
{1000545}{}{Throats Slashers}
{1000546}{}{The Peacekeepers}
{1000547}{}{The Peacekeepers}
{1000548}{}{The Good Guys}
{1000549}{}{The Good Guys}
{1000550}{}{The Bad Guys}
{1000551}{}{The Bad Guys}
{1000552}{}{The Jinxers}
{1000553}{}{The Jinxers}
{1000554}{}{The Greasy Bastards}
{1000555}{}{The Greasy Bastards}
{1000556}{}{The Bonzai Trees Keepers}
{1000557}{}{The Bonzai Trees Keepers}
{1000557}{}{Bonzai Trees Keepers}
{1000558}{}{The Red Riders}
{1000559}{}{The Red Riders}
{1000560}{}{Word of New Order}
{1000561}{}{Word of New Order}
{1000562}{}{The Lost Guards}
{1000563}{}{The Lost Guards}
{1000564}{}{The Rot Guts Eaters}
{1000565}{}{The Rot Guts Eaters}
{1000566}{}{The Redding Minewatchers}
{1000567}{}{The Redding Minewatchers}
{1000568}{}{The Gecko Patrols}
{1000569}{}{The Gecko Patrols}
{1000570}{}{The NCR Raiders}
{1000571}{}{The NCR Raiders}
{1000572}{}{The Trapper Camp of Klamath}
{1000573}{}{The Trapper Camp of Klamath}
{1000573}{}{Trapper Camp of Klamath}
{1000574}{}{The Redding Terraformers}
{1000575}{}{The Redding Terraformers}
{1000576}{}{The Junktown Junkies}
{1000577}{}{The Junktown Junkies}
{1000578}{}{The San Fran Blues Band}
{1000579}{}{The San Fran Blues Band}
{1000580}{}{The San Francisco Sailors}
{1000581}{}{The San Francisco Sailors}
{1000582}{}{The Klamath Fried Geckos}
{1000583}{}{The Klamath Fried Geckos}
{1000583}{}{Klamath Fried Geckos}
{1000584}{}{Wasteland Degenerates}
{1000585}{}{Wasteland Degenerates}
{1000586}{}{Wasteland Wildlife Protectors}
{1000587}{}{Wasteland Wildlife Protectors}
{1000587}{}{WWP}
{1000588}{}{The Chosen Ones}
{1000589}{}{The Chosen Ones}
{1000589}{}{Chosen Ones}
{1000590}{}{The Church of Mushroom Cloud}
{1000591}{}{The Church of Mushroom Cloud}
{1000591}{}{TCMC}
{1000592}{}{Children Of Atom}
{1000593}{}{Children Of Atom}
{1000594}{}{Children Of The Wastes}
{1000595}{}{Children Of The Wastes}
{1000596}{}{The Irradiated Brains Scum}
{1000597}{}{The Irradiated Brains Scum}
{1000597}{}{Irradiated Brains Scum}
{1000598}{}{The Wasteland patrol}
{1000599}{}{The Wasteland patrol}
{1000599}{}{Wasteland Patrol}
{1000600}{}{The Iguana Bits}
{1000601}{}{The Iguana Bits}
{1000602}{}{The Grey Rock Tribe}
{1000603}{}{The Grey Rock Tribe}
{1000603}{}{Grey Rock Tribe}
{1000604}{}{The People Of Dust}
{1000605}{}{The People Of Dust}
{1000606}{}{The Bluesuits}
{1000607}{}{The Bluesuits}
{1000608}{}{The Vault Robbers}
{1000609}{}{The Vault Robbers}
{1000610}{}{The Southern Opression Gang}
{1000611}{}{The Southern Opression Gang}
{1000611}{}{Southern Opression Gang}
{1000612}{}{The Northern Opression Gang}
{1000613}{}{The Northern Opression Gang}
{1000613}{}{Northern Opression Gang}
{1000614}{}{The Judgement Day Club}
{1000615}{}{The Judgement Day Club}
{1000616}{}{The Lucky Gamblers}
{1000617}{}{The Lucky Gamblers}
{1000618}{}{The Brahmins Butchers}
{1000619}{}{The Brahmins Butchers}
{1000620}{}{The Brahminhood of Shit}
{1000621}{}{The Brahminhood of Shit}
{1000622}{}{Wasteland Marine Corp}
{1000623}{}{Wasteland Marine Corp}
{1000624}{}{The Naughty Vault Dwellers}
{1000625}{}{The Naughty Vault Dwellers}
{1000625}{}{Naughty Vault Dwellers}
{1000626}{}{The Wastelands Freaks}
{1000627}{}{The Wastelands Freaks}
{1000628}{}{The Wasteland Hurricane}
{1000629}{}{The Wasteland Hurricane}
{1000630}{}{Dead Master's Crew}
{1000631}{}{Dead Master's Crew}
{1000632}{}{The Nukes}
{1000633}{}{The Nukes}
{1000634}{}{The Busted Raiders}
{1000635}{}{The Busted Raiders}
{1000636}{}{Red Dot Army}
{1000637}{}{Red Dot Army}
{1000637}{}{RDA}
{1000638}{}{R.E.P.O.}
{1000639}{}{R.E.P.O.}
{1000639}{}{Regional Energy Program Office}
{1000640}{}{The Bad Habits}
{1000641}{}{The Bad Habits}
{1000642}{}{The Brahmin Shit Hunters}
{1000643}{}{The Brahmin Shit Hunters}
{1000644}{}{The Booze Lovers}
{1000645}{}{The Booze Lovers}
{1000646}{}{The Chess Club}
{1000647}{}{The Chess Club}
{1000648}{}{The Chopstick Triad}
{1000649}{}{The Chopstick Triad}
{1000650}{}{The Drunken Bastards}
{1000651}{}{The Drunken Bastards}
{1000652}{}{The Gecko Skinners}
{1000653}{}{The Gecko Skinners}
{1000654}{}{Ghoulish Legionnaires}
{1000655}{}{Ghoulish Legionnaires}
{1000656}{}{The Gopnik Swarm}
{1000657}{}{The Gopnik Swarm}
{1000658}{}{The Hub Kneebreakers}
{1000659}{}{The Hub Kneebreakers}
{1000660}{}{The Junk Dealers}
{1000661}{}{The Junk Dealers}
{1000662}{}{The Junkie Beaters}
{1000663}{}{The Junkie Beaters}
{1000664}{}{The Knights Who Say Ni}
{1000665}{}{The Knights Who Say Ni}
{1000666}{}{The Lazy Alt Users}
{1000667}{}{The Lazy Alt Users}
{1000668}{}{The Los Alamos Warriors}
{1000669}{}{The Los Alamos Warriors}
{1000670}{}{The Manflyers}
{1000671}{}{The Manflyers}
{1000672}{}{The Mayans}
{1000673}{}{The Mayans}
{1000674}{}{The Modoc Militia}
{1000675}{}{The Modoc Militia}
{1000676}{}{The Modoc Hillbillies}
{1000677}{}{The Modoc Hillbillies}
{1000678}{}{The Murderous Hobos}
{1000679}{}{The Murderous Hobos}
{1000680}{}{The New Reno Nasties}
{1000681}{}{The New Reno Nasties}
{1000682}{}{The Nordic Marauders}
{1000683}{}{The Nordic Marauders}
{1000684}{}{The Nuka Cola Addicts}
{1000685}{}{The Nuka Cola Addicts}
{1000686}{}{The One-Niners}
{1000687}{}{The One-Niners}
{1000688}{}{The Outhouse Boys}
{1000689}{}{The Outhouse Boys}
{1000690}{}{The Pagans}
{1000691}{}{The Pagans}
{1000692}{}{The Peasant Butchers}
{1000693}{}{The Peasant Butchers}
{1000694}{}{The Redeyed Barbarians}
{1000695}{}{The Redeyed Barbarians}
{1000696}{}{The Redneck Yokels}
{1000697}{}{The Redneck Yokels}
{1000698}{}{The Reno Gumshoes}
{1000699}{}{The Reno Gumshoes}
{1000700}{}{Sadistic Skull Bangers}
{1000701}{}{Sadistic Skull Bangers}
{1000702}{}{The Schroedinger Cats}
{1000703}{}{The Schroedinger Cats}
{1000704}{}{Small Group With Big Guns}
{1000705}{}{Small Group With Big Guns}
{1000706}{}{The Smoothskins}
{1000707}{}{The Smoothskins}
{1000708}{}{The Sons of Anarchy}
{1000709}{}{The Sons of Anarchy}
{1000710}{}{The Spanish Inquisition}
{1000711}{}{The Spanish Inquisition}
{1000712}{}{The Three Dimensions}
{1000713}{}{The Three Dimensions}
{1000714}{}{The Throatslit Happies}
{1000715}{}{The Throatslit Happies}
{1000716}{}{The Wasteland Abusers}
{1000717}{}{The Wasteland Abusers}
{1000718}{}{The Wasteland Girls}
{1000719}{}{The Wasteland Girls}
{1000720}{}{The Wasteland Scumbags}
{1000721}{}{The Wasteland Scumbags}
{1000722}{}{The World Eaters}
{1000723}{}{The World Eaters}
{1000724}{}{The Zip Gun Bandits}
{1000725}{}{The Zip Gun Bandits}
{1000726}{}{The Den Headaches}
{1000727}{}{The Den Headaches}
{1000728}{}{The Suicidal Assault Team}
{1000729}{}{The Suicidal Assault Team}
{1000730}{}{The Redding Agents}
{1000731}{}{The Redding Agents}
{1000732}{}{The Crazy Bartenders}
{1000733}{}{The Crazy Bartenders}
{1000734}{}{The Powerful Illusions}
{1000735}{}{The Powerful Illusions}
{1000736}{}{The Lucky Wings}
{1000737}{}{The Lucky Wings}
{1000738}{}{The Amusing Patrol}
{1000739}{}{The Amusing Patrol}
{1000740}{}{The Imperial Slashers}
{1000741}{}{The Imperial Slashers}
{1000742}{}{The Powder Investigators}
{1000743}{}{The Powder Investigators}
{1000744}{}{The Stormy Slashers}
{1000745}{}{The Stormy Slashers}
{1000746}{}{The Thirsty Lieutenants}
{1000747}{}{The Thirsty Lieutenants}
{1000748}{}{The Metal Gang}
{1000749}{}{The Metal Gang}
{1000750}{}{The Bleeding Hurricanes}
{1000751}{}{The Bleeding Hurricanes}
{1000752}{}{The Broken Hills Hunters}
{1000753}{}{The Broken Hills Hunters}
{1000754}{}{The Hub Jumpers}
{1000755}{}{The Hub Jumpers}
{1000756}{}{The Redding Tribe}
{1000757}{}{The Redding Tribe}
{1000758}{}{The Greasy Angels}
{1000759}{}{The Greasy Angels}
{1000760}{}{The Strange Suiciders}
{1000761}{}{The Strange Suiciders}
{1000762}{}{The Bleeding Watchers}
{1000763}{}{The Bleeding Watchers}
{1000764}{}{The Brahmin's Vault Dwellers}
{1000765}{}{The Brahmin's Vault Dwellers}
{1000765}{}{Brahmin's Vault Dwellers}
{1000766}{}{The Wasteland Sharpshooters}
{1000767}{}{The Wasteland Sharpshooters}
{1000767}{}{Wasteland Sharpshooters}
{1000768}{}{The East Panthers}
{1000769}{}{The East Panthers}
{1000770}{}{The Three Guys}
{1000771}{}{The Three Guys}
{1000772}{}{The Amusing Jumpers}
{1000773}{}{The Amusing Jumpers}
{1000774}{}{The Unlucky Raiders}
{1000775}{}{The Unlucky Raiders}
{1000776}{}{The Booze Patrol}
{1000777}{}{The Booze Patrol}
{1000778}{}{The Sixth Tribe}
{1000779}{}{The Sixth Tribe}
{1000780}{}{The Reactor Jumpers}
{1000781}{}{The Reactor Jumpers}
{1000782}{}{The Gecko Children}
{1000783}{}{The Gecko Children}
{1000784}{}{The Jealous Beasts}
{1000785}{}{The Jealous Beasts}
{1000786}{}{The Black Virgins}
{1000787}{}{The Black Virgins}
{1000788}{}{The Burning Women}
{1000789}{}{The Burning Women}
{1000790}{}{The Bad Deputies}
{1000791}{}{The Bad Deputies}
{1000792}{}{The Wild Nomads}
{1000793}{}{The Wild Nomads}
{1000794}{}{The Four Warriors}
{1000795}{}{The Four Warriors}
{1000796}{}{The Reading Androids}
{1000797}{}{The Reading Androids}
{1000798}{}{The Psychopath Devils}
{1000799}{}{The Psychopath Devils}
{1000800}{}{The Necropolis Professors}
{1000801}{}{The Necropolis Professors}
{1000802}{}{The Broken Hills Killers}
{1000803}{}{The Broken Hills Killers}
{1000804}{}{The Sneaky Huntresses}
{1000805}{}{The Sneaky Huntresses}
{1000806}{}{The Powerful Protectors}
{1000807}{}{The Powerful Protectors}
{1000808}{}{The Vault City Virgins}
{1000809}{}{The Vault City Virgins}
{1000810}{}{The Wild Communists}
{1000811}{}{The Wild Communists}
{1000812}{}{The Crazy Slashers}
{1000813}{}{The Crazy Slashers}
{1000814}{}{The Old Eagles}
{1000815}{}{The Old Eagles}
{1000816}{}{The Eight Strangers}
{1000817}{}{The Eight Strangers}
{1000818}{}{The Tedious Wings}
{1000819}{}{The Tedious Wings}
{1000820}{}{The Wasteland Professors}
{1000821}{}{The Wasteland Professors}
{1000822}{}{The Gecko Huntresses}
{1000823}{}{The Gecko Huntresses}
{1000824}{}{The Winning Amazons}
{1000825}{}{The Winning Amazons}
{1000826}{}{The Radiated Scientists}
{1000827}{}{The Radiated Scientists}
{1000828}{}{The Heroic Tornadoes}
{1000829}{}{The Heroic Tornadoes}
{1000830}{}{The Desert Alliance}
{1000831}{}{The Desert Alliance}
{1000832}{}{The Burning One-Eyed}
{1000833}{}{The Burning One-Eyed}
{1000834}{}{The South Eagles}
{1000835}{}{The South Eagles}
{1000836}{}{The Nine Ghouls}
{1000837}{}{The Nine Ghouls}
{1000838}{}{The Strange Children}
{1000839}{}{The Strange Children}
{1000840}{}{The West Necromancers}
{1000841}{}{The West Necromancers}
{1000842}{}{The Wild Elders}
{1000843}{}{The Wild Elders}
{1000844}{}{The Holy Suiciders}
{1000845}{}{The Holy Suiciders}
{1000846}{}{The Jealous Punks}
{1000847}{}{The Jealous Punks}
{1000848}{}{The Thirsty Chess Players}
{1000849}{}{The Thirsty Chess Players}
{1000850}{}{The Secret Angels}
{1000851}{}{The Secret Angels}
{1000852}{}{The Lost Hills Hurricanes}
{1000853}{}{The Lost Hills Hurricanes}
{1000854}{}{The Greedy Incinerators}
{1000855}{}{The Greedy Incinerators}
{1000856}{}{The Midnight Tornadoes}
{1000857}{}{The Midnight Tornadoes}
{1000858}{}{The Master's Girls}
{1000859}{}{The Master's Girls}
{1000860}{}{The Lucky Guys}
{1000861}{}{The Lucky Guys}
{1000862}{}{The Tall Snipers}
{1000863}{}{The Tall Snipers}
{1000864}{}{The Lost Hills Mutants}
{1000865}{}{The Lost Hills Mutants}
{1000866}{}{The Tedious Gods}
{1000867}{}{The Tedious Gods}
{1000868}{}{The Mad Watchers}
{1000869}{}{The Mad Watchers}
{1000870}{}{The Terrible Patrol}
{1000871}{}{The Terrible Patrol}
{1000872}{}{The Nasty Bulls}
{1000873}{}{The Nasty Bulls}
{1000874}{}{The Ultimate Monks}
{1000875}{}{The Ultimate Monks}
{1000876}{}{The Green Wings}
{1000877}{}{The Green Wings}
{1000878}{}{The Eight Punks}
{1000879}{}{The Eight Punks}
{1000880}{}{The Dark Squad}
{1000881}{}{The Dark Squad}
{1000882}{}{The Lost Hills Investigators}
{1000883}{}{The Lost Hills Investigators}
{1000883}{}{Lost Hills Investigators}
{1000884}{}{The Lawful Bartenders}
{1000885}{}{The Lawful Bartenders}
{1000886}{}{The Junktown Professors}
{1000887}{}{The Junktown Professors}
{1000888}{}{The Wild Amazons}
{1000889}{}{The Wild Amazons}
{1000890}{}{The Big Cats}
{1000891}{}{The Big Cats}
{1000892}{}{The Wasteland Eaters}
{1000893}{}{The Wasteland Eaters}
{1000894}{}{The Broken Hills Virgins}
{1000895}{}{The Broken Hills Virgins}
{1000896}{}{The Failing Bulls}
{1000897}{}{The Failing Bulls}
{1000898}{}{The Angry Meteors}
{1000899}{}{The Angry Meteors}
{1000900}{}{The Stormy Brothers}
{1000901}{}{The Stormy Brothers}
{1000902}{}{The Hungry Thugs}
{1000903}{}{The Hungry Thugs}
{1000904}{}{The Lucky Maniacs}
{1000905}{}{The Lucky Maniacs}
{1000906}{}{The Junkie Council}
{1000907}{}{The Junkie Council}
{1000908}{}{The Big Army}
{1000909}{}{The Big Army}
{1000910}{}{The Klamath Eaters}
{1000911}{}{The Klamath Eaters}
{1000912}{}{The Hub Children}
{1000913}{}{The Hub Children}
{1000914}{}{The Tedious Brothers}
{1000915}{}{The Tedious Brothers}
{1000916}{}{The Reading Men}
{1000917}{}{The Reading Men}
{1000918}{}{The Pyromaniac Bartenders}
{1000919}{}{The Pyromaniac Bartenders}
{1000920}{}{The Slashing Criminals}
{1000921}{}{The Slashing Criminals}
{1000922}{}{The Blind Watchers}
{1000923}{}{The Blind Watchers}
{1000924}{}{The Winning Cats}
{1000925}{}{The Winning Cats}
{1000926}{}{The Lawful Mobsters}
{1000927}{}{The Lawful Mobsters}
{1000928}{}{The Old Crew}
{1000929}{}{The Old Crew}
{1000930}{}{The Desert Raiders}
{1000931}{}{The Desert Raiders}
{1000932}{}{The Ultimate Shadows}
{1000933}{}{The Ultimate Shadows}
{1000934}{}{The Holy Squadron}
{1000935}{}{The Holy Squadron}
{1000936}{}{The Old Virgins}
{1000937}{}{The Old Virgins}
{1000938}{}{The Nasty Brothers}
{1000939}{}{The Nasty Brothers}
{1000940}{}{The Nuka-Cola Inquisitors}
{1000941}{}{The Nuka-Cola Inquisitors}
{1000942}{}{Paladins of Justice}
{1000943}{}{Paladins of Justice}
{1000944}{}{The Psychopath Shadows}
{1000945}{}{The Psychopath Shadows}
{1000946}{}{The North Men}
{1000947}{}{The North Men}
{1000948}{}{The Black Lovers}
{1000949}{}{The Black Lovers}
{1000950}{}{The Failing Cats}
{1000951}{}{The Failing Cats}
{1000952}{}{The Stormy Guys}
{1000953}{}{The Stormy Guys}
{1000954}{}{The California Bears}
{1000955}{}{The California Bears}
{1000956}{}{The Starved Criminals}
{1000957}{}{The Starved Criminals}
{1000958}{}{The Violent Rats}
{1000959}{}{The Violent Rats}
{1000960}{}{The Greasy Incinerators}
{1000961}{}{The Greasy Incinerators}
{1000962}{}{The Suicidal Rangers}
{1000963}{}{The Suicidal Rangers}
{1000964}{}{The Heroic Hunters}
{1000965}{}{The Heroic Hunters}
{1000966}{}{The Small Humans}
{1000967}{}{The Small Humans}
{1000968}{}{The Dark Brotherhood}
{1000969}{}{The Dark Brotherhood}
{1000970}{}{The Broken Hills Panthers}
{1000971}{}{The Broken Hills Panthers}
{1000972}{}{The Unlucky Lovers}
{1000973}{}{The Unlucky Lovers}
{1000974}{}{The Peaceful Patrol}
{1000975}{}{The Peaceful Patrol}
{1000976}{}{The Nuka-Cola Lovers}
{1000977}{}{The Nuka-Cola Lovers}
{1000978}{}{The Nine Sharpshooters}
{1000979}{}{The Nine Sharpshooters}
{1000980}{}{The Thirsty Bodyguards}
{1000981}{}{The Thirsty Bodyguards}
{1000982}{}{The Ultimate Nomads}
{1000983}{}{The Ultimate Nomads}
{1000984}{}{The Heroic Cats}
{1000985}{}{The Heroic Cats}
{1000986}{}{The South Triad}
{1000987}{}{The South Triad}
{1000988}{}{The Reactor Headaches}
{1000989}{}{The Reactor Headaches}
{1000990}{}{The Irradiated Pacifists}
{1000991}{}{The Irradiated Pacifists}
{1000992}{}{The Winning Barons}
{1000993}{}{The Winning Barons}
{1000994}{}{The Silent Hobos}
{1000995}{}{The Silent Hobos}
{1000996}{}{The Gecko Devils}
{1000997}{}{The Gecko Devils}
{1000998}{}{The Boneyard Protectors}
{1000999}{}{The Boneyard Protectors}
{1001000}{}{The Invincible Gladiators}
{1001001}{}{The Invincible Gladiators}
{1001002}{}{The Nine Suiciders}
{1001003}{}{The Nine Suiciders}
{1001004}{}{The Seven Agents}
{1001005}{}{The Seven Agents}
{1001006}{}{The Lucky League}
{1001007}{}{The Lucky League}
{1001008}{}{The Radiated Humans}
{1001009}{}{The Radiated Humans}
{1001010}{}{The New Legion}
{1001011}{}{The New Legion}
{1001012}{}{The Pyromaniac Beasts}
{1001013}{}{The Pyromaniac Beasts}
{1001014}{}{The New Sharpshooters}
{1001015}{}{The New Sharpshooters}
{1001016}{}{The Slashing Brothers}
{1001017}{}{The Slashing Brothers}
{1001018}{}{The Three Amazons}
{1001019}{}{The Three Amazons}
{1001020}{}{The Winning Eagles}
{1001021}{}{The Winning Eagles}
{1001022}{}{The Gloomy Amazons}
{1001023}{}{The Gloomy Amazons}
{1001024}{}{The Reading Meteors}
{1001025}{}{The Reading Meteors}
{1001026}{}{The Master's Fingers}
{1001027}{}{The Master's Fingers}
{1001028}{}{The Suicidal Triad}
{1001029}{}{The Suicidal Triad}
{1001030}{}{The Desert Protectors}
{1001031}{}{The Desert Protectors}
{1001032}{}{The Junkie Geckos}
{1001033}{}{The Junkie Geckos}
{1001034}{}{The Klamath Monks}
{1001035}{}{The Klamath Monks}
{1001036}{}{The Irradiated Vault Dwellers}
{1001037}{}{The Irradiated Vault Dwellers}
{1001037}{}{Irradiated Vault Dwellers}
{1001038}{}{The Evil Professors}
{1001039}{}{The Evil Professors}
{1001040}{}{The Abominable Eaters}
{1001041}{}{The Abominable Eaters}
{1001042}{}{The Peaceful Bulls}
{1001043}{}{The Peaceful Bulls}
{1001044}{}{The Dark Gang}
{1001045}{}{The Dark Gang}
{1001046}{}{The Gecko Snakes}
{1001047}{}{The Gecko Snakes}
{1001048}{}{The Jealous Army}
{1001049}{}{The Jealous Army}
{1001050}{}{The Desert Bears}
{1001051}{}{The Desert Bears}
{1001052}{}{The Imperial Investigators}
{1001053}{}{The Imperial Investigators}
{1001053}{}{Imperial Investigators}
{1001054}{}{The Nine Pacifists}
{1001055}{}{The Nine Pacifists}
{1001056}{}{The Powder Meteors}
{1001057}{}{The Powder Meteors}
{1001058}{}{The Boneyard Criminals}
{1001059}{}{The Boneyard Criminals}
{1001060}{}{The Mad Ghouls}
{1001061}{}{The Mad Ghouls}
{1001062}{}{The Nine Meteors}
{1001063}{}{The Nine Meteors}
{1001064}{}{The Junktown Club}
{1001065}{}{The Junktown Club}
{1001066}{}{The Crazy Radscorpions}
{1001067}{}{The Crazy Radscorpions}
{1001068}{}{The Irradiated Virgins}
{1001069}{}{The Irradiated Virgins}
{1001070}{}{The Winged Criminals}
{1001071}{}{The Winged Criminals}
{1001072}{}{The Evil Butchers}
{1001073}{}{The Evil Butchers}
{1001074}{}{The Hub Triad}
{1001075}{}{The Hub Triad}
{1001076}{}{The Lost Hills Huntresses}
{1001077}{}{The Lost Hills Huntresses}
{1001078}{}{The Weird Gods}
{1001079}{}{The Weird Gods}
{1001080}{}{The Small Doctors}
{1001081}{}{The Small Doctors}
{1001082}{}{The Eight Gangmen}
{1001083}{}{The Eight Gangmen}
{1001084}{}{The Red Sharpshooters}
{1001085}{}{The Red Sharpshooters}
{1001086}{}{The Crazy Raiders}
{1001087}{}{The Crazy Raiders}
{1001088}{}{The Metal Nomads}
{1001089}{}{The Metal Nomads}
{1001090}{}{The Failing Lions}
{1001091}{}{The Failing Lions}
{1001092}{}{The Stormy Slavers}
{1001093}{}{The Stormy Slavers}
{1001094}{}{The Western Mobsters}
{1001095}{}{The Western Mobsters}
{1001096}{}{The False Crew}
{1001097}{}{The False Crew}
{1001098}{}{The Burning Men}
{1001099}{}{The Burning Men}
{1001100}{}{The Secret Wings}
{1001101}{}{The Secret Wings}
{1001102}{}{The Winged Mobsters}
{1001103}{}{The Winged Mobsters}
{1001104}{}{The Burning Witches}
{1001105}{}{The Burning Witches}
{1001106}{}{The Lucky Hurricanes}
{1001107}{}{The Lucky Hurricanes}
{1001108}{}{The Winged Strangers}
{1001109}{}{The Winged Strangers}
{1001110}{}{The Tough Jumpers}
{1001111}{}{The Tough Jumpers}
{1001112}{}{The Wasteland Shadows}
{1001113}{}{The Wasteland Shadows}
{1001114}{}{The Heroic Midgets}
{1001115}{}{The Heroic Midgets}
{1001116}{}{The Imperial Pyromaniacs}
{1001117}{}{The Imperial Pyromaniacs}
{1001118}{}{The Seven Rangers}
{1001119}{}{The Seven Rangers}
{1001120}{}{The Lawful Thugs}
{1001121}{}{The Lawful Thugs}
{1001122}{}{The Strange Eyes}
{1001123}{}{The Strange Eyes}
{1001124}{}{The Metal Thugs}
{1001125}{}{The Metal Thugs}
{1001126}{}{New Reno Gangsters}
{1001127}{}{New Reno Gangsters}
{1001128}{}{Richard's Friends}
{1001129}{}{Richard's Friends}
{1001130}{}{The Herdsmen Association}
{1001131}{}{The Herdsmen Association}
{1001132}{}{Tandi's Secret Lovers}
{1001133}{}{Tandi's Secret Lovers}
{1001134}{}{The One-man-gang}
{1001135}{}{The One-man-gang}
{1001136}{}{The Running Shadows}
{1001137}{}{The Running Shadows}
{1001138}{}{Honest Citizens}
{1001139}{}{Honest Citizens}
{1001140}{}{The Redding Mobsters}
{1001141}{}{The Redding Mobsters}
{1001142}{}{The Miners}
{1001143}{}{The Miners}
{1001144}{}{The Brahmin Eaters}
{1001145}{}{The Brahmin Eaters}
{1001146}{}{The Bloody Hunters}
{1001147}{}{The Bloody Hunters}
{1001148}{}{The California Crows}
{1001149}{}{The California Crows}
{1001150}{}{Two-Headed Bears}
{1001151}{}{Two-Headed Bears}
{1001152}{}{The Black Bullets}
{1001153}{}{The Black Bullets}
{1001154}{}{The Iron Fists}
{1001155}{}{The Iron Fists}
{1001156}{}{The Ice Breakers}
{1001157}{}{The Ice Breakers}
{1001158}{}{San Francisco Mob}
{1001159}{}{San Francisco Mob}
{1001160}{}{The Wise Men}
{1001161}{}{The Wise Men}
{1001162}{}{The Green Hand}
{1001163}{}{The Green Hand}
{1001164}{}{The Not-So-Dead}
{1001165}{}{The Not-So-Dead}
{1001166}{}{The Still Alive}
{1001167}{}{The Still Alive}
{1001168}{}{The Scars}
{1001169}{}{The Scars}
{1001170}{}{The Dangerous Drivers}
{1001171}{}{The Dangerous Drivers}
{1001172}{}{The Silent Hunters}
{1001173}{}{The Silent Hunters}
{1001174}{}{The Noisy Killers}
{1001175}{}{The Noisy Killers}
{1001176}{}{The Lazy Ghouls}
{1001177}{}{The Lazy Ghouls}
{1001178}{}{The Hidden Kings}
{1001179}{}{The Hidden Kings}
{1001180}{}{The Klamath Shadows}
{1001181}{}{The Klamath Shadows}
{1001182}{}{The Modoc Guardians}
{1001183}{}{The Modoc Guardians}
{1001184}{}{The Skulls}
{1001185}{}{The Skulls}
{1001186}{}{The One-Eyed Snipers}
{1001187}{}{The One-Eyed Snipers}
{1001188}{}{The Dark Watchers}
{1001189}{}{The Dark Watchers}
{1001190}{}{The Werewolves}
{1001191}{}{The Werewolves}
{1001192}{}{The Gunslingers}
{1001193}{}{The Gunslingers}
{1001194}{}{The Mechanical Witches}
{1001195}{}{The Mechanical Witches}
{1001196}{}{The Drug Addicts}
{1001197}{}{The Drug Addicts}
{1001198}{}{Honest Thieves Organisation}
{1001199}{}{Honest Thieves Organisation}
{1001199}{}{Honest Thieves}
{1001200}{}{The Holodisks Readers}
{1001201}{}{The Holodisks Readers}
{1001201}{}{The Holodisks Reader}
{1001202}{}{The Holodisks Writers}
{1001203}{}{The Holodisks Writers}
{1001204}{}{The Murderous Knights}
{1001205}{}{The Murderous Knights}
{1001206}{}{The Green Mutants}
{1001207}{}{The Green Mutants}
{1001208}{}{The Fight Club}
{1001209}{}{The Fight Club}
{1001210}{}{The First Aid Gang}
{1001211}{}{The First Aid Gang}
{1001212}{}{Anonymous Vault Dwellers}
{1001213}{}{Anonymous Vault Dwellers}
{1001214}{}{The Men Of Their Words}
{1001215}{}{The Men Of Their Words}
{1001216}{}{The Amazing Eaters}
{1001217}{}{The Amazing Eaters}
{1001218}{}{The Mad Cooks}
{1001219}{}{The Mad Cooks}
{1001220}{}{The Poisoned Spears}
{1001221}{}{The Poisoned Spears}
{1001222}{}{The Holy Women}
{1001223}{}{The Holy Women}
{1001224}{}{The Tough Slugs}
{1001225}{}{The Tough Slugs}
{1001226}{}{The Rail Road Bandits}
{1001227}{}{The Rail Road Bandits}
{1001228}{}{The Towers}
{1001229}{}{The Towers}
{1001230}{}{The Mad Horsemen}
{1001231}{}{The Mad Horsemen}
{1001232}{}{The Shotgun Blast Gang}
{1001233}{}{The Shotgun Blast Gang}
{1001234}{}{The Shot Ones}
{1001235}{}{The Shot Ones}
{1001236}{}{The Dead Birds}
{1001237}{}{The Dead Birds}
{1001238}{}{The Bald Men}
{1001239}{}{The Bald Men}
{1001240}{}{Vietnam Warriors}
{1001241}{}{Vietnam Warriors}
{1001242}{}{Six Guys Company}
{1001243}{}{Six Guys Company}
{1001244}{}{Six Girls Company}
{1001245}{}{Six Girls Company}
{1001246}{}{North Alliance}
{1001247}{}{North Alliance}
{1001248}{}{Dark Alliance}
{1001249}{}{Dark Alliance}
{1001250}{}{The Stoneheads}
{1001251}{}{The Stoneheads}
{1001252}{}{The Crazy 88}
{1001253}{}{The Crazy 88}
{1001254}{}{The Sniping Avengers}
{1001255}{}{The Sniping Avengers}
{1001256}{}{The Crazy Barbarians}
{1001257}{}{The Crazy Barbarians}
{1001258}{}{The Pyromaniacs}
{1001259}{}{The Pyromaniacs}
{1001260}{}{The Casino Mobsters}
{1001261}{}{The Casino Mobsters}
{1001262}{}{Sneaky Gits}
{1001263}{}{Sneaky Gits}
{1001264}{}{The Nuka-Cola Gang}
{1001265}{}{The Nuka-Cola Gang}
{1001266}{}{The Broken Hills Eagles}
{1001267}{}{The Broken Hills Eagles}
{1001268}{}{The Lucky Slavers}
{1001269}{}{The Lucky Slavers}
{1001270}{}{The California Warriors}
{1001271}{}{The California Warriors}
{1001272}{}{The Green Humans}
{1001273}{}{The Green Humans}
{1001274}{}{The Weird Barbarians}
{1001275}{}{The Weird Barbarians}
{1001276}{}{The Pyromaniac Gang}
{1001277}{}{The Pyromaniac Gang}
{1001278}{}{The Crazy Hobos}
{1001279}{}{The Crazy Hobos}
{1001280}{}{The Bleeding Hands}
{1001281}{}{The Bleeding Hands}
{1001282}{}{The Weird Addicts}
{1001283}{}{The Weird Addicts}
{1001284}{}{The North Bandits}
{1001285}{}{The North Bandits}
{1001286}{}{The Secret Inquisitors}
{1001287}{}{The Secret Inquisitors}
{1001288}{}{The Tedious Slashers}
{1001289}{}{The Tedious Slashers}
{1001290}{}{The Radiated Vault Dwellers}
{1001291}{}{The Radiated Vault Dwellers}
{1001291}{}{Radiated Vault Dwellers}
{1001292}{}{The Secret Guys}
{1001293}{}{The Secret Guys}
{1001294}{}{The Junkie Women}
{1001295}{}{The Junkie Women}
{1001296}{}{The South Hands}
{1001297}{}{The South Hands}
{1001298}{}{The Amusing Thugs}
{1001299}{}{The Amusing Thugs}
{1001300}{}{The Failing Club}
{1001301}{}{The Failing Club}
{1001302}{}{The Wasteland Mutants}
{1001303}{}{The Wasteland Mutants}
{1001304}{}{The Pyromaniac Rangers}
{1001305}{}{The Pyromaniac Rangers}
{1001306}{}{The Bad Snipers}
{1001307}{}{The Bad Snipers}
{1001308}{}{The Tall Patrol}
{1001309}{}{The Tall Patrol}
{1001310}{}{The North Club}
{1001311}{}{The North Club}
{1001312}{}{The Tall Soldiers}
{1001313}{}{The Tall Soldiers}
{1001314}{}{The Mad Jumpers}
{1001315}{}{The Mad Jumpers}
{1001316}{}{The Tedious Army}
{1001317}{}{The Tedious Army}
{1001318}{}{The Greasy Pyromaniacs}
{1001319}{}{The Greasy Pyromaniacs}
{1001320}{}{The Greasy Killers}
{1001321}{}{The Greasy Killers}
{1001322}{}{The Metal Club}
{1001323}{}{The Metal Club}
{1001324}{}{The Angry Mobsters}
{1001325}{}{The Angry Mobsters}
{1001326}{}{The Hub Geckos}
{1001327}{}{The Hub Geckos}
{1001328}{}{The New Reno Radscorpions}
{1001329}{}{The New Reno Radscorpions}
{1001330}{}{The Boneyard Militia}
{1001331}{}{The Boneyard Militia}
{1001332}{}{The San Francisco Children}
{1001333}{}{The San Francisco Children}
{1001333}{}{San Francisco Children}
{1001334}{}{The South Hunters}
{1001335}{}{The South Hunters}
{1001336}{}{The Evil Guys}
{1001337}{}{The Evil Guys}
{1001338}{}{The Bad Gang}
{1001339}{}{The Bad Gang}
{1001340}{}{The Irradiated Rangers}
{1001341}{}{The Irradiated Rangers}
{1001342}{}{The Unlucky Inquisitors}
{1001343}{}{The Unlucky Inquisitors}
{1001344}{}{The Lucky Lieutenants}
{1001345}{}{The Lucky Lieutenants}
{1001346}{}{The Murder Empire}
{1001347}{}{The Murder Empire}
{1001348}{}{The Spartans}
{1001349}{}{The Spartans}
{1001350}{}{The Gloomy Communists}
{1001351}{}{The Gloomy Communists}
{1001352}{}{The Steel Men}
{1001353}{}{The Steel Men}
{1001354}{}{The Greedy Rats}
{1001355}{}{The Greedy Rats}
{1001356}{}{The Broken Hills Punks}
{1001357}{}{The Broken Hills Punks}
{1001358}{}{The Reactor Necromancers}
{1001359}{}{The Reactor Necromancers}
{1001360}{}{The True Barbarians}
{1001361}{}{The True Barbarians}
{1001362}{}{The Steel Hands}
{1001363}{}{The Steel Hands}
{1001364}{}{The Burning Criminals}
{1001365}{}{The Burning Criminals}
{1001366}{}{The Green One-Eyed}
{1001367}{}{The Green One-Eyed}
{1001368}{}{The California Wings}
{1001369}{}{The California Wings}
{1001370}{}{The Burning Lizards}
{1001371}{}{The Burning Lizards}
{1001372}{}{The Six Cats}
{1001373}{}{The Six Cats}
{1001374}{}{The Redding Meteors}
{1001375}{}{The Redding Meteors}
{1001376}{}{The Silent Arrows}
{1001377}{}{The Silent Arrows}
{1001378}{}{The Reactor Punks}
{1001379}{}{The Reactor Punks}
{1001380}{}{The Den Killers}
{1001381}{}{The Den Killers}
{1001382}{}{The Bleeding Dreamers}
{1001383}{}{The Bleeding Dreamers}
{1001384}{}{The Evil Jumpers}
{1001385}{}{The Evil Jumpers}
{1001386}{}{The Strange Cooks}
{1001387}{}{The Strange Cooks}
{1001388}{}{The Burning Lions}
{1001389}{}{The Burning Lions}
{1001390}{}{The Forest's Bluesuits}
{1001391}{}{The Forest's Bluesuits}
{1001392}{}{The Crazy Squad}
{1001393}{}{The Crazy Squad}
{1001394}{}{The Broken Hills Maniacs}
{1001395}{}{The Broken Hills Maniacs}
{1001396}{}{The Mutated Women}
{1001397}{}{The Mutated Women}
{1001398}{}{The Lost Hills Squadron}
{1001399}{}{The Lost Hills Squadron}
{1001400}{}{The Ultimate Crew}
{1001401}{}{The Ultimate Crew}
{1001402}{}{The Den Cannibals}
{1001403}{}{The Den Cannibals}
{1001404}{}{The Nasty Women}
{1001405}{}{The Nasty Women}
{1001406}{}{The True Bits}
{1001407}{}{The True Bits}
{1001408}{}{The Junkie Bulls}
{1001409}{}{The Junkie Bulls}
{1001410}{}{The Nasty Deputies}
{1001411}{}{The Nasty Deputies}
{1001412}{}{The Gecko Council}
{1001413}{}{The Gecko Council}
{1001414}{}{The Reading Strangers}
{1001415}{}{The Reading Strangers}
{1001416}{}{The Wise Rangers}
{1001417}{}{The Wise Rangers}
{1001418}{}{Ada Lovelace Lovers}
{1001419}{}{Ada Lovelace Lovers}
{1001419}{}{Ada Lovers}
{1001420}{}{The Sneaky Raiders}
{1001421}{}{The Sneaky Raiders}
{1001422}{}{The Five Protectors}
{1001423}{}{The Five Protectors}
{1001424}{}{The United States Republic}
{1001425}{}{The United States Republic}
{1001425}{}{United States Republic}
{1001425}{}{USR}
{1001426}{}{Brothers of Wasteland}
{1001427}{}{Brothers of Wasteland}
{1001427}{}{BOW}
{1001428}{}{Nuclear Rebels Army}
{1001429}{}{Nuclear Rebels Army}
{1001429}{}{NRA}
{1001430}{}{- Red Dot Army -}
{1001431}{}{- Red Dot Army -}
{1001431}{}{-Red Dot Army-}
{1001432}{}{Murder Death Kill}
{1001433}{}{Murder Death Kill}
{1001433}{}{MDK}
{1001434}{}{The Sarmatians}
{1001435}{}{The Sarmatians}
{1001435}{}{Sarmatia}
{1001436}{}{Eastern Hospitality}
{1001437}{}{Eastern Hospitality}
{1001438}{}{Dogs of War}
{1001439}{}{Dogs of War}
{1001439}{}{DOW}
{1001440}{}{The Howlin' Banshees}
{1001441}{}{The Howlin' Banshees}
{1001442}{}{The Flying Mohels}
{1001443}{}{The Flying Mohels}
{1001444}{}{The Gentlemen}
{1001445}{}{The Gentlemen}
{1001446}{}{The Rash}
{1001447}{}{The Rash}
{1001448}{}{The Grave Diggers}
{1001449}{}{The Grave Diggers}
{1001450}{}{The San Francisco Club}
{1001451}{}{The San Francisco Club}
{1001452}{}{The Toxic Avengers}
{1001453}{}{The Toxic Avengers}
{1001454}{}{The Green Fingers}
{1001455}{}{The Green Fingers}
{1001456}{}{The Golgotha Gastronomists}
{1001457}{}{The Golgotha Gastronomists}
{1001457}{}{Golgotha Gastronomists}
{1001458}{}{The Running Wolves}
{1001459}{}{The Running Wolves}
{1001460}{}{The Brutal Menace}
{1001461}{}{The Brutal Menace}
{1001462}{}{The No Hopes}
{1001463}{}{The No Hopes}
{1001464}{}{The Highliners}
{1001465}{}{The Highliners}
{1001466}{}{The Fuel Drinkers}
{1001467}{}{The Fuel Drinkers}
{1001468}{}{The Harebrained}
{1001469}{}{The Harebrained}
{1001470}{}{The Mantis Eaters}
{1001471}{}{The Mantis Eaters}
{1001472}{}{The Flying Roosters}
{1001473}{}{The Flying Roosters}
{1001474}{}{The Happy Folk}
{1001475}{}{The Happy Folk}
{1001476}{}{The Skull Collectors}
{1001477}{}{The Skull Collectors}
{1001478}{}{The Radiators}
{1001479}{}{The Radiators}
{1001480}{}{The Wasteland Poets}
{1001481}{}{The Wasteland Poets}
{1001482}{}{The Lawbringers}
{1001483}{}{The Lawbringers}
{1001484}{}{The Sidewinders}
{1001485}{}{The Sidewinders}
{1001486}{}{The Wolfhounds}
{1001487}{}{The Wolfhounds}
{1001488}{}{The Pistoleros}
{1001489}{}{The Pistoleros}
{1001490}{}{The Facebreakers}
{1001491}{}{The Facebreakers}
{1001492}{}{The Rattlers}
{1001493}{}{The Rattlers}
{1001494}{}{The Face Melters}
{1001495}{}{The Face Melters}
{1001496}{}{The Good 'Ol boys}
{1001497}{}{The Good 'Ol boys}
{1001498}{}{The Hideous Hooligans}
{1001499}{}{The Hideous Hooligans}
{1001500}{}{The Mongrels}
{1001501}{}{The Mongrels}
{1001502}{}{The Transcended Humanity}
{1001503}{}{The Transcended Humanity}
{1001504}{}{The Pigfaced Bastards}
{1001505}{}{The Pigfaced Bastards}
{1001506}{}{The Teachers}
{1001507}{}{The Teachers}
{1001508}{}{The Lost Angels}
{1001509}{}{The Lost Angels}
{1001510}{}{The Black Dragons}
{1001511}{}{The Black Dragons}
{1001512}{}{The Losers}
{1001513}{}{The Losers}
{1001514}{}{The Moose Bitches}
{1001515}{}{The Moose Bitches}
{1001516}{}{The Black Hearts}
{1001517}{}{The Black Hearts}
{1001518}{}{The Black Shadows}
{1001519}{}{The Black Shadows}
{1001520}{}{The Human Abstracts}
{1001521}{}{The Human Abstracts}
{1001522}{}{The Mannequins}
{1001523}{}{The Mannequins}
{1001524}{}{The Phobophiles}
{1001525}{}{The Phobophiles}
{1001526}{}{The Free Cards}
{1001527}{}{The Free Cards}
{1001528}{}{The Dobermen}
{1001529}{}{The Dobermen}
{1001530}{}{The Suicide Machines}
{1001531}{}{The Suicide Machines}
{1001532}{}{The Philosophers}
{1001533}{}{The Philosophers}
{1001534}{}{The Stillborns}
{1001535}{}{The Stillborns}
{1001536}{}{The Night Demons}
{1001537}{}{The Night Demons}
{1001538}{}{The Sons Of The Master}
{1001539}{}{The Sons Of The Master}
{1001540}{}{The Masters Of Disharmony}
{1001541}{}{The Masters Of Disharmony}
{1001542}{}{The Little Devils}
{1001543}{}{The Little Devils}
{1001544}{}{The Recyclers}
{1001545}{}{The Recyclers}
{1001546}{}{The Innocent Miners}
{1001547}{}{The Innocent Miners}
{1001548}{}{San Francisco Triad}
{1001549}{}{San Francisco Triad}
{1001550}{}{The Desert Punks}
{1001551}{}{The Desert Punks}
{1001552}{}{The Three Dogs}
{1001553}{}{The Three Dogs}
{1001554}{}{The Vault Outcasts}
{1001555}{}{The Vault Outcasts}
{1001556}{}{The Church of Violence}
{1001557}{}{The Church of Violence}
{1001558}{}{The Dangerous Dave's Dudes}
{1001559}{}{The Dangerous Dave's Dudes}
{1001559}{}{Dangerous Dave's Dudes}
{1001560}{}{Hungry Hippos}
{1001561}{}{Hungry Hippos}
{1001562}{}{The Iron Hand}
{1001563}{}{The Iron Hand}
{1001564}{}{The Velvet Glove}
{1001565}{}{The Velvet Glove}
{1001566}{}{The Cave Dwellers}
{1001567}{}{The Cave Dwellers}
{1001568}{}{Hells Angels}
{1001569}{}{Hells Angels}
{1001570}{}{The Black Widows}
{1001571}{}{The Black Widows}
{1001572}{}{Redding Miners Union}
{1001573}{}{Redding Miners Union}
{1001574}{}{The Bluesuit Face Stompers}
{1001575}{}{The Bluesuit Face Stompers}
{1001575}{}{Bluesuit Face Stompers}
{1001576}{}{The Shadow Sisters}
{1001577}{}{The Shadow Sisters}
{1001578}{}{Followers of the Gold Nugget}
{1001579}{}{Followers of the Gold Nugget}
{1001579}{}{Gold Nugget}
{1001580}{}{Overseer's Hands}
{1001581}{}{Overseer's Hands}
{1001582}{}{Silent Assassins}
{1001583}{}{Silent Assassins}
{1001584}{}{Skyscraper Defenders}
{1001585}{}{Skyscraper Defenders}
{1001586}{}{The Jerky Jerks Who Make Jerky}
{1001587}{}{The Jerky Jerks Who Make Jerky}
{1001587}{}{Jerky Jerks}
{1001588}{}{Secret Brahmin Lovers}
{1001589}{}{Secret Brahmin Lovers}
{1001590}{}{The Jet Pilots}
{1001591}{}{The Jet Pilots}
{1001592}{}{The Gamma Gulp Vikings}
{1001593}{}{The Gamma Gulp Vikings}
{1001594}{}{Knights of the Wasteland}
{1001595}{}{Knights of the Wasteland}
{1001596}{}{The Punisher's Rangers}
{1001597}{}{The Punisher's Rangers}
{1001598}{}{Battle Hamsters}
{1001599}{}{Battle Hamsters}
{1001600}{}{These Bastards}
{1001601}{}{These Bastards}
{1001602}{}{Soldiers of Thunderstorm}
{1001603}{}{Soldiers of Thunderstorm}
{1001604}{}{Klamath City Rockers}
{1001605}{}{Klamath City Rockers}
{1001606}{}{The Hungry Kids}
{1001607}{}{The Hungry Kids}
{1001608}{}{The Starving Kids}
{1001609}{}{The Starving Kids}
{1001610}{}{The Child Killers}
{1001611}{}{The Child Killers}
{1001612}{}{The Murdered Flowers}
{1001613}{}{The Murdered Flowers}
{1001614}{}{The Ugly Fuckers}
{1001615}{}{The Ugly Fuckers}
{1001616}{}{The Pariah Gang}
{1001617}{}{The Pariah Gang}
{1001618}{}{The Gee-willikers}
{1001619}{}{The Gee-willikers}
{1001620}{}{Pariah Dogs}
{1001621}{}{Pariah Dogs}
{1001622}{}{Karma Dogs}
{1001623}{}{Karma Dogs}
{1001624}{}{Cyber Dogs}
{1001625}{}{Cyber Dogs}
{1001626}{}{Ghoul Incorporated}
{1001627}{}{Ghoul Incorporated}
{1001628}{}{The Angry Radscorpions}
{1001629}{}{The Angry Radscorpions}
{1001630}{}{The Pain Gang}
{1001631}{}{The Pain Gang}
{1001632}{}{The San Francisco Wide Eyes}
{1001633}{}{The San Francisco Wide Eyes}
{1001633}{}{San Francisco Wide Eyes}
{1001634}{}{The Eye Fivers}
{1001635}{}{The Eye Fivers}
{1001636}{}{The Wasteland Mop Crew}
{1001637}{}{The Wasteland Mop Crew}
{1001638}{}{The Wasteland Heroes}
{1001639}{}{The Wasteland Heroes}
{1001640}{}{The Land Wasters}
{1001641}{}{The Land Wasters}
{1001642}{}{The Chainsaw Rippers}
{1001643}{}{The Chainsaw Rippers}
{1001644}{}{Chainsaw Bullet Gang}
{1001645}{}{Chainsaw Bullet Gang}
{1001646}{}{The Greeds}
{1001647}{}{The Greeds}
{1001648}{}{The Family}
{1001649}{}{The Family}
{1001650}{}{Children of Doom}
{1001651}{}{Children of Doom}
{1001652}{}{The Bloody Doom's}
{1001653}{}{The Bloody Doom's}
{1001654}{}{The Highspeed Highways}
{1001655}{}{The Highspeed Highways}
{1001656}{}{The Gang Green}
{1001657}{}{The Gang Green}
{1001658}{}{The Wasteland Survivors}
{1001659}{}{The Wasteland Survivors}
{1001660}{}{The No Hopes}
{1001661}{}{The No Hopes}
{1001662}{}{The Shoot First Gang}
{1001663}{}{The Shoot First Gang}
{1001664}{}{The Sorry's}
{1001665}{}{The Sorry's}
{1001666}{}{The Vindascorps}
{1001667}{}{The Vindascorps}
{1001668}{}{The Generic Name Gang}
{1001669}{}{The Generic Name Gang}
{1001670}{}{The Generic Ass Kickers}
{1001671}{}{The Generic Ass Kickers}
{1001672}{}{The Generic Ass Lickers}
{1001673}{}{The Generic Ass Lickers}
{1001674}{}{The Generic Badasses}
{1001675}{}{The Generic Badasses}
{1001676}{}{San Fran Nomads}
{1001677}{}{San Fran Nomads}
{1001678}{}{The Modoc Woodsmen}
{1001679}{}{The Modoc Woodsmen}
{1001680}{}{The Klamath Skinners}
{1001681}{}{The Klamath Skinners}
{1001682}{}{The Welcome Party}
{1001683}{}{The Welcome Party}
{1001684}{}{The Little Shits}
{1001685}{}{The Little Shits}
{1001686}{}{The Creeping Shadows}
{1001687}{}{The Creeping Shadows}
{1001688}{}{The Hidden Eyes}
{1001689}{}{The Hidden Eyes}
{1001690}{}{The Last Light}
{1001691}{}{The Last Light}
{1001692}{}{The Lost Children}
{1001693}{}{The Lost Children}
{1001694}{}{The Missing Children}
{1001695}{}{The Missing Children}
{1001696}{}{The Missing Arms}
{1001697}{}{The Missing Arms}
{1001698}{}{The Broken Pistols}
{1001699}{}{The Broken Pistols}
{1001700}{}{The Young Killers}
{1001701}{}{The Young Killers}
{1001702}{}{The Inexperienced}
{1001703}{}{The Inexperienced}
{1001704}{}{The Last Forgotten}
{1001705}{}{The Last Forgotten}
{1001706}{}{The Angry Forgotten}
{1001707}{}{The Angry Forgotten}
{1001708}{}{The Sleeping Barrels}
{1001709}{}{The Sleeping Barrels}
{1001710}{}{The Hello Pussies}
{1001711}{}{The Hello Pussies}
{1001712}{}{The Segmentation Fault Lovers}
{1001713}{}{The Segmentation Fault Lovers}
{1001713}{}{Segmentation Fault Lovers}
{1001714}{}{The Shoot-the-flag Gang}
{1001715}{}{The Shoot-the-flag Gang}
{1001716}{}{The Shootkills}
{1001717}{}{The Shootkills}
{1001718}{}{The Poison Cookie Gang}
{1001719}{}{The Poison Cookie Gang}
{1001720}{}{The Steel Iris}
{1001721}{}{The Steel Iris}
{1001722}{}{The Bloody Rose}
{1001723}{}{The Bloody Rose}
{1001724}{}{The Enslaved}
{1001725}{}{The Enslaved}
{1001726}{}{The Burning Flares}
{1001727}{}{The Burning Flares}
{1001728}{}{The Cross Dressers}
{1001729}{}{The Cross Dressers}
{1001730}{}{The Men In Pink}
{1001731}{}{The Men In Pink}
{1001732}{}{The Foot Patrol}
{1001733}{}{The Foot Patrol}
{1001734}{}{The Outta Gum Gang}
{1001735}{}{The Outta Gum Gang}
{1001736}{}{The Bullet Ghosts}
{1001737}{}{The Bullet Ghosts}
{1001738}{}{The Widows}
{1001739}{}{The Widows}
{1001740}{}{The Ghoul Protectors}
{1001741}{}{The Ghoul Protectors}
{1001742}{}{The Ghoul Conspiracy}
{1001743}{}{The Ghoul Conspiracy}
{1001744}{}{The Foul Critters}
{1001745}{}{The Foul Critters}
{1001746}{}{The Lost Lights of New Reno}
{1001747}{}{The Lost Lights of New Reno}
{1001747}{}{Lost Lights of New Reno}
{1001748}{}{The Whiskey Bob Club}
{1001749}{}{The Whiskey Bob Club}
{1001750}{}{The Rum Riders}
{1001751}{}{The Rum Riders}
{1001752}{}{The Glow Scavengers}
{1001753}{}{The Glow Scavengers}
{1001754}{}{The A-Bomb Followers}
{1001755}{}{The A-Bomb Followers}
{1001756}{}{The Skulls Collectors}
{1001757}{}{The Skulls Collectors}
{1001758}{}{The Booze Brothers}
{1001759}{}{The Booze Brothers}
{1001760}{}{The Jet Junkies}
{1001761}{}{The Jet Junkies}
{1001762}{}{These Damn Addicts}
{1001763}{}{These Damn Addicts}
{1001764}{}{The Wasteland Poets}
{1001765}{}{The Wasteland Poets}
{1001766}{}{The Boys from Thunder Avenue}
{1001767}{}{The Boys from Thunder Avenue}
{1001767}{}{Boys from Thunder Avenue}
{1001768}{}{The Boys from Barter Street}
{1001769}{}{The Boys from Barter Street}
{1001769}{}{Boys from Barter Street}
{1001770}{}{The Mutant Haters}
{1001771}{}{The Mutant Haters}
{1001772}{}{The Ghoul Haters}
{1001773}{}{The Ghoul Haters}
{1001774}{}{The Dogs of L.A.}
{1001775}{}{The Dogs of L.A.}
{1001776}{}{Broken Hills Uranium Company}
{1001777}{}{Broken Hills Uranium Company}
{1001777}{}{Uranium Company}
{1001778}{}{Mutant Liberation Army}
{1001779}{}{Mutant Liberation Army}
{1001780}{}{The Paranoid Freaks}
{1001781}{}{The Paranoid Freaks}
{1001782}{}{The Crazy Rats}
{1001783}{}{The Crazy Rats}
{1001784}{}{The Ghoul Whores}
{1001785}{}{The Ghoul Whores}
{1001786}{}{Cat's Paw Redactors}
{1001787}{}{Cat's Paw Redactors}
{1001788}{}{Free Miners Federation}
{1001789}{}{Free Miners Federation}
{1001790}{}{The New Reno Hookers Union}
{1001791}{}{The New Reno Hookers Union}
{1001791}{}{New Reno Hookers Union}
{1001792}{}{Mrs. Bishops Loveslaves}
{1001793}{}{Mrs. Bishops Loveslaves}
{1001794}{}{Nine Guys named Rob}
{1001795}{}{Nine Guys named Rob}
{1001796}{}{The San Francisco Tree Huggers}
{1001797}{}{The San Francisco Tree Huggers}
{1001797}{}{Tree Huggers}
{1001798}{}{The Pistoleros}
{1001799}{}{The Pistoleros}
{1001800}{}{The Wan Chai Mercenaries}
{1001801}{}{The Wan Chai Mercenaries}
{1001802}{}{Mothers Against Town Control}
{1001803}{}{Mothers Against Town Control}
{1001803}{}{Mothers Against TC}
{1001804}{}{The Ten Milimiters}
{1001805}{}{The Ten Milimiters}
{1001806}{}{The Meikyokan Yakuza}
{1001807}{}{The Meikyokan Yakuza}
{1001808}{}{The Musashi Yakuza}
{1001809}{}{The Musashi Yakuza}
{1001810}{}{The Kanamori Yakuza}
{1001811}{}{The Kanamori Yakuza}
{1001812}{}{The Hanazono Yakuza}
{1001813}{}{The Hanazono Yakuza}
{1001814}{}{Jimmy and Bob Gang}
{1001815}{}{Jimmy and Bob Gang}
{1001816}{}{The Wasteland Angels}
{1001817}{}{The Wasteland Angels}
{1001818}{}{The Abducted Ones}
{1001819}{}{The Abducted Ones}
{1001820}{}{The Calm Crafters}
{1001821}{}{The Calm Crafters}
{1001822}{}{The Creative Collectors}
{1001823}{}{The Creative Collectors}
{1001824}{}{The Enthusiastic Engineers}
{1001825}{}{The Enthusiastic Engineers}
{1001825}{}{Enthusiastic Engineers}
{1001826}{}{The Eccentric Gangmen}
{1001827}{}{The Eccentric Gangmen}
{1001828}{}{The Dark Shadows}
{1001829}{}{The Dark Shadows}
{1001830}{}{The Fist Bashers}
{1001831}{}{The Fist Bashers}
{1001832}{}{The Flaming Skulls}
{1001833}{}{The Flaming Skulls}
{1001834}{}{The Lucky Rollers}
{1001835}{}{The Lucky Rollers}
{1001836}{}{The Mad Adventureres}
{1001837}{}{The Mad Adventureres}
{1001838}{}{The Open-Minded Fools}
{1001839}{}{The Open-Minded Fools}
{1001840}{}{The Spice Collectors}
{1001841}{}{The Spice Collectors}
{1001842}{}{The Servants of the False God}
{1001843}{}{The Servants of the False God}
{1001843}{}{Servants of the False God}
{1001844}{}{The Rednecks}
{1001845}{}{The Rednecks}
{1001846}{}{The Desert Striders}
{1001847}{}{The Desert Striders}
{1001848}{}{Boneyard Pirates}
{1001849}{}{Boneyard Pirates}
{1001850}{}{San Francisco Buccaneers}
{1001851}{}{San Francisco Buccaneers}
{1001852}{}{Brahmin Express}
{1001853}{}{Brahmin Express}
{1001854}{}{Wasteland Post}
{1001855}{}{Wasteland Post}
{1001856}{}{The Laughing Men}
{1001857}{}{The Laughing Men}
{1001858}{}{Black Rocks}
{1001859}{}{Black Rocks}
{1001860}{}{Desert Drifters}
{1001861}{}{Desert Drifters}
{1001862}{}{Wasteland Drifters}
{1001863}{}{Wasteland Drifters}
{1001864}{}{Desert Roamers}
{1001865}{}{Desert Roamers}
{1001866}{}{Wasteland Roamers}
{1001867}{}{Wasteland Roamers}
{1001868}{}{The Tent Dwellers}
{1001869}{}{The Tent Dwellers}
{1001870}{}{New Reno Dealers}
{1001871}{}{New Reno Dealers}
{1001872}{}{Kaiser's Legion}
{1001873}{}{Kaiser's Legion}
{1001874}{}{The Frustrated Artists}
{1001875}{}{The Frustrated Artists}
{1001876}{}{Post Nuclear Luddites}
{1001877}{}{Post Nuclear Luddites}
{1001878}{}{The Black Flag}
{1001879}{}{The Black Flag}
{1001880}{}{The Wasteland Band}
{1001881}{}{The Wasteland Band}
{1001882}{}{The Nuclear Outcasts}
{1001883}{}{The Nuclear Outcasts}
{1001884}{}{Legion of Chaos}
{1001885}{}{Legion of Chaos}
{1001886}{}{Fatal Force}
{1001887}{}{Fatal Force}
{1001888}{}{The Thousand Suns}
{1001889}{}{The Thousand Suns}
{1001890}{}{The Orphanage}
{1001891}{}{The Orphanage}
{1001892}{}{The Black Cats}
{1001893}{}{The Black Cats}
{1001894}{}{Femme Fatales}
{1001895}{}{Femme Fatales}
{1001896}{}{Bunch of Jerks}
{1001897}{}{Bunch of Jerks}
{1001898}{}{The Kamikaze Franciscos}
{1001899}{}{The Kamikaze Franciscos}
{1001900}{}{The Armed Ladies}
{1001901}{}{The Armed Ladies}
{1001902}{}{The Nuclear Sandwiches}
{1001903}{}{The Nuclear Sandwiches}
{1001904}{}{The Candy-Machines}
{1001905}{}{The Candy-Machines}
{1001906}{}{Momma's Rat Eaters}
{1001907}{}{Momma's Rat Eaters}
{1001908}{}{The Bleak Promises}
{1001909}{}{The Bleak Promises}
{1001910}{}{Section 8}
{1001911}{}{Section 8}
{1001912}{}{The Smokers}
{1001913}{}{The Smokers}
{1001913}{}{Momma's Rat Eaters}
{1001914}{}{Momma's Rat Eaters}
{1001915}{}{The Toilets}
{1001916}{}{The Toilets}
#1002000 - end point for factions names (change in factions_names.fos)
