DIR_TOP = ..
TARGET = client_parameters
DEFINES = __CLIENT
SRC = \
    parameters_client.cpp \
    \
    AngelScript.cpp \
    $(DIR_TOP)/buffer_lazy/buffer_lazy.cpp \
    $(DIR_TOP)/online_stats/client_online_stats.cpp \
### $(DIR_TOP)/online_stats/xfiregameclient.cpp \
    utils.cpp \

include $(DIR_TOP)/Makefile.2238

all: $(SO)
