DIR_TOP = ..
TARGET = Utils
DEFINES = __SERVER
SRC = \
    dllmain.cpp \
    Utils.cpp \
    \
    AngelScript.cpp \
    ExtEvents.cpp \
    NoobServer.cpp \
    ProtoMapEx.cpp \
    $(DIR_TOP)/buffer_lazy/buffer_lazy.cpp

include $(DIR_TOP)/Makefile.2238

all: $(SO)
